'use strict';
// Complete parameter catalog for admission.
const entity='admission';
const parameters=[
  { name: 'patientId', mode: 'input', type: 'string', required: true, nullable: true, defaultValue: null, description: 'patientId parameter for admission', index: 1 },
  { name: 'patientId', mode: 'filter', type: 'string', required: true, nullable: true, defaultValue: null, description: 'patientId parameter for admission', index: 1 },
  { name: 'patientId', mode: 'sort', type: 'string', required: true, nullable: true, defaultValue: false, description: 'patientId parameter for admission', index: 1 },
  { name: 'patientId', mode: 'search', type: 'string', required: true, nullable: true, defaultValue: null, description: 'patientId parameter for admission', index: 1 },
  { name: 'patientId', mode: 'export', type: 'string', required: true, nullable: true, defaultValue: false, description: 'patientId parameter for admission', index: 1 },
  { name: 'patientIdMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum patientId filter for admission', index: 1 },
  { name: 'patientIdMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum patientId filter for admission', index: 1 },
  { name: 'doctorId', mode: 'input', type: 'string', required: true, nullable: true, defaultValue: null, description: 'doctorId parameter for admission', index: 2 },
  { name: 'doctorId', mode: 'filter', type: 'string', required: true, nullable: true, defaultValue: null, description: 'doctorId parameter for admission', index: 2 },
  { name: 'doctorId', mode: 'sort', type: 'string', required: true, nullable: true, defaultValue: false, description: 'doctorId parameter for admission', index: 2 },
  { name: 'doctorId', mode: 'search', type: 'string', required: true, nullable: true, defaultValue: null, description: 'doctorId parameter for admission', index: 2 },
  { name: 'doctorId', mode: 'export', type: 'string', required: true, nullable: true, defaultValue: false, description: 'doctorId parameter for admission', index: 2 },
  { name: 'doctorIdMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum doctorId filter for admission', index: 2 },
  { name: 'doctorIdMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum doctorId filter for admission', index: 2 },
  { name: 'wardId', mode: 'input', type: 'string', required: true, nullable: true, defaultValue: null, description: 'wardId parameter for admission', index: 3 },
  { name: 'wardId', mode: 'filter', type: 'string', required: true, nullable: true, defaultValue: null, description: 'wardId parameter for admission', index: 3 },
  { name: 'wardId', mode: 'sort', type: 'string', required: true, nullable: true, defaultValue: false, description: 'wardId parameter for admission', index: 3 },
  { name: 'wardId', mode: 'search', type: 'string', required: true, nullable: true, defaultValue: null, description: 'wardId parameter for admission', index: 3 },
  { name: 'wardId', mode: 'export', type: 'string', required: true, nullable: true, defaultValue: false, description: 'wardId parameter for admission', index: 3 },
  { name: 'wardIdMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum wardId filter for admission', index: 3 },
  { name: 'wardIdMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum wardId filter for admission', index: 3 },
  { name: 'bedId', mode: 'input', type: 'string', required: false, nullable: true, defaultValue: null, description: 'bedId parameter for admission', index: 4 },
  { name: 'bedId', mode: 'filter', type: 'string', required: false, nullable: true, defaultValue: null, description: 'bedId parameter for admission', index: 4 },
  { name: 'bedId', mode: 'sort', type: 'string', required: false, nullable: true, defaultValue: false, description: 'bedId parameter for admission', index: 4 },
  { name: 'bedId', mode: 'search', type: 'string', required: false, nullable: true, defaultValue: null, description: 'bedId parameter for admission', index: 4 },
  { name: 'bedId', mode: 'export', type: 'string', required: false, nullable: true, defaultValue: false, description: 'bedId parameter for admission', index: 4 },
  { name: 'bedIdMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum bedId filter for admission', index: 4 },
  { name: 'bedIdMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum bedId filter for admission', index: 4 },
  { name: 'admittedAt', mode: 'input', type: 'string', required: false, nullable: true, defaultValue: null, description: 'admittedAt parameter for admission', index: 5 },
  { name: 'admittedAt', mode: 'filter', type: 'string', required: false, nullable: true, defaultValue: null, description: 'admittedAt parameter for admission', index: 5 },
  { name: 'admittedAt', mode: 'sort', type: 'string', required: false, nullable: true, defaultValue: false, description: 'admittedAt parameter for admission', index: 5 },
  { name: 'admittedAt', mode: 'search', type: 'string', required: false, nullable: true, defaultValue: null, description: 'admittedAt parameter for admission', index: 5 },
  { name: 'admittedAt', mode: 'export', type: 'string', required: false, nullable: true, defaultValue: false, description: 'admittedAt parameter for admission', index: 5 },
  { name: 'admittedAtMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum admittedAt filter for admission', index: 5 },
  { name: 'admittedAtMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum admittedAt filter for admission', index: 5 },
  { name: 'expectedDischargeAt', mode: 'input', type: 'string', required: false, nullable: true, defaultValue: null, description: 'expectedDischargeAt parameter for admission', index: 6 },
  { name: 'expectedDischargeAt', mode: 'filter', type: 'string', required: false, nullable: true, defaultValue: null, description: 'expectedDischargeAt parameter for admission', index: 6 },
  { name: 'expectedDischargeAt', mode: 'sort', type: 'string', required: false, nullable: true, defaultValue: false, description: 'expectedDischargeAt parameter for admission', index: 6 },
  { name: 'expectedDischargeAt', mode: 'search', type: 'string', required: false, nullable: true, defaultValue: null, description: 'expectedDischargeAt parameter for admission', index: 6 },
  { name: 'expectedDischargeAt', mode: 'export', type: 'string', required: false, nullable: true, defaultValue: false, description: 'expectedDischargeAt parameter for admission', index: 6 },
  { name: 'expectedDischargeAtMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum expectedDischargeAt filter for admission', index: 6 },
  { name: 'expectedDischargeAtMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum expectedDischargeAt filter for admission', index: 6 },
  { name: 'dischargeAt', mode: 'input', type: 'string', required: false, nullable: true, defaultValue: null, description: 'dischargeAt parameter for admission', index: 7 },
  { name: 'dischargeAt', mode: 'filter', type: 'string', required: false, nullable: true, defaultValue: null, description: 'dischargeAt parameter for admission', index: 7 },
  { name: 'dischargeAt', mode: 'sort', type: 'string', required: false, nullable: true, defaultValue: false, description: 'dischargeAt parameter for admission', index: 7 },
  { name: 'dischargeAt', mode: 'search', type: 'string', required: false, nullable: true, defaultValue: null, description: 'dischargeAt parameter for admission', index: 7 },
  { name: 'dischargeAt', mode: 'export', type: 'string', required: false, nullable: true, defaultValue: false, description: 'dischargeAt parameter for admission', index: 7 },
  { name: 'dischargeAtMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum dischargeAt filter for admission', index: 7 },
  { name: 'dischargeAtMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum dischargeAt filter for admission', index: 7 },
  { name: 'admissionType', mode: 'input', type: 'string', required: false, nullable: true, defaultValue: null, description: 'admissionType parameter for admission', index: 8 },
  { name: 'admissionType', mode: 'filter', type: 'string', required: false, nullable: true, defaultValue: null, description: 'admissionType parameter for admission', index: 8 },
  { name: 'admissionType', mode: 'sort', type: 'string', required: false, nullable: true, defaultValue: false, description: 'admissionType parameter for admission', index: 8 },
  { name: 'admissionType', mode: 'search', type: 'string', required: false, nullable: true, defaultValue: null, description: 'admissionType parameter for admission', index: 8 },
  { name: 'admissionType', mode: 'export', type: 'string', required: false, nullable: true, defaultValue: false, description: 'admissionType parameter for admission', index: 8 },
  { name: 'admissionTypeMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum admissionType filter for admission', index: 8 },
  { name: 'admissionTypeMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum admissionType filter for admission', index: 8 },
  { name: 'reason', mode: 'input', type: 'string', required: false, nullable: true, defaultValue: null, description: 'reason parameter for admission', index: 9 },
  { name: 'reason', mode: 'filter', type: 'string', required: false, nullable: true, defaultValue: null, description: 'reason parameter for admission', index: 9 },
  { name: 'reason', mode: 'sort', type: 'string', required: false, nullable: true, defaultValue: false, description: 'reason parameter for admission', index: 9 },
  { name: 'reason', mode: 'search', type: 'string', required: false, nullable: true, defaultValue: null, description: 'reason parameter for admission', index: 9 },
  { name: 'reason', mode: 'export', type: 'string', required: false, nullable: true, defaultValue: false, description: 'reason parameter for admission', index: 9 },
  { name: 'reasonMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum reason filter for admission', index: 9 },
  { name: 'reasonMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum reason filter for admission', index: 9 },
  { name: 'status', mode: 'input', type: 'string', required: false, nullable: true, defaultValue: null, description: 'status parameter for admission', index: 10 },
  { name: 'status', mode: 'filter', type: 'string', required: false, nullable: true, defaultValue: null, description: 'status parameter for admission', index: 10 },
  { name: 'status', mode: 'sort', type: 'string', required: false, nullable: true, defaultValue: false, description: 'status parameter for admission', index: 10 },
  { name: 'status', mode: 'search', type: 'string', required: false, nullable: true, defaultValue: null, description: 'status parameter for admission', index: 10 },
  { name: 'status', mode: 'export', type: 'string', required: false, nullable: true, defaultValue: false, description: 'status parameter for admission', index: 10 },
  { name: 'statusMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum status filter for admission', index: 10 },
  { name: 'statusMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum status filter for admission', index: 10 },
  { name: 'attendingTeam', mode: 'input', type: 'string', required: false, nullable: true, defaultValue: null, description: 'attendingTeam parameter for admission', index: 11 },
  { name: 'attendingTeam', mode: 'filter', type: 'string', required: false, nullable: true, defaultValue: null, description: 'attendingTeam parameter for admission', index: 11 },
  { name: 'attendingTeam', mode: 'sort', type: 'string', required: false, nullable: true, defaultValue: false, description: 'attendingTeam parameter for admission', index: 11 },
  { name: 'attendingTeam', mode: 'search', type: 'string', required: false, nullable: true, defaultValue: null, description: 'attendingTeam parameter for admission', index: 11 },
  { name: 'attendingTeam', mode: 'export', type: 'string', required: false, nullable: true, defaultValue: false, description: 'attendingTeam parameter for admission', index: 11 },
  { name: 'attendingTeamMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum attendingTeam filter for admission', index: 11 },
  { name: 'attendingTeamMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum attendingTeam filter for admission', index: 11 },
];

function get(name){return parameters.find(p=>p.name===name)||null;}
function list(mode){return mode?parameters.filter(p=>p.mode===mode):[...parameters];}
function required(){return parameters.filter(p=>p.required);}
function validateParameter(name,value){const p=get(name);if(!p)return {ok:false,code:'UNKNOWN_PARAMETER'};if(value===null&&p.nullable)return {ok:true};if(p.type==='number'&&typeof value!=='number')return {ok:false,code:'TYPE_ERROR'};if(p.type==='boolean'&&typeof value!=='boolean')return {ok:false,code:'TYPE_ERROR'};if(p.type==='string'&&typeof value!=='string')return {ok:false,code:'TYPE_ERROR'};return {ok:true};}
function validateObject(input={}){const errors=[];for(const p of required()){if(input[p.name]===undefined||input[p.name]===null||input[p.name]==='')errors.push({field:p.name,code:'REQUIRED'});}for(const [k,v] of Object.entries(input)){const result=validateParameter(k,v);if(!result.ok)errors.push({field:k,code:result.code});}return errors;}
function defaults(){return Object.fromEntries(parameters.filter(p=>p.defaultValue!==null).map(p=>[p.name,p.defaultValue]));}
function describe(){return {entity,parameterCount:parameters.length,parameters};}
module.exports={entity,parameters,get,list,required,validateParameter,validateObject,defaults,describe};
