'use strict';
// Complete parameter catalog for anesthesiaRecord.
const entity='anesthesiaRecord';
const parameters=[
  { name: 'patientId', mode: 'input', type: 'string', required: true, nullable: true, defaultValue: null, description: 'patientId parameter for anesthesiaRecord', index: 1 },
  { name: 'patientId', mode: 'filter', type: 'string', required: true, nullable: true, defaultValue: null, description: 'patientId parameter for anesthesiaRecord', index: 1 },
  { name: 'patientId', mode: 'sort', type: 'string', required: true, nullable: true, defaultValue: false, description: 'patientId parameter for anesthesiaRecord', index: 1 },
  { name: 'patientId', mode: 'search', type: 'string', required: true, nullable: true, defaultValue: null, description: 'patientId parameter for anesthesiaRecord', index: 1 },
  { name: 'patientId', mode: 'export', type: 'string', required: true, nullable: true, defaultValue: false, description: 'patientId parameter for anesthesiaRecord', index: 1 },
  { name: 'patientIdMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum patientId filter for anesthesiaRecord', index: 1 },
  { name: 'patientIdMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum patientId filter for anesthesiaRecord', index: 1 },
  { name: 'procedureId', mode: 'input', type: 'string', required: true, nullable: true, defaultValue: null, description: 'procedureId parameter for anesthesiaRecord', index: 2 },
  { name: 'procedureId', mode: 'filter', type: 'string', required: true, nullable: true, defaultValue: null, description: 'procedureId parameter for anesthesiaRecord', index: 2 },
  { name: 'procedureId', mode: 'sort', type: 'string', required: true, nullable: true, defaultValue: false, description: 'procedureId parameter for anesthesiaRecord', index: 2 },
  { name: 'procedureId', mode: 'search', type: 'string', required: true, nullable: true, defaultValue: null, description: 'procedureId parameter for anesthesiaRecord', index: 2 },
  { name: 'procedureId', mode: 'export', type: 'string', required: true, nullable: true, defaultValue: false, description: 'procedureId parameter for anesthesiaRecord', index: 2 },
  { name: 'procedureIdMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum procedureId filter for anesthesiaRecord', index: 2 },
  { name: 'procedureIdMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum procedureId filter for anesthesiaRecord', index: 2 },
  { name: 'anesthetistId', mode: 'input', type: 'string', required: true, nullable: true, defaultValue: null, description: 'anesthetistId parameter for anesthesiaRecord', index: 3 },
  { name: 'anesthetistId', mode: 'filter', type: 'string', required: true, nullable: true, defaultValue: null, description: 'anesthetistId parameter for anesthesiaRecord', index: 3 },
  { name: 'anesthetistId', mode: 'sort', type: 'string', required: true, nullable: true, defaultValue: false, description: 'anesthetistId parameter for anesthesiaRecord', index: 3 },
  { name: 'anesthetistId', mode: 'search', type: 'string', required: true, nullable: true, defaultValue: null, description: 'anesthetistId parameter for anesthesiaRecord', index: 3 },
  { name: 'anesthetistId', mode: 'export', type: 'string', required: true, nullable: true, defaultValue: false, description: 'anesthetistId parameter for anesthesiaRecord', index: 3 },
  { name: 'anesthetistIdMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum anesthetistId filter for anesthesiaRecord', index: 3 },
  { name: 'anesthetistIdMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum anesthetistId filter for anesthesiaRecord', index: 3 },
  { name: 'type', mode: 'input', type: 'string', required: false, nullable: true, defaultValue: null, description: 'type parameter for anesthesiaRecord', index: 4 },
  { name: 'type', mode: 'filter', type: 'string', required: false, nullable: true, defaultValue: null, description: 'type parameter for anesthesiaRecord', index: 4 },
  { name: 'type', mode: 'sort', type: 'string', required: false, nullable: true, defaultValue: false, description: 'type parameter for anesthesiaRecord', index: 4 },
  { name: 'type', mode: 'search', type: 'string', required: false, nullable: true, defaultValue: null, description: 'type parameter for anesthesiaRecord', index: 4 },
  { name: 'type', mode: 'export', type: 'string', required: false, nullable: true, defaultValue: false, description: 'type parameter for anesthesiaRecord', index: 4 },
  { name: 'typeMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum type filter for anesthesiaRecord', index: 4 },
  { name: 'typeMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum type filter for anesthesiaRecord', index: 4 },
  { name: 'startAt', mode: 'input', type: 'string', required: false, nullable: true, defaultValue: null, description: 'startAt parameter for anesthesiaRecord', index: 5 },
  { name: 'startAt', mode: 'filter', type: 'string', required: false, nullable: true, defaultValue: null, description: 'startAt parameter for anesthesiaRecord', index: 5 },
  { name: 'startAt', mode: 'sort', type: 'string', required: false, nullable: true, defaultValue: false, description: 'startAt parameter for anesthesiaRecord', index: 5 },
  { name: 'startAt', mode: 'search', type: 'string', required: false, nullable: true, defaultValue: null, description: 'startAt parameter for anesthesiaRecord', index: 5 },
  { name: 'startAt', mode: 'export', type: 'string', required: false, nullable: true, defaultValue: false, description: 'startAt parameter for anesthesiaRecord', index: 5 },
  { name: 'startAtMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum startAt filter for anesthesiaRecord', index: 5 },
  { name: 'startAtMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum startAt filter for anesthesiaRecord', index: 5 },
  { name: 'endAt', mode: 'input', type: 'string', required: false, nullable: true, defaultValue: null, description: 'endAt parameter for anesthesiaRecord', index: 6 },
  { name: 'endAt', mode: 'filter', type: 'string', required: false, nullable: true, defaultValue: null, description: 'endAt parameter for anesthesiaRecord', index: 6 },
  { name: 'endAt', mode: 'sort', type: 'string', required: false, nullable: true, defaultValue: false, description: 'endAt parameter for anesthesiaRecord', index: 6 },
  { name: 'endAt', mode: 'search', type: 'string', required: false, nullable: true, defaultValue: null, description: 'endAt parameter for anesthesiaRecord', index: 6 },
  { name: 'endAt', mode: 'export', type: 'string', required: false, nullable: true, defaultValue: false, description: 'endAt parameter for anesthesiaRecord', index: 6 },
  { name: 'endAtMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum endAt filter for anesthesiaRecord', index: 6 },
  { name: 'endAtMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum endAt filter for anesthesiaRecord', index: 6 },
  { name: 'asaClass', mode: 'input', type: 'string', required: false, nullable: true, defaultValue: null, description: 'asaClass parameter for anesthesiaRecord', index: 7 },
  { name: 'asaClass', mode: 'filter', type: 'string', required: false, nullable: true, defaultValue: null, description: 'asaClass parameter for anesthesiaRecord', index: 7 },
  { name: 'asaClass', mode: 'sort', type: 'string', required: false, nullable: true, defaultValue: false, description: 'asaClass parameter for anesthesiaRecord', index: 7 },
  { name: 'asaClass', mode: 'search', type: 'string', required: false, nullable: true, defaultValue: null, description: 'asaClass parameter for anesthesiaRecord', index: 7 },
  { name: 'asaClass', mode: 'export', type: 'string', required: false, nullable: true, defaultValue: false, description: 'asaClass parameter for anesthesiaRecord', index: 7 },
  { name: 'asaClassMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum asaClass filter for anesthesiaRecord', index: 7 },
  { name: 'asaClassMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum asaClass filter for anesthesiaRecord', index: 7 },
  { name: 'notes', mode: 'input', type: 'string', required: false, nullable: true, defaultValue: null, description: 'notes parameter for anesthesiaRecord', index: 8 },
  { name: 'notes', mode: 'filter', type: 'string', required: false, nullable: true, defaultValue: null, description: 'notes parameter for anesthesiaRecord', index: 8 },
  { name: 'notes', mode: 'sort', type: 'string', required: false, nullable: true, defaultValue: false, description: 'notes parameter for anesthesiaRecord', index: 8 },
  { name: 'notes', mode: 'search', type: 'string', required: false, nullable: true, defaultValue: null, description: 'notes parameter for anesthesiaRecord', index: 8 },
  { name: 'notes', mode: 'export', type: 'string', required: false, nullable: true, defaultValue: false, description: 'notes parameter for anesthesiaRecord', index: 8 },
  { name: 'notesMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum notes filter for anesthesiaRecord', index: 8 },
  { name: 'notesMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum notes filter for anesthesiaRecord', index: 8 },
  { name: 'status', mode: 'input', type: 'string', required: false, nullable: true, defaultValue: null, description: 'status parameter for anesthesiaRecord', index: 9 },
  { name: 'status', mode: 'filter', type: 'string', required: false, nullable: true, defaultValue: null, description: 'status parameter for anesthesiaRecord', index: 9 },
  { name: 'status', mode: 'sort', type: 'string', required: false, nullable: true, defaultValue: false, description: 'status parameter for anesthesiaRecord', index: 9 },
  { name: 'status', mode: 'search', type: 'string', required: false, nullable: true, defaultValue: null, description: 'status parameter for anesthesiaRecord', index: 9 },
  { name: 'status', mode: 'export', type: 'string', required: false, nullable: true, defaultValue: false, description: 'status parameter for anesthesiaRecord', index: 9 },
  { name: 'statusMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum status filter for anesthesiaRecord', index: 9 },
  { name: 'statusMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum status filter for anesthesiaRecord', index: 9 },
];

function get(name){return parameters.find(p=>p.name===name)||null;}
function list(mode){return mode?parameters.filter(p=>p.mode===mode):[...parameters];}
function required(){return parameters.filter(p=>p.required);}
function validateParameter(name,value){const p=get(name);if(!p)return {ok:false,code:'UNKNOWN_PARAMETER'};if(value===null&&p.nullable)return {ok:true};if(p.type==='number'&&typeof value!=='number')return {ok:false,code:'TYPE_ERROR'};if(p.type==='boolean'&&typeof value!=='boolean')return {ok:false,code:'TYPE_ERROR'};if(p.type==='string'&&typeof value!=='string')return {ok:false,code:'TYPE_ERROR'};return {ok:true};}
function validateObject(input={}){const errors=[];for(const p of required()){if(input[p.name]===undefined||input[p.name]===null||input[p.name]==='')errors.push({field:p.name,code:'REQUIRED'});}for(const [k,v] of Object.entries(input)){const result=validateParameter(k,v);if(!result.ok)errors.push({field:k,code:result.code});}return errors;}
function defaults(){return Object.fromEntries(parameters.filter(p=>p.defaultValue!==null).map(p=>[p.name,p.defaultValue]));}
function describe(){return {entity,parameterCount:parameters.length,parameters};}
module.exports={entity,parameters,get,list,required,validateParameter,validateObject,defaults,describe};
