'use strict';
// Complete parameter catalog for appointment.
const entity='appointment';
const parameters=[
  { name: 'patientId', mode: 'input', type: 'string', required: true, nullable: true, defaultValue: null, description: 'patientId parameter for appointment', index: 1 },
  { name: 'patientId', mode: 'filter', type: 'string', required: true, nullable: true, defaultValue: null, description: 'patientId parameter for appointment', index: 1 },
  { name: 'patientId', mode: 'sort', type: 'string', required: true, nullable: true, defaultValue: false, description: 'patientId parameter for appointment', index: 1 },
  { name: 'patientId', mode: 'search', type: 'string', required: true, nullable: true, defaultValue: null, description: 'patientId parameter for appointment', index: 1 },
  { name: 'patientId', mode: 'export', type: 'string', required: true, nullable: true, defaultValue: false, description: 'patientId parameter for appointment', index: 1 },
  { name: 'patientIdMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum patientId filter for appointment', index: 1 },
  { name: 'patientIdMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum patientId filter for appointment', index: 1 },
  { name: 'doctorId', mode: 'input', type: 'string', required: true, nullable: true, defaultValue: null, description: 'doctorId parameter for appointment', index: 2 },
  { name: 'doctorId', mode: 'filter', type: 'string', required: true, nullable: true, defaultValue: null, description: 'doctorId parameter for appointment', index: 2 },
  { name: 'doctorId', mode: 'sort', type: 'string', required: true, nullable: true, defaultValue: false, description: 'doctorId parameter for appointment', index: 2 },
  { name: 'doctorId', mode: 'search', type: 'string', required: true, nullable: true, defaultValue: null, description: 'doctorId parameter for appointment', index: 2 },
  { name: 'doctorId', mode: 'export', type: 'string', required: true, nullable: true, defaultValue: false, description: 'doctorId parameter for appointment', index: 2 },
  { name: 'doctorIdMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum doctorId filter for appointment', index: 2 },
  { name: 'doctorIdMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum doctorId filter for appointment', index: 2 },
  { name: 'departmentId', mode: 'input', type: 'string', required: true, nullable: true, defaultValue: null, description: 'departmentId parameter for appointment', index: 3 },
  { name: 'departmentId', mode: 'filter', type: 'string', required: true, nullable: true, defaultValue: null, description: 'departmentId parameter for appointment', index: 3 },
  { name: 'departmentId', mode: 'sort', type: 'string', required: true, nullable: true, defaultValue: false, description: 'departmentId parameter for appointment', index: 3 },
  { name: 'departmentId', mode: 'search', type: 'string', required: true, nullable: true, defaultValue: null, description: 'departmentId parameter for appointment', index: 3 },
  { name: 'departmentId', mode: 'export', type: 'string', required: true, nullable: true, defaultValue: false, description: 'departmentId parameter for appointment', index: 3 },
  { name: 'departmentIdMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum departmentId filter for appointment', index: 3 },
  { name: 'departmentIdMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum departmentId filter for appointment', index: 3 },
  { name: 'scheduledAt', mode: 'input', type: 'string', required: false, nullable: true, defaultValue: null, description: 'scheduledAt parameter for appointment', index: 4 },
  { name: 'scheduledAt', mode: 'filter', type: 'string', required: false, nullable: true, defaultValue: null, description: 'scheduledAt parameter for appointment', index: 4 },
  { name: 'scheduledAt', mode: 'sort', type: 'string', required: false, nullable: true, defaultValue: false, description: 'scheduledAt parameter for appointment', index: 4 },
  { name: 'scheduledAt', mode: 'search', type: 'string', required: false, nullable: true, defaultValue: null, description: 'scheduledAt parameter for appointment', index: 4 },
  { name: 'scheduledAt', mode: 'export', type: 'string', required: false, nullable: true, defaultValue: false, description: 'scheduledAt parameter for appointment', index: 4 },
  { name: 'scheduledAtMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum scheduledAt filter for appointment', index: 4 },
  { name: 'scheduledAtMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum scheduledAt filter for appointment', index: 4 },
  { name: 'durationMinutes', mode: 'input', type: 'number', required: false, nullable: true, defaultValue: null, description: 'durationMinutes parameter for appointment', index: 5 },
  { name: 'durationMinutes', mode: 'filter', type: 'number', required: false, nullable: true, defaultValue: null, description: 'durationMinutes parameter for appointment', index: 5 },
  { name: 'durationMinutes', mode: 'sort', type: 'number', required: false, nullable: true, defaultValue: false, description: 'durationMinutes parameter for appointment', index: 5 },
  { name: 'durationMinutes', mode: 'search', type: 'number', required: false, nullable: true, defaultValue: null, description: 'durationMinutes parameter for appointment', index: 5 },
  { name: 'durationMinutes', mode: 'export', type: 'number', required: false, nullable: true, defaultValue: false, description: 'durationMinutes parameter for appointment', index: 5 },
  { name: 'durationMinutesMin', mode: 'range', type: 'number', required: false, nullable: true, defaultValue: null, description: 'Minimum durationMinutes filter for appointment', index: 5 },
  { name: 'durationMinutesMax', mode: 'range', type: 'number', required: false, nullable: true, defaultValue: null, description: 'Maximum durationMinutes filter for appointment', index: 5 },
  { name: 'type', mode: 'input', type: 'string', required: false, nullable: true, defaultValue: null, description: 'type parameter for appointment', index: 6 },
  { name: 'type', mode: 'filter', type: 'string', required: false, nullable: true, defaultValue: null, description: 'type parameter for appointment', index: 6 },
  { name: 'type', mode: 'sort', type: 'string', required: false, nullable: true, defaultValue: false, description: 'type parameter for appointment', index: 6 },
  { name: 'type', mode: 'search', type: 'string', required: false, nullable: true, defaultValue: null, description: 'type parameter for appointment', index: 6 },
  { name: 'type', mode: 'export', type: 'string', required: false, nullable: true, defaultValue: false, description: 'type parameter for appointment', index: 6 },
  { name: 'typeMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum type filter for appointment', index: 6 },
  { name: 'typeMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum type filter for appointment', index: 6 },
  { name: 'priority', mode: 'input', type: 'string', required: false, nullable: true, defaultValue: null, description: 'priority parameter for appointment', index: 7 },
  { name: 'priority', mode: 'filter', type: 'string', required: false, nullable: true, defaultValue: null, description: 'priority parameter for appointment', index: 7 },
  { name: 'priority', mode: 'sort', type: 'string', required: false, nullable: true, defaultValue: false, description: 'priority parameter for appointment', index: 7 },
  { name: 'priority', mode: 'search', type: 'string', required: false, nullable: true, defaultValue: null, description: 'priority parameter for appointment', index: 7 },
  { name: 'priority', mode: 'export', type: 'string', required: false, nullable: true, defaultValue: false, description: 'priority parameter for appointment', index: 7 },
  { name: 'priorityMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum priority filter for appointment', index: 7 },
  { name: 'priorityMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum priority filter for appointment', index: 7 },
  { name: 'reason', mode: 'input', type: 'string', required: false, nullable: true, defaultValue: null, description: 'reason parameter for appointment', index: 8 },
  { name: 'reason', mode: 'filter', type: 'string', required: false, nullable: true, defaultValue: null, description: 'reason parameter for appointment', index: 8 },
  { name: 'reason', mode: 'sort', type: 'string', required: false, nullable: true, defaultValue: false, description: 'reason parameter for appointment', index: 8 },
  { name: 'reason', mode: 'search', type: 'string', required: false, nullable: true, defaultValue: null, description: 'reason parameter for appointment', index: 8 },
  { name: 'reason', mode: 'export', type: 'string', required: false, nullable: true, defaultValue: false, description: 'reason parameter for appointment', index: 8 },
  { name: 'reasonMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum reason filter for appointment', index: 8 },
  { name: 'reasonMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum reason filter for appointment', index: 8 },
  { name: 'status', mode: 'input', type: 'string', required: false, nullable: true, defaultValue: null, description: 'status parameter for appointment', index: 9 },
  { name: 'status', mode: 'filter', type: 'string', required: false, nullable: true, defaultValue: null, description: 'status parameter for appointment', index: 9 },
  { name: 'status', mode: 'sort', type: 'string', required: false, nullable: true, defaultValue: false, description: 'status parameter for appointment', index: 9 },
  { name: 'status', mode: 'search', type: 'string', required: false, nullable: true, defaultValue: null, description: 'status parameter for appointment', index: 9 },
  { name: 'status', mode: 'export', type: 'string', required: false, nullable: true, defaultValue: false, description: 'status parameter for appointment', index: 9 },
  { name: 'statusMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum status filter for appointment', index: 9 },
  { name: 'statusMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum status filter for appointment', index: 9 },
  { name: 'notes', mode: 'input', type: 'string', required: false, nullable: true, defaultValue: null, description: 'notes parameter for appointment', index: 10 },
  { name: 'notes', mode: 'filter', type: 'string', required: false, nullable: true, defaultValue: null, description: 'notes parameter for appointment', index: 10 },
  { name: 'notes', mode: 'sort', type: 'string', required: false, nullable: true, defaultValue: false, description: 'notes parameter for appointment', index: 10 },
  { name: 'notes', mode: 'search', type: 'string', required: false, nullable: true, defaultValue: null, description: 'notes parameter for appointment', index: 10 },
  { name: 'notes', mode: 'export', type: 'string', required: false, nullable: true, defaultValue: false, description: 'notes parameter for appointment', index: 10 },
  { name: 'notesMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum notes filter for appointment', index: 10 },
  { name: 'notesMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum notes filter for appointment', index: 10 },
  { name: 'createdBy', mode: 'input', type: 'string', required: false, nullable: true, defaultValue: null, description: 'createdBy parameter for appointment', index: 11 },
  { name: 'createdBy', mode: 'filter', type: 'string', required: false, nullable: true, defaultValue: null, description: 'createdBy parameter for appointment', index: 11 },
  { name: 'createdBy', mode: 'sort', type: 'string', required: false, nullable: true, defaultValue: false, description: 'createdBy parameter for appointment', index: 11 },
  { name: 'createdBy', mode: 'search', type: 'string', required: false, nullable: true, defaultValue: null, description: 'createdBy parameter for appointment', index: 11 },
  { name: 'createdBy', mode: 'export', type: 'string', required: false, nullable: true, defaultValue: false, description: 'createdBy parameter for appointment', index: 11 },
  { name: 'createdByMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum createdBy filter for appointment', index: 11 },
  { name: 'createdByMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum createdBy filter for appointment', index: 11 },
];

function get(name){return parameters.find(p=>p.name===name)||null;}
function list(mode){return mode?parameters.filter(p=>p.mode===mode):[...parameters];}
function required(){return parameters.filter(p=>p.required);}
function validateParameter(name,value){const p=get(name);if(!p)return {ok:false,code:'UNKNOWN_PARAMETER'};if(value===null&&p.nullable)return {ok:true};if(p.type==='number'&&typeof value!=='number')return {ok:false,code:'TYPE_ERROR'};if(p.type==='boolean'&&typeof value!=='boolean')return {ok:false,code:'TYPE_ERROR'};if(p.type==='string'&&typeof value!=='string')return {ok:false,code:'TYPE_ERROR'};return {ok:true};}
function validateObject(input={}){const errors=[];for(const p of required()){if(input[p.name]===undefined||input[p.name]===null||input[p.name]==='')errors.push({field:p.name,code:'REQUIRED'});}for(const [k,v] of Object.entries(input)){const result=validateParameter(k,v);if(!result.ok)errors.push({field:k,code:result.code});}return errors;}
function defaults(){return Object.fromEntries(parameters.filter(p=>p.defaultValue!==null).map(p=>[p.name,p.defaultValue]));}
function describe(){return {entity,parameterCount:parameters.length,parameters};}
module.exports={entity,parameters,get,list,required,validateParameter,validateObject,defaults,describe};
