'use strict';
// Complete parameter catalog for discharge.
const entity='discharge';
const parameters=[
  { name: 'admissionId', mode: 'input', type: 'string', required: true, nullable: true, defaultValue: null, description: 'admissionId parameter for discharge', index: 1 },
  { name: 'admissionId', mode: 'filter', type: 'string', required: true, nullable: true, defaultValue: null, description: 'admissionId parameter for discharge', index: 1 },
  { name: 'admissionId', mode: 'sort', type: 'string', required: true, nullable: true, defaultValue: false, description: 'admissionId parameter for discharge', index: 1 },
  { name: 'admissionId', mode: 'search', type: 'string', required: true, nullable: true, defaultValue: null, description: 'admissionId parameter for discharge', index: 1 },
  { name: 'admissionId', mode: 'export', type: 'string', required: true, nullable: true, defaultValue: false, description: 'admissionId parameter for discharge', index: 1 },
  { name: 'admissionIdMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum admissionId filter for discharge', index: 1 },
  { name: 'admissionIdMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum admissionId filter for discharge', index: 1 },
  { name: 'patientId', mode: 'input', type: 'string', required: true, nullable: true, defaultValue: null, description: 'patientId parameter for discharge', index: 2 },
  { name: 'patientId', mode: 'filter', type: 'string', required: true, nullable: true, defaultValue: null, description: 'patientId parameter for discharge', index: 2 },
  { name: 'patientId', mode: 'sort', type: 'string', required: true, nullable: true, defaultValue: false, description: 'patientId parameter for discharge', index: 2 },
  { name: 'patientId', mode: 'search', type: 'string', required: true, nullable: true, defaultValue: null, description: 'patientId parameter for discharge', index: 2 },
  { name: 'patientId', mode: 'export', type: 'string', required: true, nullable: true, defaultValue: false, description: 'patientId parameter for discharge', index: 2 },
  { name: 'patientIdMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum patientId filter for discharge', index: 2 },
  { name: 'patientIdMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum patientId filter for discharge', index: 2 },
  { name: 'dischargedAt', mode: 'input', type: 'string', required: true, nullable: true, defaultValue: null, description: 'dischargedAt parameter for discharge', index: 3 },
  { name: 'dischargedAt', mode: 'filter', type: 'string', required: true, nullable: true, defaultValue: null, description: 'dischargedAt parameter for discharge', index: 3 },
  { name: 'dischargedAt', mode: 'sort', type: 'string', required: true, nullable: true, defaultValue: false, description: 'dischargedAt parameter for discharge', index: 3 },
  { name: 'dischargedAt', mode: 'search', type: 'string', required: true, nullable: true, defaultValue: null, description: 'dischargedAt parameter for discharge', index: 3 },
  { name: 'dischargedAt', mode: 'export', type: 'string', required: true, nullable: true, defaultValue: false, description: 'dischargedAt parameter for discharge', index: 3 },
  { name: 'dischargedAtMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum dischargedAt filter for discharge', index: 3 },
  { name: 'dischargedAtMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum dischargedAt filter for discharge', index: 3 },
  { name: 'diagnosis', mode: 'input', type: 'string', required: false, nullable: true, defaultValue: null, description: 'diagnosis parameter for discharge', index: 4 },
  { name: 'diagnosis', mode: 'filter', type: 'string', required: false, nullable: true, defaultValue: null, description: 'diagnosis parameter for discharge', index: 4 },
  { name: 'diagnosis', mode: 'sort', type: 'string', required: false, nullable: true, defaultValue: false, description: 'diagnosis parameter for discharge', index: 4 },
  { name: 'diagnosis', mode: 'search', type: 'string', required: false, nullable: true, defaultValue: null, description: 'diagnosis parameter for discharge', index: 4 },
  { name: 'diagnosis', mode: 'export', type: 'string', required: false, nullable: true, defaultValue: false, description: 'diagnosis parameter for discharge', index: 4 },
  { name: 'diagnosisMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum diagnosis filter for discharge', index: 4 },
  { name: 'diagnosisMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum diagnosis filter for discharge', index: 4 },
  { name: 'condition', mode: 'input', type: 'string', required: false, nullable: true, defaultValue: null, description: 'condition parameter for discharge', index: 5 },
  { name: 'condition', mode: 'filter', type: 'string', required: false, nullable: true, defaultValue: null, description: 'condition parameter for discharge', index: 5 },
  { name: 'condition', mode: 'sort', type: 'string', required: false, nullable: true, defaultValue: false, description: 'condition parameter for discharge', index: 5 },
  { name: 'condition', mode: 'search', type: 'string', required: false, nullable: true, defaultValue: null, description: 'condition parameter for discharge', index: 5 },
  { name: 'condition', mode: 'export', type: 'string', required: false, nullable: true, defaultValue: false, description: 'condition parameter for discharge', index: 5 },
  { name: 'conditionMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum condition filter for discharge', index: 5 },
  { name: 'conditionMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum condition filter for discharge', index: 5 },
  { name: 'instructions', mode: 'input', type: 'string', required: false, nullable: true, defaultValue: null, description: 'instructions parameter for discharge', index: 6 },
  { name: 'instructions', mode: 'filter', type: 'string', required: false, nullable: true, defaultValue: null, description: 'instructions parameter for discharge', index: 6 },
  { name: 'instructions', mode: 'sort', type: 'string', required: false, nullable: true, defaultValue: false, description: 'instructions parameter for discharge', index: 6 },
  { name: 'instructions', mode: 'search', type: 'string', required: false, nullable: true, defaultValue: null, description: 'instructions parameter for discharge', index: 6 },
  { name: 'instructions', mode: 'export', type: 'string', required: false, nullable: true, defaultValue: false, description: 'instructions parameter for discharge', index: 6 },
  { name: 'instructionsMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum instructions filter for discharge', index: 6 },
  { name: 'instructionsMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum instructions filter for discharge', index: 6 },
  { name: 'followUpDate', mode: 'input', type: 'string', required: false, nullable: true, defaultValue: null, description: 'followUpDate parameter for discharge', index: 7 },
  { name: 'followUpDate', mode: 'filter', type: 'string', required: false, nullable: true, defaultValue: null, description: 'followUpDate parameter for discharge', index: 7 },
  { name: 'followUpDate', mode: 'sort', type: 'string', required: false, nullable: true, defaultValue: false, description: 'followUpDate parameter for discharge', index: 7 },
  { name: 'followUpDate', mode: 'search', type: 'string', required: false, nullable: true, defaultValue: null, description: 'followUpDate parameter for discharge', index: 7 },
  { name: 'followUpDate', mode: 'export', type: 'string', required: false, nullable: true, defaultValue: false, description: 'followUpDate parameter for discharge', index: 7 },
  { name: 'followUpDateMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum followUpDate filter for discharge', index: 7 },
  { name: 'followUpDateMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum followUpDate filter for discharge', index: 7 },
  { name: 'medications', mode: 'input', type: 'string', required: false, nullable: true, defaultValue: null, description: 'medications parameter for discharge', index: 8 },
  { name: 'medications', mode: 'filter', type: 'string', required: false, nullable: true, defaultValue: null, description: 'medications parameter for discharge', index: 8 },
  { name: 'medications', mode: 'sort', type: 'string', required: false, nullable: true, defaultValue: false, description: 'medications parameter for discharge', index: 8 },
  { name: 'medications', mode: 'search', type: 'string', required: false, nullable: true, defaultValue: null, description: 'medications parameter for discharge', index: 8 },
  { name: 'medications', mode: 'export', type: 'string', required: false, nullable: true, defaultValue: false, description: 'medications parameter for discharge', index: 8 },
  { name: 'medicationsMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum medications filter for discharge', index: 8 },
  { name: 'medicationsMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum medications filter for discharge', index: 8 },
  { name: 'doctorId', mode: 'input', type: 'string', required: false, nullable: true, defaultValue: null, description: 'doctorId parameter for discharge', index: 9 },
  { name: 'doctorId', mode: 'filter', type: 'string', required: false, nullable: true, defaultValue: null, description: 'doctorId parameter for discharge', index: 9 },
  { name: 'doctorId', mode: 'sort', type: 'string', required: false, nullable: true, defaultValue: false, description: 'doctorId parameter for discharge', index: 9 },
  { name: 'doctorId', mode: 'search', type: 'string', required: false, nullable: true, defaultValue: null, description: 'doctorId parameter for discharge', index: 9 },
  { name: 'doctorId', mode: 'export', type: 'string', required: false, nullable: true, defaultValue: false, description: 'doctorId parameter for discharge', index: 9 },
  { name: 'doctorIdMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum doctorId filter for discharge', index: 9 },
  { name: 'doctorIdMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum doctorId filter for discharge', index: 9 },
  { name: 'status', mode: 'input', type: 'string', required: false, nullable: true, defaultValue: null, description: 'status parameter for discharge', index: 10 },
  { name: 'status', mode: 'filter', type: 'string', required: false, nullable: true, defaultValue: null, description: 'status parameter for discharge', index: 10 },
  { name: 'status', mode: 'sort', type: 'string', required: false, nullable: true, defaultValue: false, description: 'status parameter for discharge', index: 10 },
  { name: 'status', mode: 'search', type: 'string', required: false, nullable: true, defaultValue: null, description: 'status parameter for discharge', index: 10 },
  { name: 'status', mode: 'export', type: 'string', required: false, nullable: true, defaultValue: false, description: 'status parameter for discharge', index: 10 },
  { name: 'statusMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum status filter for discharge', index: 10 },
  { name: 'statusMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum status filter for discharge', index: 10 },
];

function get(name){return parameters.find(p=>p.name===name)||null;}
function list(mode){return mode?parameters.filter(p=>p.mode===mode):[...parameters];}
function required(){return parameters.filter(p=>p.required);}
function validateParameter(name,value){const p=get(name);if(!p)return {ok:false,code:'UNKNOWN_PARAMETER'};if(value===null&&p.nullable)return {ok:true};if(p.type==='number'&&typeof value!=='number')return {ok:false,code:'TYPE_ERROR'};if(p.type==='boolean'&&typeof value!=='boolean')return {ok:false,code:'TYPE_ERROR'};if(p.type==='string'&&typeof value!=='string')return {ok:false,code:'TYPE_ERROR'};return {ok:true};}
function validateObject(input={}){const errors=[];for(const p of required()){if(input[p.name]===undefined||input[p.name]===null||input[p.name]==='')errors.push({field:p.name,code:'REQUIRED'});}for(const [k,v] of Object.entries(input)){const result=validateParameter(k,v);if(!result.ok)errors.push({field:k,code:result.code});}return errors;}
function defaults(){return Object.fromEntries(parameters.filter(p=>p.defaultValue!==null).map(p=>[p.name,p.defaultValue]));}
function describe(){return {entity,parameterCount:parameters.length,parameters};}
module.exports={entity,parameters,get,list,required,validateParameter,validateObject,defaults,describe};
