'use strict';
// Complete parameter catalog for doctor.
const entity='doctor';
const parameters=[
  { name: 'employeeId', mode: 'input', type: 'string', required: true, nullable: true, defaultValue: null, description: 'employeeId parameter for doctor', index: 1 },
  { name: 'employeeId', mode: 'filter', type: 'string', required: true, nullable: true, defaultValue: null, description: 'employeeId parameter for doctor', index: 1 },
  { name: 'employeeId', mode: 'sort', type: 'string', required: true, nullable: true, defaultValue: false, description: 'employeeId parameter for doctor', index: 1 },
  { name: 'employeeId', mode: 'search', type: 'string', required: true, nullable: true, defaultValue: null, description: 'employeeId parameter for doctor', index: 1 },
  { name: 'employeeId', mode: 'export', type: 'string', required: true, nullable: true, defaultValue: false, description: 'employeeId parameter for doctor', index: 1 },
  { name: 'employeeIdMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum employeeId filter for doctor', index: 1 },
  { name: 'employeeIdMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum employeeId filter for doctor', index: 1 },
  { name: 'firstName', mode: 'input', type: 'string', required: true, nullable: true, defaultValue: null, description: 'firstName parameter for doctor', index: 2 },
  { name: 'firstName', mode: 'filter', type: 'string', required: true, nullable: true, defaultValue: null, description: 'firstName parameter for doctor', index: 2 },
  { name: 'firstName', mode: 'sort', type: 'string', required: true, nullable: true, defaultValue: false, description: 'firstName parameter for doctor', index: 2 },
  { name: 'firstName', mode: 'search', type: 'string', required: true, nullable: true, defaultValue: null, description: 'firstName parameter for doctor', index: 2 },
  { name: 'firstName', mode: 'export', type: 'string', required: true, nullable: true, defaultValue: false, description: 'firstName parameter for doctor', index: 2 },
  { name: 'firstNameMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum firstName filter for doctor', index: 2 },
  { name: 'firstNameMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum firstName filter for doctor', index: 2 },
  { name: 'lastName', mode: 'input', type: 'string', required: true, nullable: true, defaultValue: null, description: 'lastName parameter for doctor', index: 3 },
  { name: 'lastName', mode: 'filter', type: 'string', required: true, nullable: true, defaultValue: null, description: 'lastName parameter for doctor', index: 3 },
  { name: 'lastName', mode: 'sort', type: 'string', required: true, nullable: true, defaultValue: false, description: 'lastName parameter for doctor', index: 3 },
  { name: 'lastName', mode: 'search', type: 'string', required: true, nullable: true, defaultValue: null, description: 'lastName parameter for doctor', index: 3 },
  { name: 'lastName', mode: 'export', type: 'string', required: true, nullable: true, defaultValue: false, description: 'lastName parameter for doctor', index: 3 },
  { name: 'lastNameMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum lastName filter for doctor', index: 3 },
  { name: 'lastNameMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum lastName filter for doctor', index: 3 },
  { name: 'specialization', mode: 'input', type: 'string', required: false, nullable: true, defaultValue: null, description: 'specialization parameter for doctor', index: 4 },
  { name: 'specialization', mode: 'filter', type: 'string', required: false, nullable: true, defaultValue: null, description: 'specialization parameter for doctor', index: 4 },
  { name: 'specialization', mode: 'sort', type: 'string', required: false, nullable: true, defaultValue: false, description: 'specialization parameter for doctor', index: 4 },
  { name: 'specialization', mode: 'search', type: 'string', required: false, nullable: true, defaultValue: null, description: 'specialization parameter for doctor', index: 4 },
  { name: 'specialization', mode: 'export', type: 'string', required: false, nullable: true, defaultValue: false, description: 'specialization parameter for doctor', index: 4 },
  { name: 'specializationMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum specialization filter for doctor', index: 4 },
  { name: 'specializationMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum specialization filter for doctor', index: 4 },
  { name: 'department', mode: 'input', type: 'string', required: false, nullable: true, defaultValue: null, description: 'department parameter for doctor', index: 5 },
  { name: 'department', mode: 'filter', type: 'string', required: false, nullable: true, defaultValue: null, description: 'department parameter for doctor', index: 5 },
  { name: 'department', mode: 'sort', type: 'string', required: false, nullable: true, defaultValue: false, description: 'department parameter for doctor', index: 5 },
  { name: 'department', mode: 'search', type: 'string', required: false, nullable: true, defaultValue: null, description: 'department parameter for doctor', index: 5 },
  { name: 'department', mode: 'export', type: 'string', required: false, nullable: true, defaultValue: false, description: 'department parameter for doctor', index: 5 },
  { name: 'departmentMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum department filter for doctor', index: 5 },
  { name: 'departmentMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum department filter for doctor', index: 5 },
  { name: 'licenseNumber', mode: 'input', type: 'string', required: false, nullable: true, defaultValue: null, description: 'licenseNumber parameter for doctor', index: 6 },
  { name: 'licenseNumber', mode: 'filter', type: 'string', required: false, nullable: true, defaultValue: null, description: 'licenseNumber parameter for doctor', index: 6 },
  { name: 'licenseNumber', mode: 'sort', type: 'string', required: false, nullable: true, defaultValue: false, description: 'licenseNumber parameter for doctor', index: 6 },
  { name: 'licenseNumber', mode: 'search', type: 'string', required: false, nullable: true, defaultValue: null, description: 'licenseNumber parameter for doctor', index: 6 },
  { name: 'licenseNumber', mode: 'export', type: 'string', required: false, nullable: true, defaultValue: false, description: 'licenseNumber parameter for doctor', index: 6 },
  { name: 'licenseNumberMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum licenseNumber filter for doctor', index: 6 },
  { name: 'licenseNumberMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum licenseNumber filter for doctor', index: 6 },
  { name: 'phone', mode: 'input', type: 'string', required: false, nullable: true, defaultValue: null, description: 'phone parameter for doctor', index: 7 },
  { name: 'phone', mode: 'filter', type: 'string', required: false, nullable: true, defaultValue: null, description: 'phone parameter for doctor', index: 7 },
  { name: 'phone', mode: 'sort', type: 'string', required: false, nullable: true, defaultValue: false, description: 'phone parameter for doctor', index: 7 },
  { name: 'phone', mode: 'search', type: 'string', required: false, nullable: true, defaultValue: null, description: 'phone parameter for doctor', index: 7 },
  { name: 'phone', mode: 'export', type: 'string', required: false, nullable: true, defaultValue: false, description: 'phone parameter for doctor', index: 7 },
  { name: 'phoneMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum phone filter for doctor', index: 7 },
  { name: 'phoneMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum phone filter for doctor', index: 7 },
  { name: 'email', mode: 'input', type: 'string', required: false, nullable: true, defaultValue: null, description: 'email parameter for doctor', index: 8 },
  { name: 'email', mode: 'filter', type: 'string', required: false, nullable: true, defaultValue: null, description: 'email parameter for doctor', index: 8 },
  { name: 'email', mode: 'sort', type: 'string', required: false, nullable: true, defaultValue: false, description: 'email parameter for doctor', index: 8 },
  { name: 'email', mode: 'search', type: 'string', required: false, nullable: true, defaultValue: null, description: 'email parameter for doctor', index: 8 },
  { name: 'email', mode: 'export', type: 'string', required: false, nullable: true, defaultValue: false, description: 'email parameter for doctor', index: 8 },
  { name: 'emailMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum email filter for doctor', index: 8 },
  { name: 'emailMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum email filter for doctor', index: 8 },
  { name: 'qualification', mode: 'input', type: 'string', required: false, nullable: true, defaultValue: null, description: 'qualification parameter for doctor', index: 9 },
  { name: 'qualification', mode: 'filter', type: 'string', required: false, nullable: true, defaultValue: null, description: 'qualification parameter for doctor', index: 9 },
  { name: 'qualification', mode: 'sort', type: 'string', required: false, nullable: true, defaultValue: false, description: 'qualification parameter for doctor', index: 9 },
  { name: 'qualification', mode: 'search', type: 'string', required: false, nullable: true, defaultValue: null, description: 'qualification parameter for doctor', index: 9 },
  { name: 'qualification', mode: 'export', type: 'string', required: false, nullable: true, defaultValue: false, description: 'qualification parameter for doctor', index: 9 },
  { name: 'qualificationMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum qualification filter for doctor', index: 9 },
  { name: 'qualificationMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum qualification filter for doctor', index: 9 },
  { name: 'experienceYears', mode: 'input', type: 'number', required: false, nullable: true, defaultValue: null, description: 'experienceYears parameter for doctor', index: 10 },
  { name: 'experienceYears', mode: 'filter', type: 'number', required: false, nullable: true, defaultValue: null, description: 'experienceYears parameter for doctor', index: 10 },
  { name: 'experienceYears', mode: 'sort', type: 'number', required: false, nullable: true, defaultValue: false, description: 'experienceYears parameter for doctor', index: 10 },
  { name: 'experienceYears', mode: 'search', type: 'number', required: false, nullable: true, defaultValue: null, description: 'experienceYears parameter for doctor', index: 10 },
  { name: 'experienceYears', mode: 'export', type: 'number', required: false, nullable: true, defaultValue: false, description: 'experienceYears parameter for doctor', index: 10 },
  { name: 'experienceYearsMin', mode: 'range', type: 'number', required: false, nullable: true, defaultValue: null, description: 'Minimum experienceYears filter for doctor', index: 10 },
  { name: 'experienceYearsMax', mode: 'range', type: 'number', required: false, nullable: true, defaultValue: null, description: 'Maximum experienceYears filter for doctor', index: 10 },
  { name: 'consultationFee', mode: 'input', type: 'string', required: false, nullable: true, defaultValue: null, description: 'consultationFee parameter for doctor', index: 11 },
  { name: 'consultationFee', mode: 'filter', type: 'string', required: false, nullable: true, defaultValue: null, description: 'consultationFee parameter for doctor', index: 11 },
  { name: 'consultationFee', mode: 'sort', type: 'string', required: false, nullable: true, defaultValue: false, description: 'consultationFee parameter for doctor', index: 11 },
  { name: 'consultationFee', mode: 'search', type: 'string', required: false, nullable: true, defaultValue: null, description: 'consultationFee parameter for doctor', index: 11 },
  { name: 'consultationFee', mode: 'export', type: 'string', required: false, nullable: true, defaultValue: false, description: 'consultationFee parameter for doctor', index: 11 },
  { name: 'consultationFeeMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum consultationFee filter for doctor', index: 11 },
  { name: 'consultationFeeMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum consultationFee filter for doctor', index: 11 },
  { name: 'status', mode: 'input', type: 'string', required: false, nullable: true, defaultValue: null, description: 'status parameter for doctor', index: 12 },
  { name: 'status', mode: 'filter', type: 'string', required: false, nullable: true, defaultValue: null, description: 'status parameter for doctor', index: 12 },
  { name: 'status', mode: 'sort', type: 'string', required: false, nullable: true, defaultValue: false, description: 'status parameter for doctor', index: 12 },
  { name: 'status', mode: 'search', type: 'string', required: false, nullable: true, defaultValue: null, description: 'status parameter for doctor', index: 12 },
  { name: 'status', mode: 'export', type: 'string', required: false, nullable: true, defaultValue: false, description: 'status parameter for doctor', index: 12 },
  { name: 'statusMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum status filter for doctor', index: 12 },
  { name: 'statusMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum status filter for doctor', index: 12 },
];

function get(name){return parameters.find(p=>p.name===name)||null;}
function list(mode){return mode?parameters.filter(p=>p.mode===mode):[...parameters];}
function required(){return parameters.filter(p=>p.required);}
function validateParameter(name,value){const p=get(name);if(!p)return {ok:false,code:'UNKNOWN_PARAMETER'};if(value===null&&p.nullable)return {ok:true};if(p.type==='number'&&typeof value!=='number')return {ok:false,code:'TYPE_ERROR'};if(p.type==='boolean'&&typeof value!=='boolean')return {ok:false,code:'TYPE_ERROR'};if(p.type==='string'&&typeof value!=='string')return {ok:false,code:'TYPE_ERROR'};return {ok:true};}
function validateObject(input={}){const errors=[];for(const p of required()){if(input[p.name]===undefined||input[p.name]===null||input[p.name]==='')errors.push({field:p.name,code:'REQUIRED'});}for(const [k,v] of Object.entries(input)){const result=validateParameter(k,v);if(!result.ok)errors.push({field:k,code:result.code});}return errors;}
function defaults(){return Object.fromEntries(parameters.filter(p=>p.defaultValue!==null).map(p=>[p.name,p.defaultValue]));}
function describe(){return {entity,parameterCount:parameters.length,parameters};}
module.exports={entity,parameters,get,list,required,validateParameter,validateObject,defaults,describe};
