'use strict';
// Complete parameter catalog for insuranceClaim.
const entity='insuranceClaim';
const parameters=[
  { name: 'patientId', mode: 'input', type: 'string', required: true, nullable: true, defaultValue: null, description: 'patientId parameter for insuranceClaim', index: 1 },
  { name: 'patientId', mode: 'filter', type: 'string', required: true, nullable: true, defaultValue: null, description: 'patientId parameter for insuranceClaim', index: 1 },
  { name: 'patientId', mode: 'sort', type: 'string', required: true, nullable: true, defaultValue: false, description: 'patientId parameter for insuranceClaim', index: 1 },
  { name: 'patientId', mode: 'search', type: 'string', required: true, nullable: true, defaultValue: null, description: 'patientId parameter for insuranceClaim', index: 1 },
  { name: 'patientId', mode: 'export', type: 'string', required: true, nullable: true, defaultValue: false, description: 'patientId parameter for insuranceClaim', index: 1 },
  { name: 'patientIdMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum patientId filter for insuranceClaim', index: 1 },
  { name: 'patientIdMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum patientId filter for insuranceClaim', index: 1 },
  { name: 'invoiceId', mode: 'input', type: 'string', required: true, nullable: true, defaultValue: null, description: 'invoiceId parameter for insuranceClaim', index: 2 },
  { name: 'invoiceId', mode: 'filter', type: 'string', required: true, nullable: true, defaultValue: null, description: 'invoiceId parameter for insuranceClaim', index: 2 },
  { name: 'invoiceId', mode: 'sort', type: 'string', required: true, nullable: true, defaultValue: false, description: 'invoiceId parameter for insuranceClaim', index: 2 },
  { name: 'invoiceId', mode: 'search', type: 'string', required: true, nullable: true, defaultValue: null, description: 'invoiceId parameter for insuranceClaim', index: 2 },
  { name: 'invoiceId', mode: 'export', type: 'string', required: true, nullable: true, defaultValue: false, description: 'invoiceId parameter for insuranceClaim', index: 2 },
  { name: 'invoiceIdMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum invoiceId filter for insuranceClaim', index: 2 },
  { name: 'invoiceIdMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum invoiceId filter for insuranceClaim', index: 2 },
  { name: 'provider', mode: 'input', type: 'string', required: true, nullable: true, defaultValue: null, description: 'provider parameter for insuranceClaim', index: 3 },
  { name: 'provider', mode: 'filter', type: 'string', required: true, nullable: true, defaultValue: null, description: 'provider parameter for insuranceClaim', index: 3 },
  { name: 'provider', mode: 'sort', type: 'string', required: true, nullable: true, defaultValue: false, description: 'provider parameter for insuranceClaim', index: 3 },
  { name: 'provider', mode: 'search', type: 'string', required: true, nullable: true, defaultValue: null, description: 'provider parameter for insuranceClaim', index: 3 },
  { name: 'provider', mode: 'export', type: 'string', required: true, nullable: true, defaultValue: false, description: 'provider parameter for insuranceClaim', index: 3 },
  { name: 'providerMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum provider filter for insuranceClaim', index: 3 },
  { name: 'providerMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum provider filter for insuranceClaim', index: 3 },
  { name: 'policyNumber', mode: 'input', type: 'string', required: false, nullable: true, defaultValue: null, description: 'policyNumber parameter for insuranceClaim', index: 4 },
  { name: 'policyNumber', mode: 'filter', type: 'string', required: false, nullable: true, defaultValue: null, description: 'policyNumber parameter for insuranceClaim', index: 4 },
  { name: 'policyNumber', mode: 'sort', type: 'string', required: false, nullable: true, defaultValue: false, description: 'policyNumber parameter for insuranceClaim', index: 4 },
  { name: 'policyNumber', mode: 'search', type: 'string', required: false, nullable: true, defaultValue: null, description: 'policyNumber parameter for insuranceClaim', index: 4 },
  { name: 'policyNumber', mode: 'export', type: 'string', required: false, nullable: true, defaultValue: false, description: 'policyNumber parameter for insuranceClaim', index: 4 },
  { name: 'policyNumberMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum policyNumber filter for insuranceClaim', index: 4 },
  { name: 'policyNumberMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum policyNumber filter for insuranceClaim', index: 4 },
  { name: 'claimNumber', mode: 'input', type: 'string', required: false, nullable: true, defaultValue: null, description: 'claimNumber parameter for insuranceClaim', index: 5 },
  { name: 'claimNumber', mode: 'filter', type: 'string', required: false, nullable: true, defaultValue: null, description: 'claimNumber parameter for insuranceClaim', index: 5 },
  { name: 'claimNumber', mode: 'sort', type: 'string', required: false, nullable: true, defaultValue: false, description: 'claimNumber parameter for insuranceClaim', index: 5 },
  { name: 'claimNumber', mode: 'search', type: 'string', required: false, nullable: true, defaultValue: null, description: 'claimNumber parameter for insuranceClaim', index: 5 },
  { name: 'claimNumber', mode: 'export', type: 'string', required: false, nullable: true, defaultValue: false, description: 'claimNumber parameter for insuranceClaim', index: 5 },
  { name: 'claimNumberMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum claimNumber filter for insuranceClaim', index: 5 },
  { name: 'claimNumberMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum claimNumber filter for insuranceClaim', index: 5 },
  { name: 'submittedAt', mode: 'input', type: 'string', required: false, nullable: true, defaultValue: null, description: 'submittedAt parameter for insuranceClaim', index: 6 },
  { name: 'submittedAt', mode: 'filter', type: 'string', required: false, nullable: true, defaultValue: null, description: 'submittedAt parameter for insuranceClaim', index: 6 },
  { name: 'submittedAt', mode: 'sort', type: 'string', required: false, nullable: true, defaultValue: false, description: 'submittedAt parameter for insuranceClaim', index: 6 },
  { name: 'submittedAt', mode: 'search', type: 'string', required: false, nullable: true, defaultValue: null, description: 'submittedAt parameter for insuranceClaim', index: 6 },
  { name: 'submittedAt', mode: 'export', type: 'string', required: false, nullable: true, defaultValue: false, description: 'submittedAt parameter for insuranceClaim', index: 6 },
  { name: 'submittedAtMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum submittedAt filter for insuranceClaim', index: 6 },
  { name: 'submittedAtMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum submittedAt filter for insuranceClaim', index: 6 },
  { name: 'approvedAt', mode: 'input', type: 'string', required: false, nullable: true, defaultValue: null, description: 'approvedAt parameter for insuranceClaim', index: 7 },
  { name: 'approvedAt', mode: 'filter', type: 'string', required: false, nullable: true, defaultValue: null, description: 'approvedAt parameter for insuranceClaim', index: 7 },
  { name: 'approvedAt', mode: 'sort', type: 'string', required: false, nullable: true, defaultValue: false, description: 'approvedAt parameter for insuranceClaim', index: 7 },
  { name: 'approvedAt', mode: 'search', type: 'string', required: false, nullable: true, defaultValue: null, description: 'approvedAt parameter for insuranceClaim', index: 7 },
  { name: 'approvedAt', mode: 'export', type: 'string', required: false, nullable: true, defaultValue: false, description: 'approvedAt parameter for insuranceClaim', index: 7 },
  { name: 'approvedAtMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum approvedAt filter for insuranceClaim', index: 7 },
  { name: 'approvedAtMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum approvedAt filter for insuranceClaim', index: 7 },
  { name: 'claimedAmount', mode: 'input', type: 'number', required: false, nullable: true, defaultValue: null, description: 'claimedAmount parameter for insuranceClaim', index: 8 },
  { name: 'claimedAmount', mode: 'filter', type: 'number', required: false, nullable: true, defaultValue: null, description: 'claimedAmount parameter for insuranceClaim', index: 8 },
  { name: 'claimedAmount', mode: 'sort', type: 'number', required: false, nullable: true, defaultValue: false, description: 'claimedAmount parameter for insuranceClaim', index: 8 },
  { name: 'claimedAmount', mode: 'search', type: 'number', required: false, nullable: true, defaultValue: null, description: 'claimedAmount parameter for insuranceClaim', index: 8 },
  { name: 'claimedAmount', mode: 'export', type: 'number', required: false, nullable: true, defaultValue: false, description: 'claimedAmount parameter for insuranceClaim', index: 8 },
  { name: 'claimedAmountMin', mode: 'range', type: 'number', required: false, nullable: true, defaultValue: null, description: 'Minimum claimedAmount filter for insuranceClaim', index: 8 },
  { name: 'claimedAmountMax', mode: 'range', type: 'number', required: false, nullable: true, defaultValue: null, description: 'Maximum claimedAmount filter for insuranceClaim', index: 8 },
  { name: 'approvedAmount', mode: 'input', type: 'number', required: false, nullable: true, defaultValue: null, description: 'approvedAmount parameter for insuranceClaim', index: 9 },
  { name: 'approvedAmount', mode: 'filter', type: 'number', required: false, nullable: true, defaultValue: null, description: 'approvedAmount parameter for insuranceClaim', index: 9 },
  { name: 'approvedAmount', mode: 'sort', type: 'number', required: false, nullable: true, defaultValue: false, description: 'approvedAmount parameter for insuranceClaim', index: 9 },
  { name: 'approvedAmount', mode: 'search', type: 'number', required: false, nullable: true, defaultValue: null, description: 'approvedAmount parameter for insuranceClaim', index: 9 },
  { name: 'approvedAmount', mode: 'export', type: 'number', required: false, nullable: true, defaultValue: false, description: 'approvedAmount parameter for insuranceClaim', index: 9 },
  { name: 'approvedAmountMin', mode: 'range', type: 'number', required: false, nullable: true, defaultValue: null, description: 'Minimum approvedAmount filter for insuranceClaim', index: 9 },
  { name: 'approvedAmountMax', mode: 'range', type: 'number', required: false, nullable: true, defaultValue: null, description: 'Maximum approvedAmount filter for insuranceClaim', index: 9 },
  { name: 'status', mode: 'input', type: 'string', required: false, nullable: true, defaultValue: null, description: 'status parameter for insuranceClaim', index: 10 },
  { name: 'status', mode: 'filter', type: 'string', required: false, nullable: true, defaultValue: null, description: 'status parameter for insuranceClaim', index: 10 },
  { name: 'status', mode: 'sort', type: 'string', required: false, nullable: true, defaultValue: false, description: 'status parameter for insuranceClaim', index: 10 },
  { name: 'status', mode: 'search', type: 'string', required: false, nullable: true, defaultValue: null, description: 'status parameter for insuranceClaim', index: 10 },
  { name: 'status', mode: 'export', type: 'string', required: false, nullable: true, defaultValue: false, description: 'status parameter for insuranceClaim', index: 10 },
  { name: 'statusMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum status filter for insuranceClaim', index: 10 },
  { name: 'statusMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum status filter for insuranceClaim', index: 10 },
  { name: 'remarks', mode: 'input', type: 'string', required: false, nullable: true, defaultValue: null, description: 'remarks parameter for insuranceClaim', index: 11 },
  { name: 'remarks', mode: 'filter', type: 'string', required: false, nullable: true, defaultValue: null, description: 'remarks parameter for insuranceClaim', index: 11 },
  { name: 'remarks', mode: 'sort', type: 'string', required: false, nullable: true, defaultValue: false, description: 'remarks parameter for insuranceClaim', index: 11 },
  { name: 'remarks', mode: 'search', type: 'string', required: false, nullable: true, defaultValue: null, description: 'remarks parameter for insuranceClaim', index: 11 },
  { name: 'remarks', mode: 'export', type: 'string', required: false, nullable: true, defaultValue: false, description: 'remarks parameter for insuranceClaim', index: 11 },
  { name: 'remarksMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum remarks filter for insuranceClaim', index: 11 },
  { name: 'remarksMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum remarks filter for insuranceClaim', index: 11 },
];

function get(name){return parameters.find(p=>p.name===name)||null;}
function list(mode){return mode?parameters.filter(p=>p.mode===mode):[...parameters];}
function required(){return parameters.filter(p=>p.required);}
function validateParameter(name,value){const p=get(name);if(!p)return {ok:false,code:'UNKNOWN_PARAMETER'};if(value===null&&p.nullable)return {ok:true};if(p.type==='number'&&typeof value!=='number')return {ok:false,code:'TYPE_ERROR'};if(p.type==='boolean'&&typeof value!=='boolean')return {ok:false,code:'TYPE_ERROR'};if(p.type==='string'&&typeof value!=='string')return {ok:false,code:'TYPE_ERROR'};return {ok:true};}
function validateObject(input={}){const errors=[];for(const p of required()){if(input[p.name]===undefined||input[p.name]===null||input[p.name]==='')errors.push({field:p.name,code:'REQUIRED'});}for(const [k,v] of Object.entries(input)){const result=validateParameter(k,v);if(!result.ok)errors.push({field:k,code:result.code});}return errors;}
function defaults(){return Object.fromEntries(parameters.filter(p=>p.defaultValue!==null).map(p=>[p.name,p.defaultValue]));}
function describe(){return {entity,parameterCount:parameters.length,parameters};}
module.exports={entity,parameters,get,list,required,validateParameter,validateObject,defaults,describe};
