'use strict';
// Complete parameter catalog for invoice.
const entity='invoice';
const parameters=[
  { name: 'patientId', mode: 'input', type: 'string', required: true, nullable: true, defaultValue: null, description: 'patientId parameter for invoice', index: 1 },
  { name: 'patientId', mode: 'filter', type: 'string', required: true, nullable: true, defaultValue: null, description: 'patientId parameter for invoice', index: 1 },
  { name: 'patientId', mode: 'sort', type: 'string', required: true, nullable: true, defaultValue: false, description: 'patientId parameter for invoice', index: 1 },
  { name: 'patientId', mode: 'search', type: 'string', required: true, nullable: true, defaultValue: null, description: 'patientId parameter for invoice', index: 1 },
  { name: 'patientId', mode: 'export', type: 'string', required: true, nullable: true, defaultValue: false, description: 'patientId parameter for invoice', index: 1 },
  { name: 'patientIdMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum patientId filter for invoice', index: 1 },
  { name: 'patientIdMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum patientId filter for invoice', index: 1 },
  { name: 'visitId', mode: 'input', type: 'string', required: true, nullable: true, defaultValue: null, description: 'visitId parameter for invoice', index: 2 },
  { name: 'visitId', mode: 'filter', type: 'string', required: true, nullable: true, defaultValue: null, description: 'visitId parameter for invoice', index: 2 },
  { name: 'visitId', mode: 'sort', type: 'string', required: true, nullable: true, defaultValue: false, description: 'visitId parameter for invoice', index: 2 },
  { name: 'visitId', mode: 'search', type: 'string', required: true, nullable: true, defaultValue: null, description: 'visitId parameter for invoice', index: 2 },
  { name: 'visitId', mode: 'export', type: 'string', required: true, nullable: true, defaultValue: false, description: 'visitId parameter for invoice', index: 2 },
  { name: 'visitIdMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum visitId filter for invoice', index: 2 },
  { name: 'visitIdMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum visitId filter for invoice', index: 2 },
  { name: 'invoiceNumber', mode: 'input', type: 'string', required: true, nullable: true, defaultValue: null, description: 'invoiceNumber parameter for invoice', index: 3 },
  { name: 'invoiceNumber', mode: 'filter', type: 'string', required: true, nullable: true, defaultValue: null, description: 'invoiceNumber parameter for invoice', index: 3 },
  { name: 'invoiceNumber', mode: 'sort', type: 'string', required: true, nullable: true, defaultValue: false, description: 'invoiceNumber parameter for invoice', index: 3 },
  { name: 'invoiceNumber', mode: 'search', type: 'string', required: true, nullable: true, defaultValue: null, description: 'invoiceNumber parameter for invoice', index: 3 },
  { name: 'invoiceNumber', mode: 'export', type: 'string', required: true, nullable: true, defaultValue: false, description: 'invoiceNumber parameter for invoice', index: 3 },
  { name: 'invoiceNumberMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum invoiceNumber filter for invoice', index: 3 },
  { name: 'invoiceNumberMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum invoiceNumber filter for invoice', index: 3 },
  { name: 'subtotal', mode: 'input', type: 'number', required: false, nullable: true, defaultValue: null, description: 'subtotal parameter for invoice', index: 4 },
  { name: 'subtotal', mode: 'filter', type: 'number', required: false, nullable: true, defaultValue: null, description: 'subtotal parameter for invoice', index: 4 },
  { name: 'subtotal', mode: 'sort', type: 'number', required: false, nullable: true, defaultValue: false, description: 'subtotal parameter for invoice', index: 4 },
  { name: 'subtotal', mode: 'search', type: 'number', required: false, nullable: true, defaultValue: null, description: 'subtotal parameter for invoice', index: 4 },
  { name: 'subtotal', mode: 'export', type: 'number', required: false, nullable: true, defaultValue: false, description: 'subtotal parameter for invoice', index: 4 },
  { name: 'subtotalMin', mode: 'range', type: 'number', required: false, nullable: true, defaultValue: null, description: 'Minimum subtotal filter for invoice', index: 4 },
  { name: 'subtotalMax', mode: 'range', type: 'number', required: false, nullable: true, defaultValue: null, description: 'Maximum subtotal filter for invoice', index: 4 },
  { name: 'discount', mode: 'input', type: 'number', required: false, nullable: true, defaultValue: null, description: 'discount parameter for invoice', index: 5 },
  { name: 'discount', mode: 'filter', type: 'number', required: false, nullable: true, defaultValue: null, description: 'discount parameter for invoice', index: 5 },
  { name: 'discount', mode: 'sort', type: 'number', required: false, nullable: true, defaultValue: false, description: 'discount parameter for invoice', index: 5 },
  { name: 'discount', mode: 'search', type: 'number', required: false, nullable: true, defaultValue: null, description: 'discount parameter for invoice', index: 5 },
  { name: 'discount', mode: 'export', type: 'number', required: false, nullable: true, defaultValue: false, description: 'discount parameter for invoice', index: 5 },
  { name: 'discountMin', mode: 'range', type: 'number', required: false, nullable: true, defaultValue: null, description: 'Minimum discount filter for invoice', index: 5 },
  { name: 'discountMax', mode: 'range', type: 'number', required: false, nullable: true, defaultValue: null, description: 'Maximum discount filter for invoice', index: 5 },
  { name: 'tax', mode: 'input', type: 'number', required: false, nullable: true, defaultValue: null, description: 'tax parameter for invoice', index: 6 },
  { name: 'tax', mode: 'filter', type: 'number', required: false, nullable: true, defaultValue: null, description: 'tax parameter for invoice', index: 6 },
  { name: 'tax', mode: 'sort', type: 'number', required: false, nullable: true, defaultValue: false, description: 'tax parameter for invoice', index: 6 },
  { name: 'tax', mode: 'search', type: 'number', required: false, nullable: true, defaultValue: null, description: 'tax parameter for invoice', index: 6 },
  { name: 'tax', mode: 'export', type: 'number', required: false, nullable: true, defaultValue: false, description: 'tax parameter for invoice', index: 6 },
  { name: 'taxMin', mode: 'range', type: 'number', required: false, nullable: true, defaultValue: null, description: 'Minimum tax filter for invoice', index: 6 },
  { name: 'taxMax', mode: 'range', type: 'number', required: false, nullable: true, defaultValue: null, description: 'Maximum tax filter for invoice', index: 6 },
  { name: 'total', mode: 'input', type: 'number', required: false, nullable: true, defaultValue: null, description: 'total parameter for invoice', index: 7 },
  { name: 'total', mode: 'filter', type: 'number', required: false, nullable: true, defaultValue: null, description: 'total parameter for invoice', index: 7 },
  { name: 'total', mode: 'sort', type: 'number', required: false, nullable: true, defaultValue: false, description: 'total parameter for invoice', index: 7 },
  { name: 'total', mode: 'search', type: 'number', required: false, nullable: true, defaultValue: null, description: 'total parameter for invoice', index: 7 },
  { name: 'total', mode: 'export', type: 'number', required: false, nullable: true, defaultValue: false, description: 'total parameter for invoice', index: 7 },
  { name: 'totalMin', mode: 'range', type: 'number', required: false, nullable: true, defaultValue: null, description: 'Minimum total filter for invoice', index: 7 },
  { name: 'totalMax', mode: 'range', type: 'number', required: false, nullable: true, defaultValue: null, description: 'Maximum total filter for invoice', index: 7 },
  { name: 'currency', mode: 'input', type: 'string', required: false, nullable: true, defaultValue: null, description: 'currency parameter for invoice', index: 8 },
  { name: 'currency', mode: 'filter', type: 'string', required: false, nullable: true, defaultValue: null, description: 'currency parameter for invoice', index: 8 },
  { name: 'currency', mode: 'sort', type: 'string', required: false, nullable: true, defaultValue: false, description: 'currency parameter for invoice', index: 8 },
  { name: 'currency', mode: 'search', type: 'string', required: false, nullable: true, defaultValue: null, description: 'currency parameter for invoice', index: 8 },
  { name: 'currency', mode: 'export', type: 'string', required: false, nullable: true, defaultValue: false, description: 'currency parameter for invoice', index: 8 },
  { name: 'currencyMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum currency filter for invoice', index: 8 },
  { name: 'currencyMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum currency filter for invoice', index: 8 },
  { name: 'dueDate', mode: 'input', type: 'string', required: false, nullable: true, defaultValue: null, description: 'dueDate parameter for invoice', index: 9 },
  { name: 'dueDate', mode: 'filter', type: 'string', required: false, nullable: true, defaultValue: null, description: 'dueDate parameter for invoice', index: 9 },
  { name: 'dueDate', mode: 'sort', type: 'string', required: false, nullable: true, defaultValue: false, description: 'dueDate parameter for invoice', index: 9 },
  { name: 'dueDate', mode: 'search', type: 'string', required: false, nullable: true, defaultValue: null, description: 'dueDate parameter for invoice', index: 9 },
  { name: 'dueDate', mode: 'export', type: 'string', required: false, nullable: true, defaultValue: false, description: 'dueDate parameter for invoice', index: 9 },
  { name: 'dueDateMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum dueDate filter for invoice', index: 9 },
  { name: 'dueDateMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum dueDate filter for invoice', index: 9 },
  { name: 'status', mode: 'input', type: 'string', required: false, nullable: true, defaultValue: null, description: 'status parameter for invoice', index: 10 },
  { name: 'status', mode: 'filter', type: 'string', required: false, nullable: true, defaultValue: null, description: 'status parameter for invoice', index: 10 },
  { name: 'status', mode: 'sort', type: 'string', required: false, nullable: true, defaultValue: false, description: 'status parameter for invoice', index: 10 },
  { name: 'status', mode: 'search', type: 'string', required: false, nullable: true, defaultValue: null, description: 'status parameter for invoice', index: 10 },
  { name: 'status', mode: 'export', type: 'string', required: false, nullable: true, defaultValue: false, description: 'status parameter for invoice', index: 10 },
  { name: 'statusMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum status filter for invoice', index: 10 },
  { name: 'statusMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum status filter for invoice', index: 10 },
  { name: 'createdBy', mode: 'input', type: 'string', required: false, nullable: true, defaultValue: null, description: 'createdBy parameter for invoice', index: 11 },
  { name: 'createdBy', mode: 'filter', type: 'string', required: false, nullable: true, defaultValue: null, description: 'createdBy parameter for invoice', index: 11 },
  { name: 'createdBy', mode: 'sort', type: 'string', required: false, nullable: true, defaultValue: false, description: 'createdBy parameter for invoice', index: 11 },
  { name: 'createdBy', mode: 'search', type: 'string', required: false, nullable: true, defaultValue: null, description: 'createdBy parameter for invoice', index: 11 },
  { name: 'createdBy', mode: 'export', type: 'string', required: false, nullable: true, defaultValue: false, description: 'createdBy parameter for invoice', index: 11 },
  { name: 'createdByMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum createdBy filter for invoice', index: 11 },
  { name: 'createdByMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum createdBy filter for invoice', index: 11 },
];

function get(name){return parameters.find(p=>p.name===name)||null;}
function list(mode){return mode?parameters.filter(p=>p.mode===mode):[...parameters];}
function required(){return parameters.filter(p=>p.required);}
function validateParameter(name,value){const p=get(name);if(!p)return {ok:false,code:'UNKNOWN_PARAMETER'};if(value===null&&p.nullable)return {ok:true};if(p.type==='number'&&typeof value!=='number')return {ok:false,code:'TYPE_ERROR'};if(p.type==='boolean'&&typeof value!=='boolean')return {ok:false,code:'TYPE_ERROR'};if(p.type==='string'&&typeof value!=='string')return {ok:false,code:'TYPE_ERROR'};return {ok:true};}
function validateObject(input={}){const errors=[];for(const p of required()){if(input[p.name]===undefined||input[p.name]===null||input[p.name]==='')errors.push({field:p.name,code:'REQUIRED'});}for(const [k,v] of Object.entries(input)){const result=validateParameter(k,v);if(!result.ok)errors.push({field:k,code:result.code});}return errors;}
function defaults(){return Object.fromEntries(parameters.filter(p=>p.defaultValue!==null).map(p=>[p.name,p.defaultValue]));}
function describe(){return {entity,parameterCount:parameters.length,parameters};}
module.exports={entity,parameters,get,list,required,validateParameter,validateObject,defaults,describe};
