'use strict';
// Complete parameter catalog for labOrder.
const entity='labOrder';
const parameters=[
  { name: 'patientId', mode: 'input', type: 'string', required: true, nullable: true, defaultValue: null, description: 'patientId parameter for labOrder', index: 1 },
  { name: 'patientId', mode: 'filter', type: 'string', required: true, nullable: true, defaultValue: null, description: 'patientId parameter for labOrder', index: 1 },
  { name: 'patientId', mode: 'sort', type: 'string', required: true, nullable: true, defaultValue: false, description: 'patientId parameter for labOrder', index: 1 },
  { name: 'patientId', mode: 'search', type: 'string', required: true, nullable: true, defaultValue: null, description: 'patientId parameter for labOrder', index: 1 },
  { name: 'patientId', mode: 'export', type: 'string', required: true, nullable: true, defaultValue: false, description: 'patientId parameter for labOrder', index: 1 },
  { name: 'patientIdMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum patientId filter for labOrder', index: 1 },
  { name: 'patientIdMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum patientId filter for labOrder', index: 1 },
  { name: 'doctorId', mode: 'input', type: 'string', required: true, nullable: true, defaultValue: null, description: 'doctorId parameter for labOrder', index: 2 },
  { name: 'doctorId', mode: 'filter', type: 'string', required: true, nullable: true, defaultValue: null, description: 'doctorId parameter for labOrder', index: 2 },
  { name: 'doctorId', mode: 'sort', type: 'string', required: true, nullable: true, defaultValue: false, description: 'doctorId parameter for labOrder', index: 2 },
  { name: 'doctorId', mode: 'search', type: 'string', required: true, nullable: true, defaultValue: null, description: 'doctorId parameter for labOrder', index: 2 },
  { name: 'doctorId', mode: 'export', type: 'string', required: true, nullable: true, defaultValue: false, description: 'doctorId parameter for labOrder', index: 2 },
  { name: 'doctorIdMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum doctorId filter for labOrder', index: 2 },
  { name: 'doctorIdMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum doctorId filter for labOrder', index: 2 },
  { name: 'visitId', mode: 'input', type: 'string', required: true, nullable: true, defaultValue: null, description: 'visitId parameter for labOrder', index: 3 },
  { name: 'visitId', mode: 'filter', type: 'string', required: true, nullable: true, defaultValue: null, description: 'visitId parameter for labOrder', index: 3 },
  { name: 'visitId', mode: 'sort', type: 'string', required: true, nullable: true, defaultValue: false, description: 'visitId parameter for labOrder', index: 3 },
  { name: 'visitId', mode: 'search', type: 'string', required: true, nullable: true, defaultValue: null, description: 'visitId parameter for labOrder', index: 3 },
  { name: 'visitId', mode: 'export', type: 'string', required: true, nullable: true, defaultValue: false, description: 'visitId parameter for labOrder', index: 3 },
  { name: 'visitIdMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum visitId filter for labOrder', index: 3 },
  { name: 'visitIdMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum visitId filter for labOrder', index: 3 },
  { name: 'testCode', mode: 'input', type: 'string', required: false, nullable: true, defaultValue: null, description: 'testCode parameter for labOrder', index: 4 },
  { name: 'testCode', mode: 'filter', type: 'string', required: false, nullable: true, defaultValue: null, description: 'testCode parameter for labOrder', index: 4 },
  { name: 'testCode', mode: 'sort', type: 'string', required: false, nullable: true, defaultValue: false, description: 'testCode parameter for labOrder', index: 4 },
  { name: 'testCode', mode: 'search', type: 'string', required: false, nullable: true, defaultValue: null, description: 'testCode parameter for labOrder', index: 4 },
  { name: 'testCode', mode: 'export', type: 'string', required: false, nullable: true, defaultValue: false, description: 'testCode parameter for labOrder', index: 4 },
  { name: 'testCodeMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum testCode filter for labOrder', index: 4 },
  { name: 'testCodeMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum testCode filter for labOrder', index: 4 },
  { name: 'testName', mode: 'input', type: 'string', required: false, nullable: true, defaultValue: null, description: 'testName parameter for labOrder', index: 5 },
  { name: 'testName', mode: 'filter', type: 'string', required: false, nullable: true, defaultValue: null, description: 'testName parameter for labOrder', index: 5 },
  { name: 'testName', mode: 'sort', type: 'string', required: false, nullable: true, defaultValue: false, description: 'testName parameter for labOrder', index: 5 },
  { name: 'testName', mode: 'search', type: 'string', required: false, nullable: true, defaultValue: null, description: 'testName parameter for labOrder', index: 5 },
  { name: 'testName', mode: 'export', type: 'string', required: false, nullable: true, defaultValue: false, description: 'testName parameter for labOrder', index: 5 },
  { name: 'testNameMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum testName filter for labOrder', index: 5 },
  { name: 'testNameMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum testName filter for labOrder', index: 5 },
  { name: 'priority', mode: 'input', type: 'string', required: false, nullable: true, defaultValue: null, description: 'priority parameter for labOrder', index: 6 },
  { name: 'priority', mode: 'filter', type: 'string', required: false, nullable: true, defaultValue: null, description: 'priority parameter for labOrder', index: 6 },
  { name: 'priority', mode: 'sort', type: 'string', required: false, nullable: true, defaultValue: false, description: 'priority parameter for labOrder', index: 6 },
  { name: 'priority', mode: 'search', type: 'string', required: false, nullable: true, defaultValue: null, description: 'priority parameter for labOrder', index: 6 },
  { name: 'priority', mode: 'export', type: 'string', required: false, nullable: true, defaultValue: false, description: 'priority parameter for labOrder', index: 6 },
  { name: 'priorityMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum priority filter for labOrder', index: 6 },
  { name: 'priorityMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum priority filter for labOrder', index: 6 },
  { name: 'specimen', mode: 'input', type: 'string', required: false, nullable: true, defaultValue: null, description: 'specimen parameter for labOrder', index: 7 },
  { name: 'specimen', mode: 'filter', type: 'string', required: false, nullable: true, defaultValue: null, description: 'specimen parameter for labOrder', index: 7 },
  { name: 'specimen', mode: 'sort', type: 'string', required: false, nullable: true, defaultValue: false, description: 'specimen parameter for labOrder', index: 7 },
  { name: 'specimen', mode: 'search', type: 'string', required: false, nullable: true, defaultValue: null, description: 'specimen parameter for labOrder', index: 7 },
  { name: 'specimen', mode: 'export', type: 'string', required: false, nullable: true, defaultValue: false, description: 'specimen parameter for labOrder', index: 7 },
  { name: 'specimenMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum specimen filter for labOrder', index: 7 },
  { name: 'specimenMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum specimen filter for labOrder', index: 7 },
  { name: 'orderedAt', mode: 'input', type: 'string', required: false, nullable: true, defaultValue: null, description: 'orderedAt parameter for labOrder', index: 8 },
  { name: 'orderedAt', mode: 'filter', type: 'string', required: false, nullable: true, defaultValue: null, description: 'orderedAt parameter for labOrder', index: 8 },
  { name: 'orderedAt', mode: 'sort', type: 'string', required: false, nullable: true, defaultValue: false, description: 'orderedAt parameter for labOrder', index: 8 },
  { name: 'orderedAt', mode: 'search', type: 'string', required: false, nullable: true, defaultValue: null, description: 'orderedAt parameter for labOrder', index: 8 },
  { name: 'orderedAt', mode: 'export', type: 'string', required: false, nullable: true, defaultValue: false, description: 'orderedAt parameter for labOrder', index: 8 },
  { name: 'orderedAtMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum orderedAt filter for labOrder', index: 8 },
  { name: 'orderedAtMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum orderedAt filter for labOrder', index: 8 },
  { name: 'status', mode: 'input', type: 'string', required: false, nullable: true, defaultValue: null, description: 'status parameter for labOrder', index: 9 },
  { name: 'status', mode: 'filter', type: 'string', required: false, nullable: true, defaultValue: null, description: 'status parameter for labOrder', index: 9 },
  { name: 'status', mode: 'sort', type: 'string', required: false, nullable: true, defaultValue: false, description: 'status parameter for labOrder', index: 9 },
  { name: 'status', mode: 'search', type: 'string', required: false, nullable: true, defaultValue: null, description: 'status parameter for labOrder', index: 9 },
  { name: 'status', mode: 'export', type: 'string', required: false, nullable: true, defaultValue: false, description: 'status parameter for labOrder', index: 9 },
  { name: 'statusMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum status filter for labOrder', index: 9 },
  { name: 'statusMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum status filter for labOrder', index: 9 },
  { name: 'clinicalNotes', mode: 'input', type: 'string', required: false, nullable: true, defaultValue: null, description: 'clinicalNotes parameter for labOrder', index: 10 },
  { name: 'clinicalNotes', mode: 'filter', type: 'string', required: false, nullable: true, defaultValue: null, description: 'clinicalNotes parameter for labOrder', index: 10 },
  { name: 'clinicalNotes', mode: 'sort', type: 'string', required: false, nullable: true, defaultValue: false, description: 'clinicalNotes parameter for labOrder', index: 10 },
  { name: 'clinicalNotes', mode: 'search', type: 'string', required: false, nullable: true, defaultValue: null, description: 'clinicalNotes parameter for labOrder', index: 10 },
  { name: 'clinicalNotes', mode: 'export', type: 'string', required: false, nullable: true, defaultValue: false, description: 'clinicalNotes parameter for labOrder', index: 10 },
  { name: 'clinicalNotesMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum clinicalNotes filter for labOrder', index: 10 },
  { name: 'clinicalNotesMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum clinicalNotes filter for labOrder', index: 10 },
];

function get(name){return parameters.find(p=>p.name===name)||null;}
function list(mode){return mode?parameters.filter(p=>p.mode===mode):[...parameters];}
function required(){return parameters.filter(p=>p.required);}
function validateParameter(name,value){const p=get(name);if(!p)return {ok:false,code:'UNKNOWN_PARAMETER'};if(value===null&&p.nullable)return {ok:true};if(p.type==='number'&&typeof value!=='number')return {ok:false,code:'TYPE_ERROR'};if(p.type==='boolean'&&typeof value!=='boolean')return {ok:false,code:'TYPE_ERROR'};if(p.type==='string'&&typeof value!=='string')return {ok:false,code:'TYPE_ERROR'};return {ok:true};}
function validateObject(input={}){const errors=[];for(const p of required()){if(input[p.name]===undefined||input[p.name]===null||input[p.name]==='')errors.push({field:p.name,code:'REQUIRED'});}for(const [k,v] of Object.entries(input)){const result=validateParameter(k,v);if(!result.ok)errors.push({field:k,code:result.code});}return errors;}
function defaults(){return Object.fromEntries(parameters.filter(p=>p.defaultValue!==null).map(p=>[p.name,p.defaultValue]));}
function describe(){return {entity,parameterCount:parameters.length,parameters};}
module.exports={entity,parameters,get,list,required,validateParameter,validateObject,defaults,describe};
