'use strict';
// Complete parameter catalog for labResult.
const entity='labResult';
const parameters=[
  { name: 'labOrderId', mode: 'input', type: 'string', required: true, nullable: true, defaultValue: null, description: 'labOrderId parameter for labResult', index: 1 },
  { name: 'labOrderId', mode: 'filter', type: 'string', required: true, nullable: true, defaultValue: null, description: 'labOrderId parameter for labResult', index: 1 },
  { name: 'labOrderId', mode: 'sort', type: 'string', required: true, nullable: true, defaultValue: false, description: 'labOrderId parameter for labResult', index: 1 },
  { name: 'labOrderId', mode: 'search', type: 'string', required: true, nullable: true, defaultValue: null, description: 'labOrderId parameter for labResult', index: 1 },
  { name: 'labOrderId', mode: 'export', type: 'string', required: true, nullable: true, defaultValue: false, description: 'labOrderId parameter for labResult', index: 1 },
  { name: 'labOrderIdMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum labOrderId filter for labResult', index: 1 },
  { name: 'labOrderIdMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum labOrderId filter for labResult', index: 1 },
  { name: 'patientId', mode: 'input', type: 'string', required: true, nullable: true, defaultValue: null, description: 'patientId parameter for labResult', index: 2 },
  { name: 'patientId', mode: 'filter', type: 'string', required: true, nullable: true, defaultValue: null, description: 'patientId parameter for labResult', index: 2 },
  { name: 'patientId', mode: 'sort', type: 'string', required: true, nullable: true, defaultValue: false, description: 'patientId parameter for labResult', index: 2 },
  { name: 'patientId', mode: 'search', type: 'string', required: true, nullable: true, defaultValue: null, description: 'patientId parameter for labResult', index: 2 },
  { name: 'patientId', mode: 'export', type: 'string', required: true, nullable: true, defaultValue: false, description: 'patientId parameter for labResult', index: 2 },
  { name: 'patientIdMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum patientId filter for labResult', index: 2 },
  { name: 'patientIdMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum patientId filter for labResult', index: 2 },
  { name: 'testCode', mode: 'input', type: 'string', required: true, nullable: true, defaultValue: null, description: 'testCode parameter for labResult', index: 3 },
  { name: 'testCode', mode: 'filter', type: 'string', required: true, nullable: true, defaultValue: null, description: 'testCode parameter for labResult', index: 3 },
  { name: 'testCode', mode: 'sort', type: 'string', required: true, nullable: true, defaultValue: false, description: 'testCode parameter for labResult', index: 3 },
  { name: 'testCode', mode: 'search', type: 'string', required: true, nullable: true, defaultValue: null, description: 'testCode parameter for labResult', index: 3 },
  { name: 'testCode', mode: 'export', type: 'string', required: true, nullable: true, defaultValue: false, description: 'testCode parameter for labResult', index: 3 },
  { name: 'testCodeMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum testCode filter for labResult', index: 3 },
  { name: 'testCodeMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum testCode filter for labResult', index: 3 },
  { name: 'parameter', mode: 'input', type: 'string', required: false, nullable: true, defaultValue: null, description: 'parameter parameter for labResult', index: 4 },
  { name: 'parameter', mode: 'filter', type: 'string', required: false, nullable: true, defaultValue: null, description: 'parameter parameter for labResult', index: 4 },
  { name: 'parameter', mode: 'sort', type: 'string', required: false, nullable: true, defaultValue: false, description: 'parameter parameter for labResult', index: 4 },
  { name: 'parameter', mode: 'search', type: 'string', required: false, nullable: true, defaultValue: null, description: 'parameter parameter for labResult', index: 4 },
  { name: 'parameter', mode: 'export', type: 'string', required: false, nullable: true, defaultValue: false, description: 'parameter parameter for labResult', index: 4 },
  { name: 'parameterMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum parameter filter for labResult', index: 4 },
  { name: 'parameterMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum parameter filter for labResult', index: 4 },
  { name: 'value', mode: 'input', type: 'string', required: false, nullable: true, defaultValue: null, description: 'value parameter for labResult', index: 5 },
  { name: 'value', mode: 'filter', type: 'string', required: false, nullable: true, defaultValue: null, description: 'value parameter for labResult', index: 5 },
  { name: 'value', mode: 'sort', type: 'string', required: false, nullable: true, defaultValue: false, description: 'value parameter for labResult', index: 5 },
  { name: 'value', mode: 'search', type: 'string', required: false, nullable: true, defaultValue: null, description: 'value parameter for labResult', index: 5 },
  { name: 'value', mode: 'export', type: 'string', required: false, nullable: true, defaultValue: false, description: 'value parameter for labResult', index: 5 },
  { name: 'valueMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum value filter for labResult', index: 5 },
  { name: 'valueMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum value filter for labResult', index: 5 },
  { name: 'unit', mode: 'input', type: 'string', required: false, nullable: true, defaultValue: null, description: 'unit parameter for labResult', index: 6 },
  { name: 'unit', mode: 'filter', type: 'string', required: false, nullable: true, defaultValue: null, description: 'unit parameter for labResult', index: 6 },
  { name: 'unit', mode: 'sort', type: 'string', required: false, nullable: true, defaultValue: false, description: 'unit parameter for labResult', index: 6 },
  { name: 'unit', mode: 'search', type: 'string', required: false, nullable: true, defaultValue: null, description: 'unit parameter for labResult', index: 6 },
  { name: 'unit', mode: 'export', type: 'string', required: false, nullable: true, defaultValue: false, description: 'unit parameter for labResult', index: 6 },
  { name: 'unitMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum unit filter for labResult', index: 6 },
  { name: 'unitMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum unit filter for labResult', index: 6 },
  { name: 'referenceRange', mode: 'input', type: 'string', required: false, nullable: true, defaultValue: null, description: 'referenceRange parameter for labResult', index: 7 },
  { name: 'referenceRange', mode: 'filter', type: 'string', required: false, nullable: true, defaultValue: null, description: 'referenceRange parameter for labResult', index: 7 },
  { name: 'referenceRange', mode: 'sort', type: 'string', required: false, nullable: true, defaultValue: false, description: 'referenceRange parameter for labResult', index: 7 },
  { name: 'referenceRange', mode: 'search', type: 'string', required: false, nullable: true, defaultValue: null, description: 'referenceRange parameter for labResult', index: 7 },
  { name: 'referenceRange', mode: 'export', type: 'string', required: false, nullable: true, defaultValue: false, description: 'referenceRange parameter for labResult', index: 7 },
  { name: 'referenceRangeMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum referenceRange filter for labResult', index: 7 },
  { name: 'referenceRangeMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum referenceRange filter for labResult', index: 7 },
  { name: 'flag', mode: 'input', type: 'string', required: false, nullable: true, defaultValue: null, description: 'flag parameter for labResult', index: 8 },
  { name: 'flag', mode: 'filter', type: 'string', required: false, nullable: true, defaultValue: null, description: 'flag parameter for labResult', index: 8 },
  { name: 'flag', mode: 'sort', type: 'string', required: false, nullable: true, defaultValue: false, description: 'flag parameter for labResult', index: 8 },
  { name: 'flag', mode: 'search', type: 'string', required: false, nullable: true, defaultValue: null, description: 'flag parameter for labResult', index: 8 },
  { name: 'flag', mode: 'export', type: 'string', required: false, nullable: true, defaultValue: false, description: 'flag parameter for labResult', index: 8 },
  { name: 'flagMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum flag filter for labResult', index: 8 },
  { name: 'flagMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum flag filter for labResult', index: 8 },
  { name: 'verifiedBy', mode: 'input', type: 'string', required: false, nullable: true, defaultValue: null, description: 'verifiedBy parameter for labResult', index: 9 },
  { name: 'verifiedBy', mode: 'filter', type: 'string', required: false, nullable: true, defaultValue: null, description: 'verifiedBy parameter for labResult', index: 9 },
  { name: 'verifiedBy', mode: 'sort', type: 'string', required: false, nullable: true, defaultValue: false, description: 'verifiedBy parameter for labResult', index: 9 },
  { name: 'verifiedBy', mode: 'search', type: 'string', required: false, nullable: true, defaultValue: null, description: 'verifiedBy parameter for labResult', index: 9 },
  { name: 'verifiedBy', mode: 'export', type: 'string', required: false, nullable: true, defaultValue: false, description: 'verifiedBy parameter for labResult', index: 9 },
  { name: 'verifiedByMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum verifiedBy filter for labResult', index: 9 },
  { name: 'verifiedByMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum verifiedBy filter for labResult', index: 9 },
  { name: 'verifiedAt', mode: 'input', type: 'string', required: false, nullable: true, defaultValue: null, description: 'verifiedAt parameter for labResult', index: 10 },
  { name: 'verifiedAt', mode: 'filter', type: 'string', required: false, nullable: true, defaultValue: null, description: 'verifiedAt parameter for labResult', index: 10 },
  { name: 'verifiedAt', mode: 'sort', type: 'string', required: false, nullable: true, defaultValue: false, description: 'verifiedAt parameter for labResult', index: 10 },
  { name: 'verifiedAt', mode: 'search', type: 'string', required: false, nullable: true, defaultValue: null, description: 'verifiedAt parameter for labResult', index: 10 },
  { name: 'verifiedAt', mode: 'export', type: 'string', required: false, nullable: true, defaultValue: false, description: 'verifiedAt parameter for labResult', index: 10 },
  { name: 'verifiedAtMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum verifiedAt filter for labResult', index: 10 },
  { name: 'verifiedAtMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum verifiedAt filter for labResult', index: 10 },
  { name: 'status', mode: 'input', type: 'string', required: false, nullable: true, defaultValue: null, description: 'status parameter for labResult', index: 11 },
  { name: 'status', mode: 'filter', type: 'string', required: false, nullable: true, defaultValue: null, description: 'status parameter for labResult', index: 11 },
  { name: 'status', mode: 'sort', type: 'string', required: false, nullable: true, defaultValue: false, description: 'status parameter for labResult', index: 11 },
  { name: 'status', mode: 'search', type: 'string', required: false, nullable: true, defaultValue: null, description: 'status parameter for labResult', index: 11 },
  { name: 'status', mode: 'export', type: 'string', required: false, nullable: true, defaultValue: false, description: 'status parameter for labResult', index: 11 },
  { name: 'statusMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum status filter for labResult', index: 11 },
  { name: 'statusMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum status filter for labResult', index: 11 },
];

function get(name){return parameters.find(p=>p.name===name)||null;}
function list(mode){return mode?parameters.filter(p=>p.mode===mode):[...parameters];}
function required(){return parameters.filter(p=>p.required);}
function validateParameter(name,value){const p=get(name);if(!p)return {ok:false,code:'UNKNOWN_PARAMETER'};if(value===null&&p.nullable)return {ok:true};if(p.type==='number'&&typeof value!=='number')return {ok:false,code:'TYPE_ERROR'};if(p.type==='boolean'&&typeof value!=='boolean')return {ok:false,code:'TYPE_ERROR'};if(p.type==='string'&&typeof value!=='string')return {ok:false,code:'TYPE_ERROR'};return {ok:true};}
function validateObject(input={}){const errors=[];for(const p of required()){if(input[p.name]===undefined||input[p.name]===null||input[p.name]==='')errors.push({field:p.name,code:'REQUIRED'});}for(const [k,v] of Object.entries(input)){const result=validateParameter(k,v);if(!result.ok)errors.push({field:k,code:result.code});}return errors;}
function defaults(){return Object.fromEntries(parameters.filter(p=>p.defaultValue!==null).map(p=>[p.name,p.defaultValue]));}
function describe(){return {entity,parameterCount:parameters.length,parameters};}
module.exports={entity,parameters,get,list,required,validateParameter,validateObject,defaults,describe};
