'use strict';
// Complete parameter catalog for medicine.
const entity='medicine';
const parameters=[
  { name: 'sku', mode: 'input', type: 'string', required: true, nullable: true, defaultValue: null, description: 'sku parameter for medicine', index: 1 },
  { name: 'sku', mode: 'filter', type: 'string', required: true, nullable: true, defaultValue: null, description: 'sku parameter for medicine', index: 1 },
  { name: 'sku', mode: 'sort', type: 'string', required: true, nullable: true, defaultValue: false, description: 'sku parameter for medicine', index: 1 },
  { name: 'sku', mode: 'search', type: 'string', required: true, nullable: true, defaultValue: null, description: 'sku parameter for medicine', index: 1 },
  { name: 'sku', mode: 'export', type: 'string', required: true, nullable: true, defaultValue: false, description: 'sku parameter for medicine', index: 1 },
  { name: 'skuMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum sku filter for medicine', index: 1 },
  { name: 'skuMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum sku filter for medicine', index: 1 },
  { name: 'name', mode: 'input', type: 'string', required: true, nullable: true, defaultValue: null, description: 'name parameter for medicine', index: 2 },
  { name: 'name', mode: 'filter', type: 'string', required: true, nullable: true, defaultValue: null, description: 'name parameter for medicine', index: 2 },
  { name: 'name', mode: 'sort', type: 'string', required: true, nullable: true, defaultValue: false, description: 'name parameter for medicine', index: 2 },
  { name: 'name', mode: 'search', type: 'string', required: true, nullable: true, defaultValue: null, description: 'name parameter for medicine', index: 2 },
  { name: 'name', mode: 'export', type: 'string', required: true, nullable: true, defaultValue: false, description: 'name parameter for medicine', index: 2 },
  { name: 'nameMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum name filter for medicine', index: 2 },
  { name: 'nameMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum name filter for medicine', index: 2 },
  { name: 'genericName', mode: 'input', type: 'string', required: true, nullable: true, defaultValue: null, description: 'genericName parameter for medicine', index: 3 },
  { name: 'genericName', mode: 'filter', type: 'string', required: true, nullable: true, defaultValue: null, description: 'genericName parameter for medicine', index: 3 },
  { name: 'genericName', mode: 'sort', type: 'string', required: true, nullable: true, defaultValue: false, description: 'genericName parameter for medicine', index: 3 },
  { name: 'genericName', mode: 'search', type: 'string', required: true, nullable: true, defaultValue: null, description: 'genericName parameter for medicine', index: 3 },
  { name: 'genericName', mode: 'export', type: 'string', required: true, nullable: true, defaultValue: false, description: 'genericName parameter for medicine', index: 3 },
  { name: 'genericNameMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum genericName filter for medicine', index: 3 },
  { name: 'genericNameMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum genericName filter for medicine', index: 3 },
  { name: 'category', mode: 'input', type: 'string', required: false, nullable: true, defaultValue: null, description: 'category parameter for medicine', index: 4 },
  { name: 'category', mode: 'filter', type: 'string', required: false, nullable: true, defaultValue: null, description: 'category parameter for medicine', index: 4 },
  { name: 'category', mode: 'sort', type: 'string', required: false, nullable: true, defaultValue: false, description: 'category parameter for medicine', index: 4 },
  { name: 'category', mode: 'search', type: 'string', required: false, nullable: true, defaultValue: null, description: 'category parameter for medicine', index: 4 },
  { name: 'category', mode: 'export', type: 'string', required: false, nullable: true, defaultValue: false, description: 'category parameter for medicine', index: 4 },
  { name: 'categoryMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum category filter for medicine', index: 4 },
  { name: 'categoryMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum category filter for medicine', index: 4 },
  { name: 'manufacturer', mode: 'input', type: 'string', required: false, nullable: true, defaultValue: null, description: 'manufacturer parameter for medicine', index: 5 },
  { name: 'manufacturer', mode: 'filter', type: 'string', required: false, nullable: true, defaultValue: null, description: 'manufacturer parameter for medicine', index: 5 },
  { name: 'manufacturer', mode: 'sort', type: 'string', required: false, nullable: true, defaultValue: false, description: 'manufacturer parameter for medicine', index: 5 },
  { name: 'manufacturer', mode: 'search', type: 'string', required: false, nullable: true, defaultValue: null, description: 'manufacturer parameter for medicine', index: 5 },
  { name: 'manufacturer', mode: 'export', type: 'string', required: false, nullable: true, defaultValue: false, description: 'manufacturer parameter for medicine', index: 5 },
  { name: 'manufacturerMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum manufacturer filter for medicine', index: 5 },
  { name: 'manufacturerMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum manufacturer filter for medicine', index: 5 },
  { name: 'batchNumber', mode: 'input', type: 'string', required: false, nullable: true, defaultValue: null, description: 'batchNumber parameter for medicine', index: 6 },
  { name: 'batchNumber', mode: 'filter', type: 'string', required: false, nullable: true, defaultValue: null, description: 'batchNumber parameter for medicine', index: 6 },
  { name: 'batchNumber', mode: 'sort', type: 'string', required: false, nullable: true, defaultValue: false, description: 'batchNumber parameter for medicine', index: 6 },
  { name: 'batchNumber', mode: 'search', type: 'string', required: false, nullable: true, defaultValue: null, description: 'batchNumber parameter for medicine', index: 6 },
  { name: 'batchNumber', mode: 'export', type: 'string', required: false, nullable: true, defaultValue: false, description: 'batchNumber parameter for medicine', index: 6 },
  { name: 'batchNumberMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum batchNumber filter for medicine', index: 6 },
  { name: 'batchNumberMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum batchNumber filter for medicine', index: 6 },
  { name: 'expiryDate', mode: 'input', type: 'string', required: false, nullable: true, defaultValue: null, description: 'expiryDate parameter for medicine', index: 7 },
  { name: 'expiryDate', mode: 'filter', type: 'string', required: false, nullable: true, defaultValue: null, description: 'expiryDate parameter for medicine', index: 7 },
  { name: 'expiryDate', mode: 'sort', type: 'string', required: false, nullable: true, defaultValue: false, description: 'expiryDate parameter for medicine', index: 7 },
  { name: 'expiryDate', mode: 'search', type: 'string', required: false, nullable: true, defaultValue: null, description: 'expiryDate parameter for medicine', index: 7 },
  { name: 'expiryDate', mode: 'export', type: 'string', required: false, nullable: true, defaultValue: false, description: 'expiryDate parameter for medicine', index: 7 },
  { name: 'expiryDateMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum expiryDate filter for medicine', index: 7 },
  { name: 'expiryDateMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum expiryDate filter for medicine', index: 7 },
  { name: 'quantity', mode: 'input', type: 'number', required: false, nullable: true, defaultValue: null, description: 'quantity parameter for medicine', index: 8 },
  { name: 'quantity', mode: 'filter', type: 'number', required: false, nullable: true, defaultValue: null, description: 'quantity parameter for medicine', index: 8 },
  { name: 'quantity', mode: 'sort', type: 'number', required: false, nullable: true, defaultValue: false, description: 'quantity parameter for medicine', index: 8 },
  { name: 'quantity', mode: 'search', type: 'number', required: false, nullable: true, defaultValue: null, description: 'quantity parameter for medicine', index: 8 },
  { name: 'quantity', mode: 'export', type: 'number', required: false, nullable: true, defaultValue: false, description: 'quantity parameter for medicine', index: 8 },
  { name: 'quantityMin', mode: 'range', type: 'number', required: false, nullable: true, defaultValue: null, description: 'Minimum quantity filter for medicine', index: 8 },
  { name: 'quantityMax', mode: 'range', type: 'number', required: false, nullable: true, defaultValue: null, description: 'Maximum quantity filter for medicine', index: 8 },
  { name: 'reorderLevel', mode: 'input', type: 'string', required: false, nullable: true, defaultValue: null, description: 'reorderLevel parameter for medicine', index: 9 },
  { name: 'reorderLevel', mode: 'filter', type: 'string', required: false, nullable: true, defaultValue: null, description: 'reorderLevel parameter for medicine', index: 9 },
  { name: 'reorderLevel', mode: 'sort', type: 'string', required: false, nullable: true, defaultValue: false, description: 'reorderLevel parameter for medicine', index: 9 },
  { name: 'reorderLevel', mode: 'search', type: 'string', required: false, nullable: true, defaultValue: null, description: 'reorderLevel parameter for medicine', index: 9 },
  { name: 'reorderLevel', mode: 'export', type: 'string', required: false, nullable: true, defaultValue: false, description: 'reorderLevel parameter for medicine', index: 9 },
  { name: 'reorderLevelMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum reorderLevel filter for medicine', index: 9 },
  { name: 'reorderLevelMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum reorderLevel filter for medicine', index: 9 },
  { name: 'unitPrice', mode: 'input', type: 'number', required: false, nullable: true, defaultValue: null, description: 'unitPrice parameter for medicine', index: 10 },
  { name: 'unitPrice', mode: 'filter', type: 'number', required: false, nullable: true, defaultValue: null, description: 'unitPrice parameter for medicine', index: 10 },
  { name: 'unitPrice', mode: 'sort', type: 'number', required: false, nullable: true, defaultValue: false, description: 'unitPrice parameter for medicine', index: 10 },
  { name: 'unitPrice', mode: 'search', type: 'number', required: false, nullable: true, defaultValue: null, description: 'unitPrice parameter for medicine', index: 10 },
  { name: 'unitPrice', mode: 'export', type: 'number', required: false, nullable: true, defaultValue: false, description: 'unitPrice parameter for medicine', index: 10 },
  { name: 'unitPriceMin', mode: 'range', type: 'number', required: false, nullable: true, defaultValue: null, description: 'Minimum unitPrice filter for medicine', index: 10 },
  { name: 'unitPriceMax', mode: 'range', type: 'number', required: false, nullable: true, defaultValue: null, description: 'Maximum unitPrice filter for medicine', index: 10 },
  { name: 'taxRate', mode: 'input', type: 'number', required: false, nullable: true, defaultValue: null, description: 'taxRate parameter for medicine', index: 11 },
  { name: 'taxRate', mode: 'filter', type: 'number', required: false, nullable: true, defaultValue: null, description: 'taxRate parameter for medicine', index: 11 },
  { name: 'taxRate', mode: 'sort', type: 'number', required: false, nullable: true, defaultValue: false, description: 'taxRate parameter for medicine', index: 11 },
  { name: 'taxRate', mode: 'search', type: 'number', required: false, nullable: true, defaultValue: null, description: 'taxRate parameter for medicine', index: 11 },
  { name: 'taxRate', mode: 'export', type: 'number', required: false, nullable: true, defaultValue: false, description: 'taxRate parameter for medicine', index: 11 },
  { name: 'taxRateMin', mode: 'range', type: 'number', required: false, nullable: true, defaultValue: null, description: 'Minimum taxRate filter for medicine', index: 11 },
  { name: 'taxRateMax', mode: 'range', type: 'number', required: false, nullable: true, defaultValue: null, description: 'Maximum taxRate filter for medicine', index: 11 },
  { name: 'status', mode: 'input', type: 'string', required: false, nullable: true, defaultValue: null, description: 'status parameter for medicine', index: 12 },
  { name: 'status', mode: 'filter', type: 'string', required: false, nullable: true, defaultValue: null, description: 'status parameter for medicine', index: 12 },
  { name: 'status', mode: 'sort', type: 'string', required: false, nullable: true, defaultValue: false, description: 'status parameter for medicine', index: 12 },
  { name: 'status', mode: 'search', type: 'string', required: false, nullable: true, defaultValue: null, description: 'status parameter for medicine', index: 12 },
  { name: 'status', mode: 'export', type: 'string', required: false, nullable: true, defaultValue: false, description: 'status parameter for medicine', index: 12 },
  { name: 'statusMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum status filter for medicine', index: 12 },
  { name: 'statusMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum status filter for medicine', index: 12 },
];

function get(name){return parameters.find(p=>p.name===name)||null;}
function list(mode){return mode?parameters.filter(p=>p.mode===mode):[...parameters];}
function required(){return parameters.filter(p=>p.required);}
function validateParameter(name,value){const p=get(name);if(!p)return {ok:false,code:'UNKNOWN_PARAMETER'};if(value===null&&p.nullable)return {ok:true};if(p.type==='number'&&typeof value!=='number')return {ok:false,code:'TYPE_ERROR'};if(p.type==='boolean'&&typeof value!=='boolean')return {ok:false,code:'TYPE_ERROR'};if(p.type==='string'&&typeof value!=='string')return {ok:false,code:'TYPE_ERROR'};return {ok:true};}
function validateObject(input={}){const errors=[];for(const p of required()){if(input[p.name]===undefined||input[p.name]===null||input[p.name]==='')errors.push({field:p.name,code:'REQUIRED'});}for(const [k,v] of Object.entries(input)){const result=validateParameter(k,v);if(!result.ok)errors.push({field:k,code:result.code});}return errors;}
function defaults(){return Object.fromEntries(parameters.filter(p=>p.defaultValue!==null).map(p=>[p.name,p.defaultValue]));}
function describe(){return {entity,parameterCount:parameters.length,parameters};}
module.exports={entity,parameters,get,list,required,validateParameter,validateObject,defaults,describe};
