'use strict';
// Complete parameter catalog for notification.
const entity='notification';
const parameters=[
  { name: 'recipientId', mode: 'input', type: 'string', required: true, nullable: true, defaultValue: null, description: 'recipientId parameter for notification', index: 1 },
  { name: 'recipientId', mode: 'filter', type: 'string', required: true, nullable: true, defaultValue: null, description: 'recipientId parameter for notification', index: 1 },
  { name: 'recipientId', mode: 'sort', type: 'string', required: true, nullable: true, defaultValue: false, description: 'recipientId parameter for notification', index: 1 },
  { name: 'recipientId', mode: 'search', type: 'string', required: true, nullable: true, defaultValue: null, description: 'recipientId parameter for notification', index: 1 },
  { name: 'recipientId', mode: 'export', type: 'string', required: true, nullable: true, defaultValue: false, description: 'recipientId parameter for notification', index: 1 },
  { name: 'recipientIdMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum recipientId filter for notification', index: 1 },
  { name: 'recipientIdMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum recipientId filter for notification', index: 1 },
  { name: 'channel', mode: 'input', type: 'string', required: true, nullable: true, defaultValue: null, description: 'channel parameter for notification', index: 2 },
  { name: 'channel', mode: 'filter', type: 'string', required: true, nullable: true, defaultValue: null, description: 'channel parameter for notification', index: 2 },
  { name: 'channel', mode: 'sort', type: 'string', required: true, nullable: true, defaultValue: false, description: 'channel parameter for notification', index: 2 },
  { name: 'channel', mode: 'search', type: 'string', required: true, nullable: true, defaultValue: null, description: 'channel parameter for notification', index: 2 },
  { name: 'channel', mode: 'export', type: 'string', required: true, nullable: true, defaultValue: false, description: 'channel parameter for notification', index: 2 },
  { name: 'channelMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum channel filter for notification', index: 2 },
  { name: 'channelMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum channel filter for notification', index: 2 },
  { name: 'subject', mode: 'input', type: 'string', required: true, nullable: true, defaultValue: null, description: 'subject parameter for notification', index: 3 },
  { name: 'subject', mode: 'filter', type: 'string', required: true, nullable: true, defaultValue: null, description: 'subject parameter for notification', index: 3 },
  { name: 'subject', mode: 'sort', type: 'string', required: true, nullable: true, defaultValue: false, description: 'subject parameter for notification', index: 3 },
  { name: 'subject', mode: 'search', type: 'string', required: true, nullable: true, defaultValue: null, description: 'subject parameter for notification', index: 3 },
  { name: 'subject', mode: 'export', type: 'string', required: true, nullable: true, defaultValue: false, description: 'subject parameter for notification', index: 3 },
  { name: 'subjectMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum subject filter for notification', index: 3 },
  { name: 'subjectMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum subject filter for notification', index: 3 },
  { name: 'message', mode: 'input', type: 'string', required: false, nullable: true, defaultValue: null, description: 'message parameter for notification', index: 4 },
  { name: 'message', mode: 'filter', type: 'string', required: false, nullable: true, defaultValue: null, description: 'message parameter for notification', index: 4 },
  { name: 'message', mode: 'sort', type: 'string', required: false, nullable: true, defaultValue: false, description: 'message parameter for notification', index: 4 },
  { name: 'message', mode: 'search', type: 'string', required: false, nullable: true, defaultValue: null, description: 'message parameter for notification', index: 4 },
  { name: 'message', mode: 'export', type: 'string', required: false, nullable: true, defaultValue: false, description: 'message parameter for notification', index: 4 },
  { name: 'messageMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum message filter for notification', index: 4 },
  { name: 'messageMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum message filter for notification', index: 4 },
  { name: 'priority', mode: 'input', type: 'string', required: false, nullable: true, defaultValue: null, description: 'priority parameter for notification', index: 5 },
  { name: 'priority', mode: 'filter', type: 'string', required: false, nullable: true, defaultValue: null, description: 'priority parameter for notification', index: 5 },
  { name: 'priority', mode: 'sort', type: 'string', required: false, nullable: true, defaultValue: false, description: 'priority parameter for notification', index: 5 },
  { name: 'priority', mode: 'search', type: 'string', required: false, nullable: true, defaultValue: null, description: 'priority parameter for notification', index: 5 },
  { name: 'priority', mode: 'export', type: 'string', required: false, nullable: true, defaultValue: false, description: 'priority parameter for notification', index: 5 },
  { name: 'priorityMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum priority filter for notification', index: 5 },
  { name: 'priorityMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum priority filter for notification', index: 5 },
  { name: 'scheduledAt', mode: 'input', type: 'string', required: false, nullable: true, defaultValue: null, description: 'scheduledAt parameter for notification', index: 6 },
  { name: 'scheduledAt', mode: 'filter', type: 'string', required: false, nullable: true, defaultValue: null, description: 'scheduledAt parameter for notification', index: 6 },
  { name: 'scheduledAt', mode: 'sort', type: 'string', required: false, nullable: true, defaultValue: false, description: 'scheduledAt parameter for notification', index: 6 },
  { name: 'scheduledAt', mode: 'search', type: 'string', required: false, nullable: true, defaultValue: null, description: 'scheduledAt parameter for notification', index: 6 },
  { name: 'scheduledAt', mode: 'export', type: 'string', required: false, nullable: true, defaultValue: false, description: 'scheduledAt parameter for notification', index: 6 },
  { name: 'scheduledAtMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum scheduledAt filter for notification', index: 6 },
  { name: 'scheduledAtMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum scheduledAt filter for notification', index: 6 },
  { name: 'sentAt', mode: 'input', type: 'string', required: false, nullable: true, defaultValue: null, description: 'sentAt parameter for notification', index: 7 },
  { name: 'sentAt', mode: 'filter', type: 'string', required: false, nullable: true, defaultValue: null, description: 'sentAt parameter for notification', index: 7 },
  { name: 'sentAt', mode: 'sort', type: 'string', required: false, nullable: true, defaultValue: false, description: 'sentAt parameter for notification', index: 7 },
  { name: 'sentAt', mode: 'search', type: 'string', required: false, nullable: true, defaultValue: null, description: 'sentAt parameter for notification', index: 7 },
  { name: 'sentAt', mode: 'export', type: 'string', required: false, nullable: true, defaultValue: false, description: 'sentAt parameter for notification', index: 7 },
  { name: 'sentAtMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum sentAt filter for notification', index: 7 },
  { name: 'sentAtMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum sentAt filter for notification', index: 7 },
  { name: 'readAt', mode: 'input', type: 'string', required: false, nullable: true, defaultValue: null, description: 'readAt parameter for notification', index: 8 },
  { name: 'readAt', mode: 'filter', type: 'string', required: false, nullable: true, defaultValue: null, description: 'readAt parameter for notification', index: 8 },
  { name: 'readAt', mode: 'sort', type: 'string', required: false, nullable: true, defaultValue: false, description: 'readAt parameter for notification', index: 8 },
  { name: 'readAt', mode: 'search', type: 'string', required: false, nullable: true, defaultValue: null, description: 'readAt parameter for notification', index: 8 },
  { name: 'readAt', mode: 'export', type: 'string', required: false, nullable: true, defaultValue: false, description: 'readAt parameter for notification', index: 8 },
  { name: 'readAtMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum readAt filter for notification', index: 8 },
  { name: 'readAtMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum readAt filter for notification', index: 8 },
  { name: 'status', mode: 'input', type: 'string', required: false, nullable: true, defaultValue: null, description: 'status parameter for notification', index: 9 },
  { name: 'status', mode: 'filter', type: 'string', required: false, nullable: true, defaultValue: null, description: 'status parameter for notification', index: 9 },
  { name: 'status', mode: 'sort', type: 'string', required: false, nullable: true, defaultValue: false, description: 'status parameter for notification', index: 9 },
  { name: 'status', mode: 'search', type: 'string', required: false, nullable: true, defaultValue: null, description: 'status parameter for notification', index: 9 },
  { name: 'status', mode: 'export', type: 'string', required: false, nullable: true, defaultValue: false, description: 'status parameter for notification', index: 9 },
  { name: 'statusMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum status filter for notification', index: 9 },
  { name: 'statusMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum status filter for notification', index: 9 },
];

function get(name){return parameters.find(p=>p.name===name)||null;}
function list(mode){return mode?parameters.filter(p=>p.mode===mode):[...parameters];}
function required(){return parameters.filter(p=>p.required);}
function validateParameter(name,value){const p=get(name);if(!p)return {ok:false,code:'UNKNOWN_PARAMETER'};if(value===null&&p.nullable)return {ok:true};if(p.type==='number'&&typeof value!=='number')return {ok:false,code:'TYPE_ERROR'};if(p.type==='boolean'&&typeof value!=='boolean')return {ok:false,code:'TYPE_ERROR'};if(p.type==='string'&&typeof value!=='string')return {ok:false,code:'TYPE_ERROR'};return {ok:true};}
function validateObject(input={}){const errors=[];for(const p of required()){if(input[p.name]===undefined||input[p.name]===null||input[p.name]==='')errors.push({field:p.name,code:'REQUIRED'});}for(const [k,v] of Object.entries(input)){const result=validateParameter(k,v);if(!result.ok)errors.push({field:k,code:result.code});}return errors;}
function defaults(){return Object.fromEntries(parameters.filter(p=>p.defaultValue!==null).map(p=>[p.name,p.defaultValue]));}
function describe(){return {entity,parameterCount:parameters.length,parameters};}
module.exports={entity,parameters,get,list,required,validateParameter,validateObject,defaults,describe};
