'use strict';
// Complete parameter catalog for patient.
const entity='patient';
const parameters=[
  { name: 'mrn', mode: 'input', type: 'string', required: true, nullable: true, defaultValue: null, description: 'mrn parameter for patient', index: 1 },
  { name: 'mrn', mode: 'filter', type: 'string', required: true, nullable: true, defaultValue: null, description: 'mrn parameter for patient', index: 1 },
  { name: 'mrn', mode: 'sort', type: 'string', required: true, nullable: true, defaultValue: false, description: 'mrn parameter for patient', index: 1 },
  { name: 'mrn', mode: 'search', type: 'string', required: true, nullable: true, defaultValue: null, description: 'mrn parameter for patient', index: 1 },
  { name: 'mrn', mode: 'export', type: 'string', required: true, nullable: true, defaultValue: false, description: 'mrn parameter for patient', index: 1 },
  { name: 'mrnMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum mrn filter for patient', index: 1 },
  { name: 'mrnMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum mrn filter for patient', index: 1 },
  { name: 'firstName', mode: 'input', type: 'string', required: true, nullable: true, defaultValue: null, description: 'firstName parameter for patient', index: 2 },
  { name: 'firstName', mode: 'filter', type: 'string', required: true, nullable: true, defaultValue: null, description: 'firstName parameter for patient', index: 2 },
  { name: 'firstName', mode: 'sort', type: 'string', required: true, nullable: true, defaultValue: false, description: 'firstName parameter for patient', index: 2 },
  { name: 'firstName', mode: 'search', type: 'string', required: true, nullable: true, defaultValue: null, description: 'firstName parameter for patient', index: 2 },
  { name: 'firstName', mode: 'export', type: 'string', required: true, nullable: true, defaultValue: false, description: 'firstName parameter for patient', index: 2 },
  { name: 'firstNameMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum firstName filter for patient', index: 2 },
  { name: 'firstNameMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum firstName filter for patient', index: 2 },
  { name: 'lastName', mode: 'input', type: 'string', required: true, nullable: true, defaultValue: null, description: 'lastName parameter for patient', index: 3 },
  { name: 'lastName', mode: 'filter', type: 'string', required: true, nullable: true, defaultValue: null, description: 'lastName parameter for patient', index: 3 },
  { name: 'lastName', mode: 'sort', type: 'string', required: true, nullable: true, defaultValue: false, description: 'lastName parameter for patient', index: 3 },
  { name: 'lastName', mode: 'search', type: 'string', required: true, nullable: true, defaultValue: null, description: 'lastName parameter for patient', index: 3 },
  { name: 'lastName', mode: 'export', type: 'string', required: true, nullable: true, defaultValue: false, description: 'lastName parameter for patient', index: 3 },
  { name: 'lastNameMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum lastName filter for patient', index: 3 },
  { name: 'lastNameMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum lastName filter for patient', index: 3 },
  { name: 'dateOfBirth', mode: 'input', type: 'string', required: false, nullable: true, defaultValue: null, description: 'dateOfBirth parameter for patient', index: 4 },
  { name: 'dateOfBirth', mode: 'filter', type: 'string', required: false, nullable: true, defaultValue: null, description: 'dateOfBirth parameter for patient', index: 4 },
  { name: 'dateOfBirth', mode: 'sort', type: 'string', required: false, nullable: true, defaultValue: false, description: 'dateOfBirth parameter for patient', index: 4 },
  { name: 'dateOfBirth', mode: 'search', type: 'string', required: false, nullable: true, defaultValue: null, description: 'dateOfBirth parameter for patient', index: 4 },
  { name: 'dateOfBirth', mode: 'export', type: 'string', required: false, nullable: true, defaultValue: false, description: 'dateOfBirth parameter for patient', index: 4 },
  { name: 'dateOfBirthMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum dateOfBirth filter for patient', index: 4 },
  { name: 'dateOfBirthMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum dateOfBirth filter for patient', index: 4 },
  { name: 'gender', mode: 'input', type: 'string', required: false, nullable: true, defaultValue: null, description: 'gender parameter for patient', index: 5 },
  { name: 'gender', mode: 'filter', type: 'string', required: false, nullable: true, defaultValue: null, description: 'gender parameter for patient', index: 5 },
  { name: 'gender', mode: 'sort', type: 'string', required: false, nullable: true, defaultValue: false, description: 'gender parameter for patient', index: 5 },
  { name: 'gender', mode: 'search', type: 'string', required: false, nullable: true, defaultValue: null, description: 'gender parameter for patient', index: 5 },
  { name: 'gender', mode: 'export', type: 'string', required: false, nullable: true, defaultValue: false, description: 'gender parameter for patient', index: 5 },
  { name: 'genderMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum gender filter for patient', index: 5 },
  { name: 'genderMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum gender filter for patient', index: 5 },
  { name: 'bloodGroup', mode: 'input', type: 'string', required: false, nullable: true, defaultValue: null, description: 'bloodGroup parameter for patient', index: 6 },
  { name: 'bloodGroup', mode: 'filter', type: 'string', required: false, nullable: true, defaultValue: null, description: 'bloodGroup parameter for patient', index: 6 },
  { name: 'bloodGroup', mode: 'sort', type: 'string', required: false, nullable: true, defaultValue: false, description: 'bloodGroup parameter for patient', index: 6 },
  { name: 'bloodGroup', mode: 'search', type: 'string', required: false, nullable: true, defaultValue: null, description: 'bloodGroup parameter for patient', index: 6 },
  { name: 'bloodGroup', mode: 'export', type: 'string', required: false, nullable: true, defaultValue: false, description: 'bloodGroup parameter for patient', index: 6 },
  { name: 'bloodGroupMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum bloodGroup filter for patient', index: 6 },
  { name: 'bloodGroupMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum bloodGroup filter for patient', index: 6 },
  { name: 'phone', mode: 'input', type: 'string', required: false, nullable: true, defaultValue: null, description: 'phone parameter for patient', index: 7 },
  { name: 'phone', mode: 'filter', type: 'string', required: false, nullable: true, defaultValue: null, description: 'phone parameter for patient', index: 7 },
  { name: 'phone', mode: 'sort', type: 'string', required: false, nullable: true, defaultValue: false, description: 'phone parameter for patient', index: 7 },
  { name: 'phone', mode: 'search', type: 'string', required: false, nullable: true, defaultValue: null, description: 'phone parameter for patient', index: 7 },
  { name: 'phone', mode: 'export', type: 'string', required: false, nullable: true, defaultValue: false, description: 'phone parameter for patient', index: 7 },
  { name: 'phoneMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum phone filter for patient', index: 7 },
  { name: 'phoneMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum phone filter for patient', index: 7 },
  { name: 'email', mode: 'input', type: 'string', required: false, nullable: true, defaultValue: null, description: 'email parameter for patient', index: 8 },
  { name: 'email', mode: 'filter', type: 'string', required: false, nullable: true, defaultValue: null, description: 'email parameter for patient', index: 8 },
  { name: 'email', mode: 'sort', type: 'string', required: false, nullable: true, defaultValue: false, description: 'email parameter for patient', index: 8 },
  { name: 'email', mode: 'search', type: 'string', required: false, nullable: true, defaultValue: null, description: 'email parameter for patient', index: 8 },
  { name: 'email', mode: 'export', type: 'string', required: false, nullable: true, defaultValue: false, description: 'email parameter for patient', index: 8 },
  { name: 'emailMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum email filter for patient', index: 8 },
  { name: 'emailMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum email filter for patient', index: 8 },
  { name: 'address', mode: 'input', type: 'string', required: false, nullable: true, defaultValue: null, description: 'address parameter for patient', index: 9 },
  { name: 'address', mode: 'filter', type: 'string', required: false, nullable: true, defaultValue: null, description: 'address parameter for patient', index: 9 },
  { name: 'address', mode: 'sort', type: 'string', required: false, nullable: true, defaultValue: false, description: 'address parameter for patient', index: 9 },
  { name: 'address', mode: 'search', type: 'string', required: false, nullable: true, defaultValue: null, description: 'address parameter for patient', index: 9 },
  { name: 'address', mode: 'export', type: 'string', required: false, nullable: true, defaultValue: false, description: 'address parameter for patient', index: 9 },
  { name: 'addressMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum address filter for patient', index: 9 },
  { name: 'addressMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum address filter for patient', index: 9 },
  { name: 'emergencyContact', mode: 'input', type: 'string', required: false, nullable: true, defaultValue: null, description: 'emergencyContact parameter for patient', index: 10 },
  { name: 'emergencyContact', mode: 'filter', type: 'string', required: false, nullable: true, defaultValue: null, description: 'emergencyContact parameter for patient', index: 10 },
  { name: 'emergencyContact', mode: 'sort', type: 'string', required: false, nullable: true, defaultValue: false, description: 'emergencyContact parameter for patient', index: 10 },
  { name: 'emergencyContact', mode: 'search', type: 'string', required: false, nullable: true, defaultValue: null, description: 'emergencyContact parameter for patient', index: 10 },
  { name: 'emergencyContact', mode: 'export', type: 'string', required: false, nullable: true, defaultValue: false, description: 'emergencyContact parameter for patient', index: 10 },
  { name: 'emergencyContactMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum emergencyContact filter for patient', index: 10 },
  { name: 'emergencyContactMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum emergencyContact filter for patient', index: 10 },
  { name: 'allergies', mode: 'input', type: 'string', required: false, nullable: true, defaultValue: null, description: 'allergies parameter for patient', index: 11 },
  { name: 'allergies', mode: 'filter', type: 'string', required: false, nullable: true, defaultValue: null, description: 'allergies parameter for patient', index: 11 },
  { name: 'allergies', mode: 'sort', type: 'string', required: false, nullable: true, defaultValue: false, description: 'allergies parameter for patient', index: 11 },
  { name: 'allergies', mode: 'search', type: 'string', required: false, nullable: true, defaultValue: null, description: 'allergies parameter for patient', index: 11 },
  { name: 'allergies', mode: 'export', type: 'string', required: false, nullable: true, defaultValue: false, description: 'allergies parameter for patient', index: 11 },
  { name: 'allergiesMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum allergies filter for patient', index: 11 },
  { name: 'allergiesMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum allergies filter for patient', index: 11 },
  { name: 'insuranceId', mode: 'input', type: 'string', required: false, nullable: true, defaultValue: null, description: 'insuranceId parameter for patient', index: 12 },
  { name: 'insuranceId', mode: 'filter', type: 'string', required: false, nullable: true, defaultValue: null, description: 'insuranceId parameter for patient', index: 12 },
  { name: 'insuranceId', mode: 'sort', type: 'string', required: false, nullable: true, defaultValue: false, description: 'insuranceId parameter for patient', index: 12 },
  { name: 'insuranceId', mode: 'search', type: 'string', required: false, nullable: true, defaultValue: null, description: 'insuranceId parameter for patient', index: 12 },
  { name: 'insuranceId', mode: 'export', type: 'string', required: false, nullable: true, defaultValue: false, description: 'insuranceId parameter for patient', index: 12 },
  { name: 'insuranceIdMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum insuranceId filter for patient', index: 12 },
  { name: 'insuranceIdMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum insuranceId filter for patient', index: 12 },
  { name: 'status', mode: 'input', type: 'string', required: false, nullable: true, defaultValue: null, description: 'status parameter for patient', index: 13 },
  { name: 'status', mode: 'filter', type: 'string', required: false, nullable: true, defaultValue: null, description: 'status parameter for patient', index: 13 },
  { name: 'status', mode: 'sort', type: 'string', required: false, nullable: true, defaultValue: false, description: 'status parameter for patient', index: 13 },
  { name: 'status', mode: 'search', type: 'string', required: false, nullable: true, defaultValue: null, description: 'status parameter for patient', index: 13 },
  { name: 'status', mode: 'export', type: 'string', required: false, nullable: true, defaultValue: false, description: 'status parameter for patient', index: 13 },
  { name: 'statusMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum status filter for patient', index: 13 },
  { name: 'statusMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum status filter for patient', index: 13 },
];

function get(name){return parameters.find(p=>p.name===name)||null;}
function list(mode){return mode?parameters.filter(p=>p.mode===mode):[...parameters];}
function required(){return parameters.filter(p=>p.required);}
function validateParameter(name,value){const p=get(name);if(!p)return {ok:false,code:'UNKNOWN_PARAMETER'};if(value===null&&p.nullable)return {ok:true};if(p.type==='number'&&typeof value!=='number')return {ok:false,code:'TYPE_ERROR'};if(p.type==='boolean'&&typeof value!=='boolean')return {ok:false,code:'TYPE_ERROR'};if(p.type==='string'&&typeof value!=='string')return {ok:false,code:'TYPE_ERROR'};return {ok:true};}
function validateObject(input={}){const errors=[];for(const p of required()){if(input[p.name]===undefined||input[p.name]===null||input[p.name]==='')errors.push({field:p.name,code:'REQUIRED'});}for(const [k,v] of Object.entries(input)){const result=validateParameter(k,v);if(!result.ok)errors.push({field:k,code:result.code});}return errors;}
function defaults(){return Object.fromEntries(parameters.filter(p=>p.defaultValue!==null).map(p=>[p.name,p.defaultValue]));}
function describe(){return {entity,parameterCount:parameters.length,parameters};}
module.exports={entity,parameters,get,list,required,validateParameter,validateObject,defaults,describe};
