'use strict';
// Complete parameter catalog for pharmacyOrder.
const entity='pharmacyOrder';
const parameters=[
  { name: 'patientId', mode: 'input', type: 'string', required: true, nullable: true, defaultValue: null, description: 'patientId parameter for pharmacyOrder', index: 1 },
  { name: 'patientId', mode: 'filter', type: 'string', required: true, nullable: true, defaultValue: null, description: 'patientId parameter for pharmacyOrder', index: 1 },
  { name: 'patientId', mode: 'sort', type: 'string', required: true, nullable: true, defaultValue: false, description: 'patientId parameter for pharmacyOrder', index: 1 },
  { name: 'patientId', mode: 'search', type: 'string', required: true, nullable: true, defaultValue: null, description: 'patientId parameter for pharmacyOrder', index: 1 },
  { name: 'patientId', mode: 'export', type: 'string', required: true, nullable: true, defaultValue: false, description: 'patientId parameter for pharmacyOrder', index: 1 },
  { name: 'patientIdMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum patientId filter for pharmacyOrder', index: 1 },
  { name: 'patientIdMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum patientId filter for pharmacyOrder', index: 1 },
  { name: 'prescriptionId', mode: 'input', type: 'string', required: true, nullable: true, defaultValue: null, description: 'prescriptionId parameter for pharmacyOrder', index: 2 },
  { name: 'prescriptionId', mode: 'filter', type: 'string', required: true, nullable: true, defaultValue: null, description: 'prescriptionId parameter for pharmacyOrder', index: 2 },
  { name: 'prescriptionId', mode: 'sort', type: 'string', required: true, nullable: true, defaultValue: false, description: 'prescriptionId parameter for pharmacyOrder', index: 2 },
  { name: 'prescriptionId', mode: 'search', type: 'string', required: true, nullable: true, defaultValue: null, description: 'prescriptionId parameter for pharmacyOrder', index: 2 },
  { name: 'prescriptionId', mode: 'export', type: 'string', required: true, nullable: true, defaultValue: false, description: 'prescriptionId parameter for pharmacyOrder', index: 2 },
  { name: 'prescriptionIdMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum prescriptionId filter for pharmacyOrder', index: 2 },
  { name: 'prescriptionIdMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum prescriptionId filter for pharmacyOrder', index: 2 },
  { name: 'items', mode: 'input', type: 'string', required: true, nullable: true, defaultValue: null, description: 'items parameter for pharmacyOrder', index: 3 },
  { name: 'items', mode: 'filter', type: 'string', required: true, nullable: true, defaultValue: null, description: 'items parameter for pharmacyOrder', index: 3 },
  { name: 'items', mode: 'sort', type: 'string', required: true, nullable: true, defaultValue: false, description: 'items parameter for pharmacyOrder', index: 3 },
  { name: 'items', mode: 'search', type: 'string', required: true, nullable: true, defaultValue: null, description: 'items parameter for pharmacyOrder', index: 3 },
  { name: 'items', mode: 'export', type: 'string', required: true, nullable: true, defaultValue: false, description: 'items parameter for pharmacyOrder', index: 3 },
  { name: 'itemsMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum items filter for pharmacyOrder', index: 3 },
  { name: 'itemsMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum items filter for pharmacyOrder', index: 3 },
  { name: 'subtotal', mode: 'input', type: 'number', required: false, nullable: true, defaultValue: null, description: 'subtotal parameter for pharmacyOrder', index: 4 },
  { name: 'subtotal', mode: 'filter', type: 'number', required: false, nullable: true, defaultValue: null, description: 'subtotal parameter for pharmacyOrder', index: 4 },
  { name: 'subtotal', mode: 'sort', type: 'number', required: false, nullable: true, defaultValue: false, description: 'subtotal parameter for pharmacyOrder', index: 4 },
  { name: 'subtotal', mode: 'search', type: 'number', required: false, nullable: true, defaultValue: null, description: 'subtotal parameter for pharmacyOrder', index: 4 },
  { name: 'subtotal', mode: 'export', type: 'number', required: false, nullable: true, defaultValue: false, description: 'subtotal parameter for pharmacyOrder', index: 4 },
  { name: 'subtotalMin', mode: 'range', type: 'number', required: false, nullable: true, defaultValue: null, description: 'Minimum subtotal filter for pharmacyOrder', index: 4 },
  { name: 'subtotalMax', mode: 'range', type: 'number', required: false, nullable: true, defaultValue: null, description: 'Maximum subtotal filter for pharmacyOrder', index: 4 },
  { name: 'discount', mode: 'input', type: 'number', required: false, nullable: true, defaultValue: null, description: 'discount parameter for pharmacyOrder', index: 5 },
  { name: 'discount', mode: 'filter', type: 'number', required: false, nullable: true, defaultValue: null, description: 'discount parameter for pharmacyOrder', index: 5 },
  { name: 'discount', mode: 'sort', type: 'number', required: false, nullable: true, defaultValue: false, description: 'discount parameter for pharmacyOrder', index: 5 },
  { name: 'discount', mode: 'search', type: 'number', required: false, nullable: true, defaultValue: null, description: 'discount parameter for pharmacyOrder', index: 5 },
  { name: 'discount', mode: 'export', type: 'number', required: false, nullable: true, defaultValue: false, description: 'discount parameter for pharmacyOrder', index: 5 },
  { name: 'discountMin', mode: 'range', type: 'number', required: false, nullable: true, defaultValue: null, description: 'Minimum discount filter for pharmacyOrder', index: 5 },
  { name: 'discountMax', mode: 'range', type: 'number', required: false, nullable: true, defaultValue: null, description: 'Maximum discount filter for pharmacyOrder', index: 5 },
  { name: 'tax', mode: 'input', type: 'number', required: false, nullable: true, defaultValue: null, description: 'tax parameter for pharmacyOrder', index: 6 },
  { name: 'tax', mode: 'filter', type: 'number', required: false, nullable: true, defaultValue: null, description: 'tax parameter for pharmacyOrder', index: 6 },
  { name: 'tax', mode: 'sort', type: 'number', required: false, nullable: true, defaultValue: false, description: 'tax parameter for pharmacyOrder', index: 6 },
  { name: 'tax', mode: 'search', type: 'number', required: false, nullable: true, defaultValue: null, description: 'tax parameter for pharmacyOrder', index: 6 },
  { name: 'tax', mode: 'export', type: 'number', required: false, nullable: true, defaultValue: false, description: 'tax parameter for pharmacyOrder', index: 6 },
  { name: 'taxMin', mode: 'range', type: 'number', required: false, nullable: true, defaultValue: null, description: 'Minimum tax filter for pharmacyOrder', index: 6 },
  { name: 'taxMax', mode: 'range', type: 'number', required: false, nullable: true, defaultValue: null, description: 'Maximum tax filter for pharmacyOrder', index: 6 },
  { name: 'total', mode: 'input', type: 'number', required: false, nullable: true, defaultValue: null, description: 'total parameter for pharmacyOrder', index: 7 },
  { name: 'total', mode: 'filter', type: 'number', required: false, nullable: true, defaultValue: null, description: 'total parameter for pharmacyOrder', index: 7 },
  { name: 'total', mode: 'sort', type: 'number', required: false, nullable: true, defaultValue: false, description: 'total parameter for pharmacyOrder', index: 7 },
  { name: 'total', mode: 'search', type: 'number', required: false, nullable: true, defaultValue: null, description: 'total parameter for pharmacyOrder', index: 7 },
  { name: 'total', mode: 'export', type: 'number', required: false, nullable: true, defaultValue: false, description: 'total parameter for pharmacyOrder', index: 7 },
  { name: 'totalMin', mode: 'range', type: 'number', required: false, nullable: true, defaultValue: null, description: 'Minimum total filter for pharmacyOrder', index: 7 },
  { name: 'totalMax', mode: 'range', type: 'number', required: false, nullable: true, defaultValue: null, description: 'Maximum total filter for pharmacyOrder', index: 7 },
  { name: 'dispensedAt', mode: 'input', type: 'string', required: false, nullable: true, defaultValue: null, description: 'dispensedAt parameter for pharmacyOrder', index: 8 },
  { name: 'dispensedAt', mode: 'filter', type: 'string', required: false, nullable: true, defaultValue: null, description: 'dispensedAt parameter for pharmacyOrder', index: 8 },
  { name: 'dispensedAt', mode: 'sort', type: 'string', required: false, nullable: true, defaultValue: false, description: 'dispensedAt parameter for pharmacyOrder', index: 8 },
  { name: 'dispensedAt', mode: 'search', type: 'string', required: false, nullable: true, defaultValue: null, description: 'dispensedAt parameter for pharmacyOrder', index: 8 },
  { name: 'dispensedAt', mode: 'export', type: 'string', required: false, nullable: true, defaultValue: false, description: 'dispensedAt parameter for pharmacyOrder', index: 8 },
  { name: 'dispensedAtMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum dispensedAt filter for pharmacyOrder', index: 8 },
  { name: 'dispensedAtMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum dispensedAt filter for pharmacyOrder', index: 8 },
  { name: 'dispensedBy', mode: 'input', type: 'string', required: false, nullable: true, defaultValue: null, description: 'dispensedBy parameter for pharmacyOrder', index: 9 },
  { name: 'dispensedBy', mode: 'filter', type: 'string', required: false, nullable: true, defaultValue: null, description: 'dispensedBy parameter for pharmacyOrder', index: 9 },
  { name: 'dispensedBy', mode: 'sort', type: 'string', required: false, nullable: true, defaultValue: false, description: 'dispensedBy parameter for pharmacyOrder', index: 9 },
  { name: 'dispensedBy', mode: 'search', type: 'string', required: false, nullable: true, defaultValue: null, description: 'dispensedBy parameter for pharmacyOrder', index: 9 },
  { name: 'dispensedBy', mode: 'export', type: 'string', required: false, nullable: true, defaultValue: false, description: 'dispensedBy parameter for pharmacyOrder', index: 9 },
  { name: 'dispensedByMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum dispensedBy filter for pharmacyOrder', index: 9 },
  { name: 'dispensedByMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum dispensedBy filter for pharmacyOrder', index: 9 },
  { name: 'status', mode: 'input', type: 'string', required: false, nullable: true, defaultValue: null, description: 'status parameter for pharmacyOrder', index: 10 },
  { name: 'status', mode: 'filter', type: 'string', required: false, nullable: true, defaultValue: null, description: 'status parameter for pharmacyOrder', index: 10 },
  { name: 'status', mode: 'sort', type: 'string', required: false, nullable: true, defaultValue: false, description: 'status parameter for pharmacyOrder', index: 10 },
  { name: 'status', mode: 'search', type: 'string', required: false, nullable: true, defaultValue: null, description: 'status parameter for pharmacyOrder', index: 10 },
  { name: 'status', mode: 'export', type: 'string', required: false, nullable: true, defaultValue: false, description: 'status parameter for pharmacyOrder', index: 10 },
  { name: 'statusMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum status filter for pharmacyOrder', index: 10 },
  { name: 'statusMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum status filter for pharmacyOrder', index: 10 },
];

function get(name){return parameters.find(p=>p.name===name)||null;}
function list(mode){return mode?parameters.filter(p=>p.mode===mode):[...parameters];}
function required(){return parameters.filter(p=>p.required);}
function validateParameter(name,value){const p=get(name);if(!p)return {ok:false,code:'UNKNOWN_PARAMETER'};if(value===null&&p.nullable)return {ok:true};if(p.type==='number'&&typeof value!=='number')return {ok:false,code:'TYPE_ERROR'};if(p.type==='boolean'&&typeof value!=='boolean')return {ok:false,code:'TYPE_ERROR'};if(p.type==='string'&&typeof value!=='string')return {ok:false,code:'TYPE_ERROR'};return {ok:true};}
function validateObject(input={}){const errors=[];for(const p of required()){if(input[p.name]===undefined||input[p.name]===null||input[p.name]==='')errors.push({field:p.name,code:'REQUIRED'});}for(const [k,v] of Object.entries(input)){const result=validateParameter(k,v);if(!result.ok)errors.push({field:k,code:result.code});}return errors;}
function defaults(){return Object.fromEntries(parameters.filter(p=>p.defaultValue!==null).map(p=>[p.name,p.defaultValue]));}
function describe(){return {entity,parameterCount:parameters.length,parameters};}
module.exports={entity,parameters,get,list,required,validateParameter,validateObject,defaults,describe};
