'use strict';
// Complete parameter catalog for prescription.
const entity='prescription';
const parameters=[
  { name: 'patientId', mode: 'input', type: 'string', required: true, nullable: true, defaultValue: null, description: 'patientId parameter for prescription', index: 1 },
  { name: 'patientId', mode: 'filter', type: 'string', required: true, nullable: true, defaultValue: null, description: 'patientId parameter for prescription', index: 1 },
  { name: 'patientId', mode: 'sort', type: 'string', required: true, nullable: true, defaultValue: false, description: 'patientId parameter for prescription', index: 1 },
  { name: 'patientId', mode: 'search', type: 'string', required: true, nullable: true, defaultValue: null, description: 'patientId parameter for prescription', index: 1 },
  { name: 'patientId', mode: 'export', type: 'string', required: true, nullable: true, defaultValue: false, description: 'patientId parameter for prescription', index: 1 },
  { name: 'patientIdMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum patientId filter for prescription', index: 1 },
  { name: 'patientIdMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum patientId filter for prescription', index: 1 },
  { name: 'doctorId', mode: 'input', type: 'string', required: true, nullable: true, defaultValue: null, description: 'doctorId parameter for prescription', index: 2 },
  { name: 'doctorId', mode: 'filter', type: 'string', required: true, nullable: true, defaultValue: null, description: 'doctorId parameter for prescription', index: 2 },
  { name: 'doctorId', mode: 'sort', type: 'string', required: true, nullable: true, defaultValue: false, description: 'doctorId parameter for prescription', index: 2 },
  { name: 'doctorId', mode: 'search', type: 'string', required: true, nullable: true, defaultValue: null, description: 'doctorId parameter for prescription', index: 2 },
  { name: 'doctorId', mode: 'export', type: 'string', required: true, nullable: true, defaultValue: false, description: 'doctorId parameter for prescription', index: 2 },
  { name: 'doctorIdMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum doctorId filter for prescription', index: 2 },
  { name: 'doctorIdMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum doctorId filter for prescription', index: 2 },
  { name: 'visitId', mode: 'input', type: 'string', required: true, nullable: true, defaultValue: null, description: 'visitId parameter for prescription', index: 3 },
  { name: 'visitId', mode: 'filter', type: 'string', required: true, nullable: true, defaultValue: null, description: 'visitId parameter for prescription', index: 3 },
  { name: 'visitId', mode: 'sort', type: 'string', required: true, nullable: true, defaultValue: false, description: 'visitId parameter for prescription', index: 3 },
  { name: 'visitId', mode: 'search', type: 'string', required: true, nullable: true, defaultValue: null, description: 'visitId parameter for prescription', index: 3 },
  { name: 'visitId', mode: 'export', type: 'string', required: true, nullable: true, defaultValue: false, description: 'visitId parameter for prescription', index: 3 },
  { name: 'visitIdMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum visitId filter for prescription', index: 3 },
  { name: 'visitIdMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum visitId filter for prescription', index: 3 },
  { name: 'medicationId', mode: 'input', type: 'string', required: false, nullable: true, defaultValue: null, description: 'medicationId parameter for prescription', index: 4 },
  { name: 'medicationId', mode: 'filter', type: 'string', required: false, nullable: true, defaultValue: null, description: 'medicationId parameter for prescription', index: 4 },
  { name: 'medicationId', mode: 'sort', type: 'string', required: false, nullable: true, defaultValue: false, description: 'medicationId parameter for prescription', index: 4 },
  { name: 'medicationId', mode: 'search', type: 'string', required: false, nullable: true, defaultValue: null, description: 'medicationId parameter for prescription', index: 4 },
  { name: 'medicationId', mode: 'export', type: 'string', required: false, nullable: true, defaultValue: false, description: 'medicationId parameter for prescription', index: 4 },
  { name: 'medicationIdMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum medicationId filter for prescription', index: 4 },
  { name: 'medicationIdMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum medicationId filter for prescription', index: 4 },
  { name: 'dose', mode: 'input', type: 'string', required: false, nullable: true, defaultValue: null, description: 'dose parameter for prescription', index: 5 },
  { name: 'dose', mode: 'filter', type: 'string', required: false, nullable: true, defaultValue: null, description: 'dose parameter for prescription', index: 5 },
  { name: 'dose', mode: 'sort', type: 'string', required: false, nullable: true, defaultValue: false, description: 'dose parameter for prescription', index: 5 },
  { name: 'dose', mode: 'search', type: 'string', required: false, nullable: true, defaultValue: null, description: 'dose parameter for prescription', index: 5 },
  { name: 'dose', mode: 'export', type: 'string', required: false, nullable: true, defaultValue: false, description: 'dose parameter for prescription', index: 5 },
  { name: 'doseMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum dose filter for prescription', index: 5 },
  { name: 'doseMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum dose filter for prescription', index: 5 },
  { name: 'route', mode: 'input', type: 'string', required: false, nullable: true, defaultValue: null, description: 'route parameter for prescription', index: 6 },
  { name: 'route', mode: 'filter', type: 'string', required: false, nullable: true, defaultValue: null, description: 'route parameter for prescription', index: 6 },
  { name: 'route', mode: 'sort', type: 'string', required: false, nullable: true, defaultValue: false, description: 'route parameter for prescription', index: 6 },
  { name: 'route', mode: 'search', type: 'string', required: false, nullable: true, defaultValue: null, description: 'route parameter for prescription', index: 6 },
  { name: 'route', mode: 'export', type: 'string', required: false, nullable: true, defaultValue: false, description: 'route parameter for prescription', index: 6 },
  { name: 'routeMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum route filter for prescription', index: 6 },
  { name: 'routeMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum route filter for prescription', index: 6 },
  { name: 'frequency', mode: 'input', type: 'string', required: false, nullable: true, defaultValue: null, description: 'frequency parameter for prescription', index: 7 },
  { name: 'frequency', mode: 'filter', type: 'string', required: false, nullable: true, defaultValue: null, description: 'frequency parameter for prescription', index: 7 },
  { name: 'frequency', mode: 'sort', type: 'string', required: false, nullable: true, defaultValue: false, description: 'frequency parameter for prescription', index: 7 },
  { name: 'frequency', mode: 'search', type: 'string', required: false, nullable: true, defaultValue: null, description: 'frequency parameter for prescription', index: 7 },
  { name: 'frequency', mode: 'export', type: 'string', required: false, nullable: true, defaultValue: false, description: 'frequency parameter for prescription', index: 7 },
  { name: 'frequencyMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum frequency filter for prescription', index: 7 },
  { name: 'frequencyMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum frequency filter for prescription', index: 7 },
  { name: 'durationDays', mode: 'input', type: 'number', required: false, nullable: true, defaultValue: null, description: 'durationDays parameter for prescription', index: 8 },
  { name: 'durationDays', mode: 'filter', type: 'number', required: false, nullable: true, defaultValue: null, description: 'durationDays parameter for prescription', index: 8 },
  { name: 'durationDays', mode: 'sort', type: 'number', required: false, nullable: true, defaultValue: false, description: 'durationDays parameter for prescription', index: 8 },
  { name: 'durationDays', mode: 'search', type: 'number', required: false, nullable: true, defaultValue: null, description: 'durationDays parameter for prescription', index: 8 },
  { name: 'durationDays', mode: 'export', type: 'number', required: false, nullable: true, defaultValue: false, description: 'durationDays parameter for prescription', index: 8 },
  { name: 'durationDaysMin', mode: 'range', type: 'number', required: false, nullable: true, defaultValue: null, description: 'Minimum durationDays filter for prescription', index: 8 },
  { name: 'durationDaysMax', mode: 'range', type: 'number', required: false, nullable: true, defaultValue: null, description: 'Maximum durationDays filter for prescription', index: 8 },
  { name: 'quantity', mode: 'input', type: 'number', required: false, nullable: true, defaultValue: null, description: 'quantity parameter for prescription', index: 9 },
  { name: 'quantity', mode: 'filter', type: 'number', required: false, nullable: true, defaultValue: null, description: 'quantity parameter for prescription', index: 9 },
  { name: 'quantity', mode: 'sort', type: 'number', required: false, nullable: true, defaultValue: false, description: 'quantity parameter for prescription', index: 9 },
  { name: 'quantity', mode: 'search', type: 'number', required: false, nullable: true, defaultValue: null, description: 'quantity parameter for prescription', index: 9 },
  { name: 'quantity', mode: 'export', type: 'number', required: false, nullable: true, defaultValue: false, description: 'quantity parameter for prescription', index: 9 },
  { name: 'quantityMin', mode: 'range', type: 'number', required: false, nullable: true, defaultValue: null, description: 'Minimum quantity filter for prescription', index: 9 },
  { name: 'quantityMax', mode: 'range', type: 'number', required: false, nullable: true, defaultValue: null, description: 'Maximum quantity filter for prescription', index: 9 },
  { name: 'instructions', mode: 'input', type: 'string', required: false, nullable: true, defaultValue: null, description: 'instructions parameter for prescription', index: 10 },
  { name: 'instructions', mode: 'filter', type: 'string', required: false, nullable: true, defaultValue: null, description: 'instructions parameter for prescription', index: 10 },
  { name: 'instructions', mode: 'sort', type: 'string', required: false, nullable: true, defaultValue: false, description: 'instructions parameter for prescription', index: 10 },
  { name: 'instructions', mode: 'search', type: 'string', required: false, nullable: true, defaultValue: null, description: 'instructions parameter for prescription', index: 10 },
  { name: 'instructions', mode: 'export', type: 'string', required: false, nullable: true, defaultValue: false, description: 'instructions parameter for prescription', index: 10 },
  { name: 'instructionsMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum instructions filter for prescription', index: 10 },
  { name: 'instructionsMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum instructions filter for prescription', index: 10 },
  { name: 'status', mode: 'input', type: 'string', required: false, nullable: true, defaultValue: null, description: 'status parameter for prescription', index: 11 },
  { name: 'status', mode: 'filter', type: 'string', required: false, nullable: true, defaultValue: null, description: 'status parameter for prescription', index: 11 },
  { name: 'status', mode: 'sort', type: 'string', required: false, nullable: true, defaultValue: false, description: 'status parameter for prescription', index: 11 },
  { name: 'status', mode: 'search', type: 'string', required: false, nullable: true, defaultValue: null, description: 'status parameter for prescription', index: 11 },
  { name: 'status', mode: 'export', type: 'string', required: false, nullable: true, defaultValue: false, description: 'status parameter for prescription', index: 11 },
  { name: 'statusMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum status filter for prescription', index: 11 },
  { name: 'statusMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum status filter for prescription', index: 11 },
];

function get(name){return parameters.find(p=>p.name===name)||null;}
function list(mode){return mode?parameters.filter(p=>p.mode===mode):[...parameters];}
function required(){return parameters.filter(p=>p.required);}
function validateParameter(name,value){const p=get(name);if(!p)return {ok:false,code:'UNKNOWN_PARAMETER'};if(value===null&&p.nullable)return {ok:true};if(p.type==='number'&&typeof value!=='number')return {ok:false,code:'TYPE_ERROR'};if(p.type==='boolean'&&typeof value!=='boolean')return {ok:false,code:'TYPE_ERROR'};if(p.type==='string'&&typeof value!=='string')return {ok:false,code:'TYPE_ERROR'};return {ok:true};}
function validateObject(input={}){const errors=[];for(const p of required()){if(input[p.name]===undefined||input[p.name]===null||input[p.name]==='')errors.push({field:p.name,code:'REQUIRED'});}for(const [k,v] of Object.entries(input)){const result=validateParameter(k,v);if(!result.ok)errors.push({field:k,code:result.code});}return errors;}
function defaults(){return Object.fromEntries(parameters.filter(p=>p.defaultValue!==null).map(p=>[p.name,p.defaultValue]));}
function describe(){return {entity,parameterCount:parameters.length,parameters};}
module.exports={entity,parameters,get,list,required,validateParameter,validateObject,defaults,describe};
