'use strict';
// Complete parameter catalog for procedure.
const entity='procedure';
const parameters=[
  { name: 'patientId', mode: 'input', type: 'string', required: true, nullable: true, defaultValue: null, description: 'patientId parameter for procedure', index: 1 },
  { name: 'patientId', mode: 'filter', type: 'string', required: true, nullable: true, defaultValue: null, description: 'patientId parameter for procedure', index: 1 },
  { name: 'patientId', mode: 'sort', type: 'string', required: true, nullable: true, defaultValue: false, description: 'patientId parameter for procedure', index: 1 },
  { name: 'patientId', mode: 'search', type: 'string', required: true, nullable: true, defaultValue: null, description: 'patientId parameter for procedure', index: 1 },
  { name: 'patientId', mode: 'export', type: 'string', required: true, nullable: true, defaultValue: false, description: 'patientId parameter for procedure', index: 1 },
  { name: 'patientIdMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum patientId filter for procedure', index: 1 },
  { name: 'patientIdMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum patientId filter for procedure', index: 1 },
  { name: 'doctorId', mode: 'input', type: 'string', required: true, nullable: true, defaultValue: null, description: 'doctorId parameter for procedure', index: 2 },
  { name: 'doctorId', mode: 'filter', type: 'string', required: true, nullable: true, defaultValue: null, description: 'doctorId parameter for procedure', index: 2 },
  { name: 'doctorId', mode: 'sort', type: 'string', required: true, nullable: true, defaultValue: false, description: 'doctorId parameter for procedure', index: 2 },
  { name: 'doctorId', mode: 'search', type: 'string', required: true, nullable: true, defaultValue: null, description: 'doctorId parameter for procedure', index: 2 },
  { name: 'doctorId', mode: 'export', type: 'string', required: true, nullable: true, defaultValue: false, description: 'doctorId parameter for procedure', index: 2 },
  { name: 'doctorIdMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum doctorId filter for procedure', index: 2 },
  { name: 'doctorIdMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum doctorId filter for procedure', index: 2 },
  { name: 'visitId', mode: 'input', type: 'string', required: true, nullable: true, defaultValue: null, description: 'visitId parameter for procedure', index: 3 },
  { name: 'visitId', mode: 'filter', type: 'string', required: true, nullable: true, defaultValue: null, description: 'visitId parameter for procedure', index: 3 },
  { name: 'visitId', mode: 'sort', type: 'string', required: true, nullable: true, defaultValue: false, description: 'visitId parameter for procedure', index: 3 },
  { name: 'visitId', mode: 'search', type: 'string', required: true, nullable: true, defaultValue: null, description: 'visitId parameter for procedure', index: 3 },
  { name: 'visitId', mode: 'export', type: 'string', required: true, nullable: true, defaultValue: false, description: 'visitId parameter for procedure', index: 3 },
  { name: 'visitIdMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum visitId filter for procedure', index: 3 },
  { name: 'visitIdMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum visitId filter for procedure', index: 3 },
  { name: 'code', mode: 'input', type: 'string', required: false, nullable: true, defaultValue: null, description: 'code parameter for procedure', index: 4 },
  { name: 'code', mode: 'filter', type: 'string', required: false, nullable: true, defaultValue: null, description: 'code parameter for procedure', index: 4 },
  { name: 'code', mode: 'sort', type: 'string', required: false, nullable: true, defaultValue: false, description: 'code parameter for procedure', index: 4 },
  { name: 'code', mode: 'search', type: 'string', required: false, nullable: true, defaultValue: null, description: 'code parameter for procedure', index: 4 },
  { name: 'code', mode: 'export', type: 'string', required: false, nullable: true, defaultValue: false, description: 'code parameter for procedure', index: 4 },
  { name: 'codeMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum code filter for procedure', index: 4 },
  { name: 'codeMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum code filter for procedure', index: 4 },
  { name: 'name', mode: 'input', type: 'string', required: false, nullable: true, defaultValue: null, description: 'name parameter for procedure', index: 5 },
  { name: 'name', mode: 'filter', type: 'string', required: false, nullable: true, defaultValue: null, description: 'name parameter for procedure', index: 5 },
  { name: 'name', mode: 'sort', type: 'string', required: false, nullable: true, defaultValue: false, description: 'name parameter for procedure', index: 5 },
  { name: 'name', mode: 'search', type: 'string', required: false, nullable: true, defaultValue: null, description: 'name parameter for procedure', index: 5 },
  { name: 'name', mode: 'export', type: 'string', required: false, nullable: true, defaultValue: false, description: 'name parameter for procedure', index: 5 },
  { name: 'nameMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum name filter for procedure', index: 5 },
  { name: 'nameMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum name filter for procedure', index: 5 },
  { name: 'performedAt', mode: 'input', type: 'string', required: false, nullable: true, defaultValue: null, description: 'performedAt parameter for procedure', index: 6 },
  { name: 'performedAt', mode: 'filter', type: 'string', required: false, nullable: true, defaultValue: null, description: 'performedAt parameter for procedure', index: 6 },
  { name: 'performedAt', mode: 'sort', type: 'string', required: false, nullable: true, defaultValue: false, description: 'performedAt parameter for procedure', index: 6 },
  { name: 'performedAt', mode: 'search', type: 'string', required: false, nullable: true, defaultValue: null, description: 'performedAt parameter for procedure', index: 6 },
  { name: 'performedAt', mode: 'export', type: 'string', required: false, nullable: true, defaultValue: false, description: 'performedAt parameter for procedure', index: 6 },
  { name: 'performedAtMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum performedAt filter for procedure', index: 6 },
  { name: 'performedAtMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum performedAt filter for procedure', index: 6 },
  { name: 'anesthesia', mode: 'input', type: 'string', required: false, nullable: true, defaultValue: null, description: 'anesthesia parameter for procedure', index: 7 },
  { name: 'anesthesia', mode: 'filter', type: 'string', required: false, nullable: true, defaultValue: null, description: 'anesthesia parameter for procedure', index: 7 },
  { name: 'anesthesia', mode: 'sort', type: 'string', required: false, nullable: true, defaultValue: false, description: 'anesthesia parameter for procedure', index: 7 },
  { name: 'anesthesia', mode: 'search', type: 'string', required: false, nullable: true, defaultValue: null, description: 'anesthesia parameter for procedure', index: 7 },
  { name: 'anesthesia', mode: 'export', type: 'string', required: false, nullable: true, defaultValue: false, description: 'anesthesia parameter for procedure', index: 7 },
  { name: 'anesthesiaMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum anesthesia filter for procedure', index: 7 },
  { name: 'anesthesiaMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum anesthesia filter for procedure', index: 7 },
  { name: 'findings', mode: 'input', type: 'string', required: false, nullable: true, defaultValue: null, description: 'findings parameter for procedure', index: 8 },
  { name: 'findings', mode: 'filter', type: 'string', required: false, nullable: true, defaultValue: null, description: 'findings parameter for procedure', index: 8 },
  { name: 'findings', mode: 'sort', type: 'string', required: false, nullable: true, defaultValue: false, description: 'findings parameter for procedure', index: 8 },
  { name: 'findings', mode: 'search', type: 'string', required: false, nullable: true, defaultValue: null, description: 'findings parameter for procedure', index: 8 },
  { name: 'findings', mode: 'export', type: 'string', required: false, nullable: true, defaultValue: false, description: 'findings parameter for procedure', index: 8 },
  { name: 'findingsMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum findings filter for procedure', index: 8 },
  { name: 'findingsMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum findings filter for procedure', index: 8 },
  { name: 'outcome', mode: 'input', type: 'string', required: false, nullable: true, defaultValue: null, description: 'outcome parameter for procedure', index: 9 },
  { name: 'outcome', mode: 'filter', type: 'string', required: false, nullable: true, defaultValue: null, description: 'outcome parameter for procedure', index: 9 },
  { name: 'outcome', mode: 'sort', type: 'string', required: false, nullable: true, defaultValue: false, description: 'outcome parameter for procedure', index: 9 },
  { name: 'outcome', mode: 'search', type: 'string', required: false, nullable: true, defaultValue: null, description: 'outcome parameter for procedure', index: 9 },
  { name: 'outcome', mode: 'export', type: 'string', required: false, nullable: true, defaultValue: false, description: 'outcome parameter for procedure', index: 9 },
  { name: 'outcomeMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum outcome filter for procedure', index: 9 },
  { name: 'outcomeMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum outcome filter for procedure', index: 9 },
  { name: 'status', mode: 'input', type: 'string', required: false, nullable: true, defaultValue: null, description: 'status parameter for procedure', index: 10 },
  { name: 'status', mode: 'filter', type: 'string', required: false, nullable: true, defaultValue: null, description: 'status parameter for procedure', index: 10 },
  { name: 'status', mode: 'sort', type: 'string', required: false, nullable: true, defaultValue: false, description: 'status parameter for procedure', index: 10 },
  { name: 'status', mode: 'search', type: 'string', required: false, nullable: true, defaultValue: null, description: 'status parameter for procedure', index: 10 },
  { name: 'status', mode: 'export', type: 'string', required: false, nullable: true, defaultValue: false, description: 'status parameter for procedure', index: 10 },
  { name: 'statusMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum status filter for procedure', index: 10 },
  { name: 'statusMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum status filter for procedure', index: 10 },
];

function get(name){return parameters.find(p=>p.name===name)||null;}
function list(mode){return mode?parameters.filter(p=>p.mode===mode):[...parameters];}
function required(){return parameters.filter(p=>p.required);}
function validateParameter(name,value){const p=get(name);if(!p)return {ok:false,code:'UNKNOWN_PARAMETER'};if(value===null&&p.nullable)return {ok:true};if(p.type==='number'&&typeof value!=='number')return {ok:false,code:'TYPE_ERROR'};if(p.type==='boolean'&&typeof value!=='boolean')return {ok:false,code:'TYPE_ERROR'};if(p.type==='string'&&typeof value!=='string')return {ok:false,code:'TYPE_ERROR'};return {ok:true};}
function validateObject(input={}){const errors=[];for(const p of required()){if(input[p.name]===undefined||input[p.name]===null||input[p.name]==='')errors.push({field:p.name,code:'REQUIRED'});}for(const [k,v] of Object.entries(input)){const result=validateParameter(k,v);if(!result.ok)errors.push({field:k,code:result.code});}return errors;}
function defaults(){return Object.fromEntries(parameters.filter(p=>p.defaultValue!==null).map(p=>[p.name,p.defaultValue]));}
function describe(){return {entity,parameterCount:parameters.length,parameters};}
module.exports={entity,parameters,get,list,required,validateParameter,validateObject,defaults,describe};
