'use strict';
// Complete parameter catalog for radiologyOrder.
const entity='radiologyOrder';
const parameters=[
  { name: 'patientId', mode: 'input', type: 'string', required: true, nullable: true, defaultValue: null, description: 'patientId parameter for radiologyOrder', index: 1 },
  { name: 'patientId', mode: 'filter', type: 'string', required: true, nullable: true, defaultValue: null, description: 'patientId parameter for radiologyOrder', index: 1 },
  { name: 'patientId', mode: 'sort', type: 'string', required: true, nullable: true, defaultValue: false, description: 'patientId parameter for radiologyOrder', index: 1 },
  { name: 'patientId', mode: 'search', type: 'string', required: true, nullable: true, defaultValue: null, description: 'patientId parameter for radiologyOrder', index: 1 },
  { name: 'patientId', mode: 'export', type: 'string', required: true, nullable: true, defaultValue: false, description: 'patientId parameter for radiologyOrder', index: 1 },
  { name: 'patientIdMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum patientId filter for radiologyOrder', index: 1 },
  { name: 'patientIdMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum patientId filter for radiologyOrder', index: 1 },
  { name: 'doctorId', mode: 'input', type: 'string', required: true, nullable: true, defaultValue: null, description: 'doctorId parameter for radiologyOrder', index: 2 },
  { name: 'doctorId', mode: 'filter', type: 'string', required: true, nullable: true, defaultValue: null, description: 'doctorId parameter for radiologyOrder', index: 2 },
  { name: 'doctorId', mode: 'sort', type: 'string', required: true, nullable: true, defaultValue: false, description: 'doctorId parameter for radiologyOrder', index: 2 },
  { name: 'doctorId', mode: 'search', type: 'string', required: true, nullable: true, defaultValue: null, description: 'doctorId parameter for radiologyOrder', index: 2 },
  { name: 'doctorId', mode: 'export', type: 'string', required: true, nullable: true, defaultValue: false, description: 'doctorId parameter for radiologyOrder', index: 2 },
  { name: 'doctorIdMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum doctorId filter for radiologyOrder', index: 2 },
  { name: 'doctorIdMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum doctorId filter for radiologyOrder', index: 2 },
  { name: 'visitId', mode: 'input', type: 'string', required: true, nullable: true, defaultValue: null, description: 'visitId parameter for radiologyOrder', index: 3 },
  { name: 'visitId', mode: 'filter', type: 'string', required: true, nullable: true, defaultValue: null, description: 'visitId parameter for radiologyOrder', index: 3 },
  { name: 'visitId', mode: 'sort', type: 'string', required: true, nullable: true, defaultValue: false, description: 'visitId parameter for radiologyOrder', index: 3 },
  { name: 'visitId', mode: 'search', type: 'string', required: true, nullable: true, defaultValue: null, description: 'visitId parameter for radiologyOrder', index: 3 },
  { name: 'visitId', mode: 'export', type: 'string', required: true, nullable: true, defaultValue: false, description: 'visitId parameter for radiologyOrder', index: 3 },
  { name: 'visitIdMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum visitId filter for radiologyOrder', index: 3 },
  { name: 'visitIdMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum visitId filter for radiologyOrder', index: 3 },
  { name: 'studyCode', mode: 'input', type: 'string', required: false, nullable: true, defaultValue: null, description: 'studyCode parameter for radiologyOrder', index: 4 },
  { name: 'studyCode', mode: 'filter', type: 'string', required: false, nullable: true, defaultValue: null, description: 'studyCode parameter for radiologyOrder', index: 4 },
  { name: 'studyCode', mode: 'sort', type: 'string', required: false, nullable: true, defaultValue: false, description: 'studyCode parameter for radiologyOrder', index: 4 },
  { name: 'studyCode', mode: 'search', type: 'string', required: false, nullable: true, defaultValue: null, description: 'studyCode parameter for radiologyOrder', index: 4 },
  { name: 'studyCode', mode: 'export', type: 'string', required: false, nullable: true, defaultValue: false, description: 'studyCode parameter for radiologyOrder', index: 4 },
  { name: 'studyCodeMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum studyCode filter for radiologyOrder', index: 4 },
  { name: 'studyCodeMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum studyCode filter for radiologyOrder', index: 4 },
  { name: 'studyName', mode: 'input', type: 'string', required: false, nullable: true, defaultValue: null, description: 'studyName parameter for radiologyOrder', index: 5 },
  { name: 'studyName', mode: 'filter', type: 'string', required: false, nullable: true, defaultValue: null, description: 'studyName parameter for radiologyOrder', index: 5 },
  { name: 'studyName', mode: 'sort', type: 'string', required: false, nullable: true, defaultValue: false, description: 'studyName parameter for radiologyOrder', index: 5 },
  { name: 'studyName', mode: 'search', type: 'string', required: false, nullable: true, defaultValue: null, description: 'studyName parameter for radiologyOrder', index: 5 },
  { name: 'studyName', mode: 'export', type: 'string', required: false, nullable: true, defaultValue: false, description: 'studyName parameter for radiologyOrder', index: 5 },
  { name: 'studyNameMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum studyName filter for radiologyOrder', index: 5 },
  { name: 'studyNameMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum studyName filter for radiologyOrder', index: 5 },
  { name: 'modality', mode: 'input', type: 'string', required: false, nullable: true, defaultValue: null, description: 'modality parameter for radiologyOrder', index: 6 },
  { name: 'modality', mode: 'filter', type: 'string', required: false, nullable: true, defaultValue: null, description: 'modality parameter for radiologyOrder', index: 6 },
  { name: 'modality', mode: 'sort', type: 'string', required: false, nullable: true, defaultValue: false, description: 'modality parameter for radiologyOrder', index: 6 },
  { name: 'modality', mode: 'search', type: 'string', required: false, nullable: true, defaultValue: null, description: 'modality parameter for radiologyOrder', index: 6 },
  { name: 'modality', mode: 'export', type: 'string', required: false, nullable: true, defaultValue: false, description: 'modality parameter for radiologyOrder', index: 6 },
  { name: 'modalityMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum modality filter for radiologyOrder', index: 6 },
  { name: 'modalityMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum modality filter for radiologyOrder', index: 6 },
  { name: 'priority', mode: 'input', type: 'string', required: false, nullable: true, defaultValue: null, description: 'priority parameter for radiologyOrder', index: 7 },
  { name: 'priority', mode: 'filter', type: 'string', required: false, nullable: true, defaultValue: null, description: 'priority parameter for radiologyOrder', index: 7 },
  { name: 'priority', mode: 'sort', type: 'string', required: false, nullable: true, defaultValue: false, description: 'priority parameter for radiologyOrder', index: 7 },
  { name: 'priority', mode: 'search', type: 'string', required: false, nullable: true, defaultValue: null, description: 'priority parameter for radiologyOrder', index: 7 },
  { name: 'priority', mode: 'export', type: 'string', required: false, nullable: true, defaultValue: false, description: 'priority parameter for radiologyOrder', index: 7 },
  { name: 'priorityMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum priority filter for radiologyOrder', index: 7 },
  { name: 'priorityMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum priority filter for radiologyOrder', index: 7 },
  { name: 'scheduledAt', mode: 'input', type: 'string', required: false, nullable: true, defaultValue: null, description: 'scheduledAt parameter for radiologyOrder', index: 8 },
  { name: 'scheduledAt', mode: 'filter', type: 'string', required: false, nullable: true, defaultValue: null, description: 'scheduledAt parameter for radiologyOrder', index: 8 },
  { name: 'scheduledAt', mode: 'sort', type: 'string', required: false, nullable: true, defaultValue: false, description: 'scheduledAt parameter for radiologyOrder', index: 8 },
  { name: 'scheduledAt', mode: 'search', type: 'string', required: false, nullable: true, defaultValue: null, description: 'scheduledAt parameter for radiologyOrder', index: 8 },
  { name: 'scheduledAt', mode: 'export', type: 'string', required: false, nullable: true, defaultValue: false, description: 'scheduledAt parameter for radiologyOrder', index: 8 },
  { name: 'scheduledAtMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum scheduledAt filter for radiologyOrder', index: 8 },
  { name: 'scheduledAtMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum scheduledAt filter for radiologyOrder', index: 8 },
  { name: 'status', mode: 'input', type: 'string', required: false, nullable: true, defaultValue: null, description: 'status parameter for radiologyOrder', index: 9 },
  { name: 'status', mode: 'filter', type: 'string', required: false, nullable: true, defaultValue: null, description: 'status parameter for radiologyOrder', index: 9 },
  { name: 'status', mode: 'sort', type: 'string', required: false, nullable: true, defaultValue: false, description: 'status parameter for radiologyOrder', index: 9 },
  { name: 'status', mode: 'search', type: 'string', required: false, nullable: true, defaultValue: null, description: 'status parameter for radiologyOrder', index: 9 },
  { name: 'status', mode: 'export', type: 'string', required: false, nullable: true, defaultValue: false, description: 'status parameter for radiologyOrder', index: 9 },
  { name: 'statusMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum status filter for radiologyOrder', index: 9 },
  { name: 'statusMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum status filter for radiologyOrder', index: 9 },
  { name: 'clinicalHistory', mode: 'input', type: 'string', required: false, nullable: true, defaultValue: null, description: 'clinicalHistory parameter for radiologyOrder', index: 10 },
  { name: 'clinicalHistory', mode: 'filter', type: 'string', required: false, nullable: true, defaultValue: null, description: 'clinicalHistory parameter for radiologyOrder', index: 10 },
  { name: 'clinicalHistory', mode: 'sort', type: 'string', required: false, nullable: true, defaultValue: false, description: 'clinicalHistory parameter for radiologyOrder', index: 10 },
  { name: 'clinicalHistory', mode: 'search', type: 'string', required: false, nullable: true, defaultValue: null, description: 'clinicalHistory parameter for radiologyOrder', index: 10 },
  { name: 'clinicalHistory', mode: 'export', type: 'string', required: false, nullable: true, defaultValue: false, description: 'clinicalHistory parameter for radiologyOrder', index: 10 },
  { name: 'clinicalHistoryMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum clinicalHistory filter for radiologyOrder', index: 10 },
  { name: 'clinicalHistoryMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum clinicalHistory filter for radiologyOrder', index: 10 },
];

function get(name){return parameters.find(p=>p.name===name)||null;}
function list(mode){return mode?parameters.filter(p=>p.mode===mode):[...parameters];}
function required(){return parameters.filter(p=>p.required);}
function validateParameter(name,value){const p=get(name);if(!p)return {ok:false,code:'UNKNOWN_PARAMETER'};if(value===null&&p.nullable)return {ok:true};if(p.type==='number'&&typeof value!=='number')return {ok:false,code:'TYPE_ERROR'};if(p.type==='boolean'&&typeof value!=='boolean')return {ok:false,code:'TYPE_ERROR'};if(p.type==='string'&&typeof value!=='string')return {ok:false,code:'TYPE_ERROR'};return {ok:true};}
function validateObject(input={}){const errors=[];for(const p of required()){if(input[p.name]===undefined||input[p.name]===null||input[p.name]==='')errors.push({field:p.name,code:'REQUIRED'});}for(const [k,v] of Object.entries(input)){const result=validateParameter(k,v);if(!result.ok)errors.push({field:k,code:result.code});}return errors;}
function defaults(){return Object.fromEntries(parameters.filter(p=>p.defaultValue!==null).map(p=>[p.name,p.defaultValue]));}
function describe(){return {entity,parameterCount:parameters.length,parameters};}
module.exports={entity,parameters,get,list,required,validateParameter,validateObject,defaults,describe};
