'use strict';
// Complete parameter catalog for visit.
const entity='visit';
const parameters=[
  { name: 'patientId', mode: 'input', type: 'string', required: true, nullable: true, defaultValue: null, description: 'patientId parameter for visit', index: 1 },
  { name: 'patientId', mode: 'filter', type: 'string', required: true, nullable: true, defaultValue: null, description: 'patientId parameter for visit', index: 1 },
  { name: 'patientId', mode: 'sort', type: 'string', required: true, nullable: true, defaultValue: false, description: 'patientId parameter for visit', index: 1 },
  { name: 'patientId', mode: 'search', type: 'string', required: true, nullable: true, defaultValue: null, description: 'patientId parameter for visit', index: 1 },
  { name: 'patientId', mode: 'export', type: 'string', required: true, nullable: true, defaultValue: false, description: 'patientId parameter for visit', index: 1 },
  { name: 'patientIdMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum patientId filter for visit', index: 1 },
  { name: 'patientIdMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum patientId filter for visit', index: 1 },
  { name: 'doctorId', mode: 'input', type: 'string', required: true, nullable: true, defaultValue: null, description: 'doctorId parameter for visit', index: 2 },
  { name: 'doctorId', mode: 'filter', type: 'string', required: true, nullable: true, defaultValue: null, description: 'doctorId parameter for visit', index: 2 },
  { name: 'doctorId', mode: 'sort', type: 'string', required: true, nullable: true, defaultValue: false, description: 'doctorId parameter for visit', index: 2 },
  { name: 'doctorId', mode: 'search', type: 'string', required: true, nullable: true, defaultValue: null, description: 'doctorId parameter for visit', index: 2 },
  { name: 'doctorId', mode: 'export', type: 'string', required: true, nullable: true, defaultValue: false, description: 'doctorId parameter for visit', index: 2 },
  { name: 'doctorIdMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum doctorId filter for visit', index: 2 },
  { name: 'doctorIdMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum doctorId filter for visit', index: 2 },
  { name: 'appointmentId', mode: 'input', type: 'string', required: true, nullable: true, defaultValue: null, description: 'appointmentId parameter for visit', index: 3 },
  { name: 'appointmentId', mode: 'filter', type: 'string', required: true, nullable: true, defaultValue: null, description: 'appointmentId parameter for visit', index: 3 },
  { name: 'appointmentId', mode: 'sort', type: 'string', required: true, nullable: true, defaultValue: false, description: 'appointmentId parameter for visit', index: 3 },
  { name: 'appointmentId', mode: 'search', type: 'string', required: true, nullable: true, defaultValue: null, description: 'appointmentId parameter for visit', index: 3 },
  { name: 'appointmentId', mode: 'export', type: 'string', required: true, nullable: true, defaultValue: false, description: 'appointmentId parameter for visit', index: 3 },
  { name: 'appointmentIdMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum appointmentId filter for visit', index: 3 },
  { name: 'appointmentIdMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum appointmentId filter for visit', index: 3 },
  { name: 'visitDate', mode: 'input', type: 'string', required: false, nullable: true, defaultValue: null, description: 'visitDate parameter for visit', index: 4 },
  { name: 'visitDate', mode: 'filter', type: 'string', required: false, nullable: true, defaultValue: null, description: 'visitDate parameter for visit', index: 4 },
  { name: 'visitDate', mode: 'sort', type: 'string', required: false, nullable: true, defaultValue: false, description: 'visitDate parameter for visit', index: 4 },
  { name: 'visitDate', mode: 'search', type: 'string', required: false, nullable: true, defaultValue: null, description: 'visitDate parameter for visit', index: 4 },
  { name: 'visitDate', mode: 'export', type: 'string', required: false, nullable: true, defaultValue: false, description: 'visitDate parameter for visit', index: 4 },
  { name: 'visitDateMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum visitDate filter for visit', index: 4 },
  { name: 'visitDateMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum visitDate filter for visit', index: 4 },
  { name: 'chiefComplaint', mode: 'input', type: 'string', required: false, nullable: true, defaultValue: null, description: 'chiefComplaint parameter for visit', index: 5 },
  { name: 'chiefComplaint', mode: 'filter', type: 'string', required: false, nullable: true, defaultValue: null, description: 'chiefComplaint parameter for visit', index: 5 },
  { name: 'chiefComplaint', mode: 'sort', type: 'string', required: false, nullable: true, defaultValue: false, description: 'chiefComplaint parameter for visit', index: 5 },
  { name: 'chiefComplaint', mode: 'search', type: 'string', required: false, nullable: true, defaultValue: null, description: 'chiefComplaint parameter for visit', index: 5 },
  { name: 'chiefComplaint', mode: 'export', type: 'string', required: false, nullable: true, defaultValue: false, description: 'chiefComplaint parameter for visit', index: 5 },
  { name: 'chiefComplaintMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum chiefComplaint filter for visit', index: 5 },
  { name: 'chiefComplaintMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum chiefComplaint filter for visit', index: 5 },
  { name: 'diagnosis', mode: 'input', type: 'string', required: false, nullable: true, defaultValue: null, description: 'diagnosis parameter for visit', index: 6 },
  { name: 'diagnosis', mode: 'filter', type: 'string', required: false, nullable: true, defaultValue: null, description: 'diagnosis parameter for visit', index: 6 },
  { name: 'diagnosis', mode: 'sort', type: 'string', required: false, nullable: true, defaultValue: false, description: 'diagnosis parameter for visit', index: 6 },
  { name: 'diagnosis', mode: 'search', type: 'string', required: false, nullable: true, defaultValue: null, description: 'diagnosis parameter for visit', index: 6 },
  { name: 'diagnosis', mode: 'export', type: 'string', required: false, nullable: true, defaultValue: false, description: 'diagnosis parameter for visit', index: 6 },
  { name: 'diagnosisMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum diagnosis filter for visit', index: 6 },
  { name: 'diagnosisMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum diagnosis filter for visit', index: 6 },
  { name: 'treatmentPlan', mode: 'input', type: 'string', required: false, nullable: true, defaultValue: null, description: 'treatmentPlan parameter for visit', index: 7 },
  { name: 'treatmentPlan', mode: 'filter', type: 'string', required: false, nullable: true, defaultValue: null, description: 'treatmentPlan parameter for visit', index: 7 },
  { name: 'treatmentPlan', mode: 'sort', type: 'string', required: false, nullable: true, defaultValue: false, description: 'treatmentPlan parameter for visit', index: 7 },
  { name: 'treatmentPlan', mode: 'search', type: 'string', required: false, nullable: true, defaultValue: null, description: 'treatmentPlan parameter for visit', index: 7 },
  { name: 'treatmentPlan', mode: 'export', type: 'string', required: false, nullable: true, defaultValue: false, description: 'treatmentPlan parameter for visit', index: 7 },
  { name: 'treatmentPlanMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum treatmentPlan filter for visit', index: 7 },
  { name: 'treatmentPlanMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum treatmentPlan filter for visit', index: 7 },
  { name: 'notes', mode: 'input', type: 'string', required: false, nullable: true, defaultValue: null, description: 'notes parameter for visit', index: 8 },
  { name: 'notes', mode: 'filter', type: 'string', required: false, nullable: true, defaultValue: null, description: 'notes parameter for visit', index: 8 },
  { name: 'notes', mode: 'sort', type: 'string', required: false, nullable: true, defaultValue: false, description: 'notes parameter for visit', index: 8 },
  { name: 'notes', mode: 'search', type: 'string', required: false, nullable: true, defaultValue: null, description: 'notes parameter for visit', index: 8 },
  { name: 'notes', mode: 'export', type: 'string', required: false, nullable: true, defaultValue: false, description: 'notes parameter for visit', index: 8 },
  { name: 'notesMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum notes filter for visit', index: 8 },
  { name: 'notesMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum notes filter for visit', index: 8 },
  { name: 'followUpDate', mode: 'input', type: 'string', required: false, nullable: true, defaultValue: null, description: 'followUpDate parameter for visit', index: 9 },
  { name: 'followUpDate', mode: 'filter', type: 'string', required: false, nullable: true, defaultValue: null, description: 'followUpDate parameter for visit', index: 9 },
  { name: 'followUpDate', mode: 'sort', type: 'string', required: false, nullable: true, defaultValue: false, description: 'followUpDate parameter for visit', index: 9 },
  { name: 'followUpDate', mode: 'search', type: 'string', required: false, nullable: true, defaultValue: null, description: 'followUpDate parameter for visit', index: 9 },
  { name: 'followUpDate', mode: 'export', type: 'string', required: false, nullable: true, defaultValue: false, description: 'followUpDate parameter for visit', index: 9 },
  { name: 'followUpDateMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum followUpDate filter for visit', index: 9 },
  { name: 'followUpDateMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum followUpDate filter for visit', index: 9 },
  { name: 'status', mode: 'input', type: 'string', required: false, nullable: true, defaultValue: null, description: 'status parameter for visit', index: 10 },
  { name: 'status', mode: 'filter', type: 'string', required: false, nullable: true, defaultValue: null, description: 'status parameter for visit', index: 10 },
  { name: 'status', mode: 'sort', type: 'string', required: false, nullable: true, defaultValue: false, description: 'status parameter for visit', index: 10 },
  { name: 'status', mode: 'search', type: 'string', required: false, nullable: true, defaultValue: null, description: 'status parameter for visit', index: 10 },
  { name: 'status', mode: 'export', type: 'string', required: false, nullable: true, defaultValue: false, description: 'status parameter for visit', index: 10 },
  { name: 'statusMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum status filter for visit', index: 10 },
  { name: 'statusMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum status filter for visit', index: 10 },
];

function get(name){return parameters.find(p=>p.name===name)||null;}
function list(mode){return mode?parameters.filter(p=>p.mode===mode):[...parameters];}
function required(){return parameters.filter(p=>p.required);}
function validateParameter(name,value){const p=get(name);if(!p)return {ok:false,code:'UNKNOWN_PARAMETER'};if(value===null&&p.nullable)return {ok:true};if(p.type==='number'&&typeof value!=='number')return {ok:false,code:'TYPE_ERROR'};if(p.type==='boolean'&&typeof value!=='boolean')return {ok:false,code:'TYPE_ERROR'};if(p.type==='string'&&typeof value!=='string')return {ok:false,code:'TYPE_ERROR'};return {ok:true};}
function validateObject(input={}){const errors=[];for(const p of required()){if(input[p.name]===undefined||input[p.name]===null||input[p.name]==='')errors.push({field:p.name,code:'REQUIRED'});}for(const [k,v] of Object.entries(input)){const result=validateParameter(k,v);if(!result.ok)errors.push({field:k,code:result.code});}return errors;}
function defaults(){return Object.fromEntries(parameters.filter(p=>p.defaultValue!==null).map(p=>[p.name,p.defaultValue]));}
function describe(){return {entity,parameterCount:parameters.length,parameters};}
module.exports={entity,parameters,get,list,required,validateParameter,validateObject,defaults,describe};
