'use strict';
// Complete parameter catalog for vital.
const entity='vital';
const parameters=[
  { name: 'patientId', mode: 'input', type: 'string', required: true, nullable: true, defaultValue: null, description: 'patientId parameter for vital', index: 1 },
  { name: 'patientId', mode: 'filter', type: 'string', required: true, nullable: true, defaultValue: null, description: 'patientId parameter for vital', index: 1 },
  { name: 'patientId', mode: 'sort', type: 'string', required: true, nullable: true, defaultValue: false, description: 'patientId parameter for vital', index: 1 },
  { name: 'patientId', mode: 'search', type: 'string', required: true, nullable: true, defaultValue: null, description: 'patientId parameter for vital', index: 1 },
  { name: 'patientId', mode: 'export', type: 'string', required: true, nullable: true, defaultValue: false, description: 'patientId parameter for vital', index: 1 },
  { name: 'patientIdMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum patientId filter for vital', index: 1 },
  { name: 'patientIdMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum patientId filter for vital', index: 1 },
  { name: 'visitId', mode: 'input', type: 'string', required: true, nullable: true, defaultValue: null, description: 'visitId parameter for vital', index: 2 },
  { name: 'visitId', mode: 'filter', type: 'string', required: true, nullable: true, defaultValue: null, description: 'visitId parameter for vital', index: 2 },
  { name: 'visitId', mode: 'sort', type: 'string', required: true, nullable: true, defaultValue: false, description: 'visitId parameter for vital', index: 2 },
  { name: 'visitId', mode: 'search', type: 'string', required: true, nullable: true, defaultValue: null, description: 'visitId parameter for vital', index: 2 },
  { name: 'visitId', mode: 'export', type: 'string', required: true, nullable: true, defaultValue: false, description: 'visitId parameter for vital', index: 2 },
  { name: 'visitIdMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum visitId filter for vital', index: 2 },
  { name: 'visitIdMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum visitId filter for vital', index: 2 },
  { name: 'recordedAt', mode: 'input', type: 'string', required: true, nullable: true, defaultValue: null, description: 'recordedAt parameter for vital', index: 3 },
  { name: 'recordedAt', mode: 'filter', type: 'string', required: true, nullable: true, defaultValue: null, description: 'recordedAt parameter for vital', index: 3 },
  { name: 'recordedAt', mode: 'sort', type: 'string', required: true, nullable: true, defaultValue: false, description: 'recordedAt parameter for vital', index: 3 },
  { name: 'recordedAt', mode: 'search', type: 'string', required: true, nullable: true, defaultValue: null, description: 'recordedAt parameter for vital', index: 3 },
  { name: 'recordedAt', mode: 'export', type: 'string', required: true, nullable: true, defaultValue: false, description: 'recordedAt parameter for vital', index: 3 },
  { name: 'recordedAtMin', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Minimum recordedAt filter for vital', index: 3 },
  { name: 'recordedAtMax', mode: 'range', type: 'string', required: false, nullable: true, defaultValue: null, description: 'Maximum recordedAt filter for vital', index: 3 },
  { name: 'temperature', mode: 'input', type: 'number', required: false, nullable: true, defaultValue: null, description: 'temperature parameter for vital', index: 4 },
  { name: 'temperature', mode: 'filter', type: 'number', required: false, nullable: true, defaultValue: null, description: 'temperature parameter for vital', index: 4 },
  { name: 'temperature', mode: 'sort', type: 'number', required: false, nullable: true, defaultValue: false, description: 'temperature parameter for vital', index: 4 },
  { name: 'temperature', mode: 'search', type: 'number', required: false, nullable: true, defaultValue: null, description: 'temperature parameter for vital', index: 4 },
  { name: 'temperature', mode: 'export', type: 'number', required: false, nullable: true, defaultValue: false, description: 'temperature parameter for vital', index: 4 },
  { name: 'temperatureMin', mode: 'range', type: 'number', required: false, nullable: true, defaultValue: null, description: 'Minimum temperature filter for vital', index: 4 },
  { name: 'temperatureMax', mode: 'range', type: 'number', required: false, nullable: true, defaultValue: null, description: 'Maximum temperature filter for vital', index: 4 },
  { name: 'heartRate', mode: 'input', type: 'number', required: false, nullable: true, defaultValue: null, description: 'heartRate parameter for vital', index: 5 },
  { name: 'heartRate', mode: 'filter', type: 'number', required: false, nullable: true, defaultValue: null, description: 'heartRate parameter for vital', index: 5 },
  { name: 'heartRate', mode: 'sort', type: 'number', required: false, nullable: true, defaultValue: false, description: 'heartRate parameter for vital', index: 5 },
  { name: 'heartRate', mode: 'search', type: 'number', required: false, nullable: true, defaultValue: null, description: 'heartRate parameter for vital', index: 5 },
  { name: 'heartRate', mode: 'export', type: 'number', required: false, nullable: true, defaultValue: false, description: 'heartRate parameter for vital', index: 5 },
  { name: 'heartRateMin', mode: 'range', type: 'number', required: false, nullable: true, defaultValue: null, description: 'Minimum heartRate filter for vital', index: 5 },
  { name: 'heartRateMax', mode: 'range', type: 'number', required: false, nullable: true, defaultValue: null, description: 'Maximum heartRate filter for vital', index: 5 },
  { name: 'respiratoryRate', mode: 'input', type: 'number', required: false, nullable: true, defaultValue: null, description: 'respiratoryRate parameter for vital', index: 6 },
  { name: 'respiratoryRate', mode: 'filter', type: 'number', required: false, nullable: true, defaultValue: null, description: 'respiratoryRate parameter for vital', index: 6 },
  { name: 'respiratoryRate', mode: 'sort', type: 'number', required: false, nullable: true, defaultValue: false, description: 'respiratoryRate parameter for vital', index: 6 },
  { name: 'respiratoryRate', mode: 'search', type: 'number', required: false, nullable: true, defaultValue: null, description: 'respiratoryRate parameter for vital', index: 6 },
  { name: 'respiratoryRate', mode: 'export', type: 'number', required: false, nullable: true, defaultValue: false, description: 'respiratoryRate parameter for vital', index: 6 },
  { name: 'respiratoryRateMin', mode: 'range', type: 'number', required: false, nullable: true, defaultValue: null, description: 'Minimum respiratoryRate filter for vital', index: 6 },
  { name: 'respiratoryRateMax', mode: 'range', type: 'number', required: false, nullable: true, defaultValue: null, description: 'Maximum respiratoryRate filter for vital', index: 6 },
  { name: 'systolicBp', mode: 'input', type: 'number', required: false, nullable: true, defaultValue: null, description: 'systolicBp parameter for vital', index: 7 },
  { name: 'systolicBp', mode: 'filter', type: 'number', required: false, nullable: true, defaultValue: null, description: 'systolicBp parameter for vital', index: 7 },
  { name: 'systolicBp', mode: 'sort', type: 'number', required: false, nullable: true, defaultValue: false, description: 'systolicBp parameter for vital', index: 7 },
  { name: 'systolicBp', mode: 'search', type: 'number', required: false, nullable: true, defaultValue: null, description: 'systolicBp parameter for vital', index: 7 },
  { name: 'systolicBp', mode: 'export', type: 'number', required: false, nullable: true, defaultValue: false, description: 'systolicBp parameter for vital', index: 7 },
  { name: 'systolicBpMin', mode: 'range', type: 'number', required: false, nullable: true, defaultValue: null, description: 'Minimum systolicBp filter for vital', index: 7 },
  { name: 'systolicBpMax', mode: 'range', type: 'number', required: false, nullable: true, defaultValue: null, description: 'Maximum systolicBp filter for vital', index: 7 },
  { name: 'diastolicBp', mode: 'input', type: 'number', required: false, nullable: true, defaultValue: null, description: 'diastolicBp parameter for vital', index: 8 },
  { name: 'diastolicBp', mode: 'filter', type: 'number', required: false, nullable: true, defaultValue: null, description: 'diastolicBp parameter for vital', index: 8 },
  { name: 'diastolicBp', mode: 'sort', type: 'number', required: false, nullable: true, defaultValue: false, description: 'diastolicBp parameter for vital', index: 8 },
  { name: 'diastolicBp', mode: 'search', type: 'number', required: false, nullable: true, defaultValue: null, description: 'diastolicBp parameter for vital', index: 8 },
  { name: 'diastolicBp', mode: 'export', type: 'number', required: false, nullable: true, defaultValue: false, description: 'diastolicBp parameter for vital', index: 8 },
  { name: 'diastolicBpMin', mode: 'range', type: 'number', required: false, nullable: true, defaultValue: null, description: 'Minimum diastolicBp filter for vital', index: 8 },
  { name: 'diastolicBpMax', mode: 'range', type: 'number', required: false, nullable: true, defaultValue: null, description: 'Maximum diastolicBp filter for vital', index: 8 },
  { name: 'oxygenSaturation', mode: 'input', type: 'number', required: false, nullable: true, defaultValue: null, description: 'oxygenSaturation parameter for vital', index: 9 },
  { name: 'oxygenSaturation', mode: 'filter', type: 'number', required: false, nullable: true, defaultValue: null, description: 'oxygenSaturation parameter for vital', index: 9 },
  { name: 'oxygenSaturation', mode: 'sort', type: 'number', required: false, nullable: true, defaultValue: false, description: 'oxygenSaturation parameter for vital', index: 9 },
  { name: 'oxygenSaturation', mode: 'search', type: 'number', required: false, nullable: true, defaultValue: null, description: 'oxygenSaturation parameter for vital', index: 9 },
  { name: 'oxygenSaturation', mode: 'export', type: 'number', required: false, nullable: true, defaultValue: false, description: 'oxygenSaturation parameter for vital', index: 9 },
  { name: 'oxygenSaturationMin', mode: 'range', type: 'number', required: false, nullable: true, defaultValue: null, description: 'Minimum oxygenSaturation filter for vital', index: 9 },
  { name: 'oxygenSaturationMax', mode: 'range', type: 'number', required: false, nullable: true, defaultValue: null, description: 'Maximum oxygenSaturation filter for vital', index: 9 },
  { name: 'weightKg', mode: 'input', type: 'number', required: false, nullable: true, defaultValue: null, description: 'weightKg parameter for vital', index: 10 },
  { name: 'weightKg', mode: 'filter', type: 'number', required: false, nullable: true, defaultValue: null, description: 'weightKg parameter for vital', index: 10 },
  { name: 'weightKg', mode: 'sort', type: 'number', required: false, nullable: true, defaultValue: false, description: 'weightKg parameter for vital', index: 10 },
  { name: 'weightKg', mode: 'search', type: 'number', required: false, nullable: true, defaultValue: null, description: 'weightKg parameter for vital', index: 10 },
  { name: 'weightKg', mode: 'export', type: 'number', required: false, nullable: true, defaultValue: false, description: 'weightKg parameter for vital', index: 10 },
  { name: 'weightKgMin', mode: 'range', type: 'number', required: false, nullable: true, defaultValue: null, description: 'Minimum weightKg filter for vital', index: 10 },
  { name: 'weightKgMax', mode: 'range', type: 'number', required: false, nullable: true, defaultValue: null, description: 'Maximum weightKg filter for vital', index: 10 },
  { name: 'heightCm', mode: 'input', type: 'number', required: false, nullable: true, defaultValue: null, description: 'heightCm parameter for vital', index: 11 },
  { name: 'heightCm', mode: 'filter', type: 'number', required: false, nullable: true, defaultValue: null, description: 'heightCm parameter for vital', index: 11 },
  { name: 'heightCm', mode: 'sort', type: 'number', required: false, nullable: true, defaultValue: false, description: 'heightCm parameter for vital', index: 11 },
  { name: 'heightCm', mode: 'search', type: 'number', required: false, nullable: true, defaultValue: null, description: 'heightCm parameter for vital', index: 11 },
  { name: 'heightCm', mode: 'export', type: 'number', required: false, nullable: true, defaultValue: false, description: 'heightCm parameter for vital', index: 11 },
  { name: 'heightCmMin', mode: 'range', type: 'number', required: false, nullable: true, defaultValue: null, description: 'Minimum heightCm filter for vital', index: 11 },
  { name: 'heightCmMax', mode: 'range', type: 'number', required: false, nullable: true, defaultValue: null, description: 'Maximum heightCm filter for vital', index: 11 },
  { name: 'bmi', mode: 'input', type: 'number', required: false, nullable: true, defaultValue: null, description: 'bmi parameter for vital', index: 12 },
  { name: 'bmi', mode: 'filter', type: 'number', required: false, nullable: true, defaultValue: null, description: 'bmi parameter for vital', index: 12 },
  { name: 'bmi', mode: 'sort', type: 'number', required: false, nullable: true, defaultValue: false, description: 'bmi parameter for vital', index: 12 },
  { name: 'bmi', mode: 'search', type: 'number', required: false, nullable: true, defaultValue: null, description: 'bmi parameter for vital', index: 12 },
  { name: 'bmi', mode: 'export', type: 'number', required: false, nullable: true, defaultValue: false, description: 'bmi parameter for vital', index: 12 },
  { name: 'bmiMin', mode: 'range', type: 'number', required: false, nullable: true, defaultValue: null, description: 'Minimum bmi filter for vital', index: 12 },
  { name: 'bmiMax', mode: 'range', type: 'number', required: false, nullable: true, defaultValue: null, description: 'Maximum bmi filter for vital', index: 12 },
];

function get(name){return parameters.find(p=>p.name===name)||null;}
function list(mode){return mode?parameters.filter(p=>p.mode===mode):[...parameters];}
function required(){return parameters.filter(p=>p.required);}
function validateParameter(name,value){const p=get(name);if(!p)return {ok:false,code:'UNKNOWN_PARAMETER'};if(value===null&&p.nullable)return {ok:true};if(p.type==='number'&&typeof value!=='number')return {ok:false,code:'TYPE_ERROR'};if(p.type==='boolean'&&typeof value!=='boolean')return {ok:false,code:'TYPE_ERROR'};if(p.type==='string'&&typeof value!=='string')return {ok:false,code:'TYPE_ERROR'};return {ok:true};}
function validateObject(input={}){const errors=[];for(const p of required()){if(input[p.name]===undefined||input[p.name]===null||input[p.name]==='')errors.push({field:p.name,code:'REQUIRED'});}for(const [k,v] of Object.entries(input)){const result=validateParameter(k,v);if(!result.ok)errors.push({field:k,code:result.code});}return errors;}
function defaults(){return Object.fromEntries(parameters.filter(p=>p.defaultValue!==null).map(p=>[p.name,p.defaultValue]));}
function describe(){return {entity,parameterCount:parameters.length,parameters};}
module.exports={entity,parameters,get,list,required,validateParameter,validateObject,defaults,describe};
